namespace ModuloAdicional
{
	// Token: 0x02000008 RID: 8
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FormModificarTicket : global::System.Windows.Forms.Form
	{
		// Token: 0x06000070 RID: 112 RVA: 0x00007850 File Offset: 0x00005A50
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000071 RID: 113 RVA: 0x000078A0 File Offset: 0x00005AA0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.FormModificarTicket));
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.lblidturno = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.lblidmesero = new global::System.Windows.Forms.Label();
			this.lblestacionName = new global::System.Windows.Forms.Label();
			this.lblhoradelticket = new global::System.Windows.Forms.Label();
			this.lblNumeroFilaFormaPago = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Panel13 = new global::System.Windows.Forms.Panel();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.lblFechaInicio = new global::System.Windows.Forms.Label();
			this.lblFechaFin = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.groupPeriodo = new global::System.Windows.Forms.GroupBox();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.BtnHorario = new global::System.Windows.Forms.PictureBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.lblfechahoy = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.cmbAnio = new global::System.Windows.Forms.ComboBox();
			this.dateHoraFin = new global::System.Windows.Forms.DateTimePicker();
			this.dateHoraIni = new global::System.Windows.Forms.DateTimePicker();
			this.dateFechaFin = new global::System.Windows.Forms.DateTimePicker();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.dateFechaIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.groupParametros = new global::System.Windows.Forms.GroupBox();
			this.btnVistaPrevia = new global::System.Windows.Forms.Button();
			this.cmbxEmpresa = new global::System.Windows.Forms.ComboBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.cmbxTipo = new global::System.Windows.Forms.ComboBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.chkReemplazar = new global::System.Windows.Forms.CheckBox();
			this.Panel14 = new global::System.Windows.Forms.Panel();
			this.DgvTicketsPeriodo = new global::System.Windows.Forms.DataGridView();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.dgvNotas = new global::System.Windows.Forms.DataGridView();
			this.Panel5 = new global::System.Windows.Forms.Panel();
			this.DgvFormasPago = new global::System.Windows.Forms.DataGridView();
			this.Panel9 = new global::System.Windows.Forms.Panel();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.lblFacturado = new global::System.Windows.Forms.Label();
			this.CheckBox_Facturado = new global::System.Windows.Forms.CheckBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.txtTotal = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txtSubtotal = new global::System.Windows.Forms.TextBox();
			this.txtDescuento = new global::System.Windows.Forms.TextBox();
			this.txtPropina = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.lblPropina = new global::System.Windows.Forms.Label();
			this.Panel_MovtosTicket = new global::System.Windows.Forms.Panel();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.btnAddMovto = new global::System.Windows.Forms.Button();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Button4 = new global::System.Windows.Forms.Button();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.txtBuscarFolio = new global::System.Windows.Forms.TextBox();
			this.txtSerie = new global::System.Windows.Forms.TextBox();
			this.lblSerie = new global::System.Windows.Forms.Label();
			this.PanelBuscarProducto = new global::System.Windows.Forms.Panel();
			this.Panel17 = new global::System.Windows.Forms.Panel();
			this.dgwProductos = new global::System.Windows.Forms.DataGridView();
			this.Panel8 = new global::System.Windows.Forms.Panel();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.txtBuscarProducto = new global::System.Windows.Forms.TextBox();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.Panel1.SuspendLayout();
			this.groupPeriodo.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.BtnHorario).BeginInit();
			this.groupParametros.SuspendLayout();
			this.Panel14.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DgvTicketsPeriodo).BeginInit();
			this.Panel2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).BeginInit();
			this.Panel5.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DgvFormasPago).BeginInit();
			this.Panel9.SuspendLayout();
			this.Panel6.SuspendLayout();
			this.Panel_MovtosTicket.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.PanelBuscarProducto.SuspendLayout();
			this.Panel17.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgwProductos).BeginInit();
			this.Panel8.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			base.SuspendLayout();
			this.Panel1.AutoSize = true;
			this.Panel1.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.Label12);
			this.Panel1.Controls.Add(this.lblidturno);
			this.Panel1.Controls.Add(this.TextBox1);
			this.Panel1.Controls.Add(this.lblidmesero);
			this.Panel1.Controls.Add(this.lblestacionName);
			this.Panel1.Controls.Add(this.lblhoradelticket);
			this.Panel1.Controls.Add(this.lblNumeroFilaFormaPago);
			this.Panel1.Controls.Add(this.Label32);
			this.Panel1.Controls.Add(this.Panel13);
			this.Panel1.Controls.Add(this.Label31);
			this.Panel1.Controls.Add(this.Panel3);
			this.Panel1.Controls.Add(this.Label30);
			this.Panel1.Controls.Add(this.Panel4);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Controls.Add(this.Panel7);
			this.Panel1.Controls.Add(this.lblFechaInicio);
			this.Panel1.Controls.Add(this.lblFechaFin);
			this.Panel1.Controls.Add(this.Label19);
			this.Panel1.Controls.Add(this.groupPeriodo);
			this.Panel1.Controls.Add(this.groupParametros);
			this.Panel1.Controls.Add(this.chkReemplazar);
			this.Panel1.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(1105, 147);
			this.Panel1.TabIndex = 144;
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.175f, global::System.Drawing.FontStyle.Bold);
			this.Label12.ForeColor = global::System.Drawing.Color.Black;
			this.Label12.Location = new global::System.Drawing.Point(1010, 31);
			this.Label12.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(103, 13);
			this.Label12.TabIndex = 49;
			this.Label12.Text = "Desc. Productos:";
			this.Label12.Visible = false;
			this.lblidturno.AutoSize = true;
			this.lblidturno.Location = new global::System.Drawing.Point(944, 28);
			this.lblidturno.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblidturno.Name = "lblidturno";
			this.lblidturno.Size = new global::System.Drawing.Size(49, 13);
			this.lblidturno.TabIndex = 199;
			this.lblidturno.Text = "lblidturno";
			this.lblidturno.Visible = false;
			this.TextBox1.BackColor = global::System.Drawing.Color.White;
			this.TextBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TextBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8f);
			this.TextBox1.Location = new global::System.Drawing.Point(1037, 9);
			this.TextBox1.Margin = new global::System.Windows.Forms.Padding(2);
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.ReadOnly = true;
			this.TextBox1.Size = new global::System.Drawing.Size(52, 13);
			this.TextBox1.TabIndex = 48;
			this.TextBox1.Visible = false;
			this.lblidmesero.AutoSize = true;
			this.lblidmesero.Location = new global::System.Drawing.Point(961, 74);
			this.lblidmesero.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblidmesero.Name = "lblidmesero";
			this.lblidmesero.Size = new global::System.Drawing.Size(59, 13);
			this.lblidmesero.TabIndex = 198;
			this.lblidmesero.Text = "lblidmesero";
			this.lblidmesero.Visible = false;
			this.lblestacionName.AutoSize = true;
			this.lblestacionName.Location = new global::System.Drawing.Point(787, 21);
			this.lblestacionName.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblestacionName.Name = "lblestacionName";
			this.lblestacionName.Size = new global::System.Drawing.Size(85, 13);
			this.lblestacionName.TabIndex = 197;
			this.lblestacionName.Text = "lblestacionName";
			this.lblestacionName.Visible = false;
			this.lblhoradelticket.AutoSize = true;
			this.lblhoradelticket.Location = new global::System.Drawing.Point(853, 113);
			this.lblhoradelticket.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblhoradelticket.Name = "lblhoradelticket";
			this.lblhoradelticket.Size = new global::System.Drawing.Size(78, 13);
			this.lblhoradelticket.TabIndex = 196;
			this.lblhoradelticket.Text = "lblhoradelticket";
			this.lblhoradelticket.Visible = false;
			this.lblNumeroFilaFormaPago.AutoSize = true;
			this.lblNumeroFilaFormaPago.Location = new global::System.Drawing.Point(758, 98);
			this.lblNumeroFilaFormaPago.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblNumeroFilaFormaPago.Name = "lblNumeroFilaFormaPago";
			this.lblNumeroFilaFormaPago.Size = new global::System.Drawing.Size(45, 13);
			this.lblNumeroFilaFormaPago.TabIndex = 195;
			this.lblNumeroFilaFormaPago.Text = "Label13";
			this.lblNumeroFilaFormaPago.Visible = false;
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label32.Location = new global::System.Drawing.Point(541, 112);
			this.Label32.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label32.Name = "Label32";
			this.Label32.Size = new global::System.Drawing.Size(173, 13);
			this.Label32.TabIndex = 194;
			this.Label32.Text = "Cuentas en Efectivo y Tarjeta";
			this.Panel13.BackColor = global::System.Drawing.Color.Black;
			this.Panel13.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel13.Location = new global::System.Drawing.Point(502, 113);
			this.Panel13.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel13.Name = "Panel13";
			this.Panel13.Size = new global::System.Drawing.Size(32, 12);
			this.Panel13.TabIndex = 193;
			this.Label31.AutoSize = true;
			this.Label31.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label31.Location = new global::System.Drawing.Point(541, 96);
			this.Label31.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label31.Name = "Label31";
			this.Label31.Size = new global::System.Drawing.Size(121, 13);
			this.Label31.TabIndex = 192;
			this.Label31.Text = "Cuentas en Efectivo";
			this.Panel3.BackColor = global::System.Drawing.Color.Green;
			this.Panel3.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel3.Location = new global::System.Drawing.Point(502, 98);
			this.Panel3.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(32, 12);
			this.Panel3.TabIndex = 191;
			this.Label30.AutoSize = true;
			this.Label30.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label30.Location = new global::System.Drawing.Point(541, 67);
			this.Label30.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label30.Name = "Label30";
			this.Label30.Size = new global::System.Drawing.Size(151, 26);
			this.Label30.TabIndex = 190;
			this.Label30.Text = "Productos con Descuento\r\no Precio $ 0";
			this.Panel4.BackColor = global::System.Drawing.Color.LightBlue;
			this.Panel4.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel4.Location = new global::System.Drawing.Point(502, 67);
			this.Panel4.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(32, 12);
			this.Panel4.TabIndex = 189;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(968, 100);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(128, 13);
			this.Label1.TabIndex = 188;
			this.Label1.Text = "Productos a modificar";
			this.Label1.Visible = false;
			this.Panel7.BackColor = global::System.Drawing.Color.Red;
			this.Panel7.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel7.Location = new global::System.Drawing.Point(929, 102);
			this.Panel7.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel7.Name = "Panel7";
			this.Panel7.Size = new global::System.Drawing.Size(32, 12);
			this.Panel7.TabIndex = 187;
			this.Panel7.Visible = false;
			this.lblFechaInicio.AutoSize = true;
			this.lblFechaInicio.Location = new global::System.Drawing.Point(173, 3);
			this.lblFechaInicio.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblFechaInicio.Name = "lblFechaInicio";
			this.lblFechaInicio.Size = new global::System.Drawing.Size(72, 13);
			this.lblFechaInicio.TabIndex = 93;
			this.lblFechaInicio.Text = "lblFechaInicio";
			this.lblFechaInicio.Visible = false;
			this.lblFechaFin.AutoSize = true;
			this.lblFechaFin.Location = new global::System.Drawing.Point(220, 4);
			this.lblFechaFin.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblFechaFin.Name = "lblFechaFin";
			this.lblFechaFin.Size = new global::System.Drawing.Size(61, 13);
			this.lblFechaFin.TabIndex = 94;
			this.lblFechaFin.Text = "lblFechaFin";
			this.lblFechaFin.Visible = false;
			this.Label19.AutoSize = true;
			this.Label19.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.Red;
			this.Label19.Location = new global::System.Drawing.Point(500, 10);
			this.Label19.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(212, 27);
			this.Label19.TabIndex = 145;
			this.Label19.Text = "*Nota\r\nGenera un respaldo antes de aplicar el proceso,\r\nesta accion es irreversible.\r\n";
			this.groupPeriodo.Controls.Add(this.Label27);
			this.groupPeriodo.Controls.Add(this.BtnHorario);
			this.groupPeriodo.Controls.Add(this.Label18);
			this.groupPeriodo.Controls.Add(this.ComboBox1);
			this.groupPeriodo.Controls.Add(this.lblfechahoy);
			this.groupPeriodo.Controls.Add(this.Label17);
			this.groupPeriodo.Controls.Add(this.cmbAnio);
			this.groupPeriodo.Controls.Add(this.dateHoraFin);
			this.groupPeriodo.Controls.Add(this.dateHoraIni);
			this.groupPeriodo.Controls.Add(this.dateFechaFin);
			this.groupPeriodo.Controls.Add(this.Label3);
			this.groupPeriodo.Controls.Add(this.dateFechaIni);
			this.groupPeriodo.Controls.Add(this.Label8);
			this.groupPeriodo.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.groupPeriodo.Location = new global::System.Drawing.Point(12, 6);
			this.groupPeriodo.Name = "groupPeriodo";
			this.groupPeriodo.Size = new global::System.Drawing.Size(293, 137);
			this.groupPeriodo.TabIndex = 1;
			this.groupPeriodo.TabStop = false;
			this.groupPeriodo.Text = "Periodo";
			this.Label27.AutoSize = true;
			this.Label27.Location = new global::System.Drawing.Point(181, 90);
			this.Label27.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label27.Name = "Label27";
			this.Label27.Size = new global::System.Drawing.Size(69, 26);
			this.Label27.TabIndex = 91;
			this.Label27.Text = "Editar horario\r\nde Turnos:";
			this.BtnHorario.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.BtnHorario.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnHorario.Image");
			this.BtnHorario.Location = new global::System.Drawing.Point(257, 90);
			this.BtnHorario.Margin = new global::System.Windows.Forms.Padding(2);
			this.BtnHorario.Name = "BtnHorario";
			this.BtnHorario.Size = new global::System.Drawing.Size(25, 26);
			this.BtnHorario.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.BtnHorario.TabIndex = 90;
			this.BtnHorario.TabStop = false;
			this.Label18.AutoSize = true;
			this.Label18.Location = new global::System.Drawing.Point(134, 16);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(30, 13);
			this.Label18.TabIndex = 89;
			this.Label18.Text = "Mes:";
			this.ComboBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(170, 15);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(116, 21);
			this.ComboBox1.TabIndex = 88;
			this.lblfechahoy.AutoSize = true;
			this.lblfechahoy.Location = new global::System.Drawing.Point(161, -6);
			this.lblfechahoy.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblfechahoy.Name = "lblfechahoy";
			this.lblfechahoy.Size = new global::System.Drawing.Size(64, 13);
			this.lblfechahoy.TabIndex = 95;
			this.lblfechahoy.Text = "lblFechahoy";
			this.lblfechahoy.Visible = false;
			this.Label17.AutoSize = true;
			this.Label17.Location = new global::System.Drawing.Point(4, 16);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(32, 13);
			this.Label17.TabIndex = 87;
			this.Label17.Text = "Año: ";
			this.cmbAnio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbAnio.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAnio.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbAnio.FormattingEnabled = true;
			this.cmbAnio.Location = new global::System.Drawing.Point(43, 15);
			this.cmbAnio.Name = "cmbAnio";
			this.cmbAnio.Size = new global::System.Drawing.Size(85, 21);
			this.cmbAnio.Sorted = true;
			this.cmbAnio.TabIndex = 86;
			this.dateHoraFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateHoraFin.Enabled = false;
			this.dateHoraFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraFin.Location = new global::System.Drawing.Point(191, 67);
			this.dateHoraFin.Margin = new global::System.Windows.Forms.Padding(2);
			this.dateHoraFin.Name = "dateHoraFin";
			this.dateHoraFin.ShowUpDown = true;
			this.dateHoraFin.Size = new global::System.Drawing.Size(93, 20);
			this.dateHoraFin.TabIndex = 3;
			this.dateHoraFin.TabStop = false;
			this.dateHoraFin.Value = new global::System.DateTime(2022, 6, 15, 5, 59, 59, 0);
			this.dateHoraIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateHoraIni.Enabled = false;
			this.dateHoraIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraIni.Location = new global::System.Drawing.Point(191, 40);
			this.dateHoraIni.Margin = new global::System.Windows.Forms.Padding(2);
			this.dateHoraIni.Name = "dateHoraIni";
			this.dateHoraIni.ShowUpDown = true;
			this.dateHoraIni.Size = new global::System.Drawing.Size(93, 20);
			this.dateHoraIni.TabIndex = 1;
			this.dateHoraIni.TabStop = false;
			this.dateHoraIni.Value = new global::System.DateTime(2022, 6, 15, 6, 0, 0, 0);
			this.dateFechaFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Custom;
			this.dateFechaFin.Location = new global::System.Drawing.Point(84, 67);
			this.dateFechaFin.Margin = new global::System.Windows.Forms.Padding(2);
			this.dateFechaFin.Name = "dateFechaFin";
			this.dateFechaFin.Size = new global::System.Drawing.Size(100, 20);
			this.dateFechaFin.TabIndex = 1;
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(8, 69);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(72, 13);
			this.Label3.TabIndex = 82;
			this.Label3.Text = "Fecha FInal : ";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dateFechaIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.dateFechaIni.Location = new global::System.Drawing.Point(84, 40);
			this.dateFechaIni.Margin = new global::System.Windows.Forms.Padding(2);
			this.dateFechaIni.MaxDate = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.dateFechaIni.MinDate = new global::System.DateTime(2017, 1, 1, 0, 0, 0, 0);
			this.dateFechaIni.Name = "dateFechaIni";
			this.dateFechaIni.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dateFechaIni.Size = new global::System.Drawing.Size(100, 20);
			this.dateFechaIni.TabIndex = 0;
			this.dateFechaIni.Value = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(5, 41);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(76, 13);
			this.Label8.TabIndex = 80;
			this.Label8.Text = "Fecha Inicial : ";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.groupParametros.Controls.Add(this.btnVistaPrevia);
			this.groupParametros.Controls.Add(this.cmbxEmpresa);
			this.groupParametros.Controls.Add(this.Label4);
			this.groupParametros.Controls.Add(this.cmbxTipo);
			this.groupParametros.Controls.Add(this.Label5);
			this.groupParametros.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.groupParametros.Location = new global::System.Drawing.Point(306, 6);
			this.groupParametros.Name = "groupParametros";
			this.groupParametros.Size = new global::System.Drawing.Size(181, 138);
			this.groupParametros.TabIndex = 0;
			this.groupParametros.TabStop = false;
			this.groupParametros.Text = "Parametros";
			this.btnVistaPrevia.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.btnVistaPrevia.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnVistaPrevia.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.btnVistaPrevia.FlatAppearance.BorderSize = 2;
			this.btnVistaPrevia.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnVistaPrevia.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 13.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnVistaPrevia.ForeColor = global::System.Drawing.Color.White;
			this.btnVistaPrevia.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnVistaPrevia.Image");
			this.btnVistaPrevia.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnVistaPrevia.Location = new global::System.Drawing.Point(13, 80);
			this.btnVistaPrevia.Name = "btnVistaPrevia";
			this.btnVistaPrevia.Size = new global::System.Drawing.Size(156, 51);
			this.btnVistaPrevia.TabIndex = 17;
			this.btnVistaPrevia.Text = "Ver Tickets";
			this.btnVistaPrevia.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.btnVistaPrevia.UseVisualStyleBackColor = false;
			this.cmbxEmpresa.BackColor = global::System.Drawing.SystemColors.Window;
			this.cmbxEmpresa.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbxEmpresa.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbxEmpresa.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbxEmpresa.FormattingEnabled = true;
			this.cmbxEmpresa.Location = new global::System.Drawing.Point(86, 18);
			this.cmbxEmpresa.Margin = new global::System.Windows.Forms.Padding(2);
			this.cmbxEmpresa.Name = "cmbxEmpresa";
			this.cmbxEmpresa.Size = new global::System.Drawing.Size(85, 21);
			this.cmbxEmpresa.TabIndex = 3;
			this.Label4.AutoSize = true;
			this.Label4.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.Label4.Location = new global::System.Drawing.Point(7, 20);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(54, 13);
			this.Label4.TabIndex = 91;
			this.Label4.Text = "Empresa :";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.cmbxTipo.BackColor = global::System.Drawing.SystemColors.Window;
			this.cmbxTipo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbxTipo.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbxTipo.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbxTipo.FormattingEnabled = true;
			this.cmbxTipo.Location = new global::System.Drawing.Point(44, 40);
			this.cmbxTipo.Margin = new global::System.Windows.Forms.Padding(2);
			this.cmbxTipo.Name = "cmbxTipo";
			this.cmbxTipo.Size = new global::System.Drawing.Size(127, 21);
			this.cmbxTipo.TabIndex = 4;
			this.Label5.AutoSize = true;
			this.Label5.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.Label5.Location = new global::System.Drawing.Point(7, 41);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(34, 13);
			this.Label5.TabIndex = 26;
			this.Label5.Text = "Tipo :";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.chkReemplazar.AutoSize = true;
			this.chkReemplazar.Cursor = global::System.Windows.Forms.Cursors.Arrow;
			this.chkReemplazar.Location = new global::System.Drawing.Point(214, 3);
			this.chkReemplazar.Name = "chkReemplazar";
			this.chkReemplazar.Size = new global::System.Drawing.Size(82, 17);
			this.chkReemplazar.TabIndex = 16;
			this.chkReemplazar.Text = "Reemplazar";
			this.chkReemplazar.UseVisualStyleBackColor = true;
			this.chkReemplazar.Visible = false;
			this.Panel14.Controls.Add(this.DgvTicketsPeriodo);
			this.Panel14.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Panel14.Location = new global::System.Drawing.Point(0, 147);
			this.Panel14.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel14.Name = "Panel14";
			this.Panel14.Size = new global::System.Drawing.Size(465, 527);
			this.Panel14.TabIndex = 145;
			this.DgvTicketsPeriodo.AllowUserToAddRows = false;
			this.DgvTicketsPeriodo.AllowUserToDeleteRows = false;
			this.DgvTicketsPeriodo.AllowUserToResizeColumns = false;
			this.DgvTicketsPeriodo.AllowUserToResizeRows = false;
			this.DgvTicketsPeriodo.BackgroundColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.DgvTicketsPeriodo.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DgvTicketsPeriodo.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DgvTicketsPeriodo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DgvTicketsPeriodo.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DgvTicketsPeriodo.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.DgvTicketsPeriodo.Location = new global::System.Drawing.Point(0, 0);
			this.DgvTicketsPeriodo.Margin = new global::System.Windows.Forms.Padding(2);
			this.DgvTicketsPeriodo.MultiSelect = false;
			this.DgvTicketsPeriodo.Name = "DgvTicketsPeriodo";
			this.DgvTicketsPeriodo.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.DgvTicketsPeriodo.RowHeadersVisible = false;
			this.DgvTicketsPeriodo.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.DgvTicketsPeriodo.RowTemplate.Height = 24;
			this.DgvTicketsPeriodo.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DgvTicketsPeriodo.Size = new global::System.Drawing.Size(465, 527);
			this.DgvTicketsPeriodo.TabIndex = 27;
			this.Panel2.Controls.Add(this.dgvNotas);
			this.Panel2.Controls.Add(this.Panel5);
			this.Panel2.Controls.Add(this.Panel6);
			this.Panel2.Controls.Add(this.Panel_MovtosTicket);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel2.Location = new global::System.Drawing.Point(465, 147);
			this.Panel2.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(640, 527);
			this.Panel2.TabIndex = 146;
			this.dgvNotas.AllowUserToAddRows = false;
			this.dgvNotas.AllowUserToDeleteRows = false;
			this.dgvNotas.AllowUserToResizeColumns = false;
			this.dgvNotas.AllowUserToResizeRows = false;
			this.dgvNotas.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgvNotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvNotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvNotas.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgvNotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvNotas.Location = new global::System.Drawing.Point(0, 103);
			this.dgvNotas.Margin = new global::System.Windows.Forms.Padding(2);
			this.dgvNotas.MultiSelect = false;
			this.dgvNotas.Name = "dgvNotas";
			this.dgvNotas.RowHeadersVisible = false;
			this.dgvNotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvNotas.RowTemplate.Height = 24;
			this.dgvNotas.Size = new global::System.Drawing.Size(640, 282);
			this.dgvNotas.TabIndex = 25;
			this.Panel5.Controls.Add(this.DgvFormasPago);
			this.Panel5.Controls.Add(this.Panel9);
			this.Panel5.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel5.Location = new global::System.Drawing.Point(0, 385);
			this.Panel5.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel5.Name = "Panel5";
			this.Panel5.Size = new global::System.Drawing.Size(640, 142);
			this.Panel5.TabIndex = 27;
			this.DgvFormasPago.AllowUserToAddRows = false;
			this.DgvFormasPago.AllowUserToDeleteRows = false;
			this.DgvFormasPago.AllowUserToResizeColumns = false;
			this.DgvFormasPago.AllowUserToResizeRows = false;
			this.DgvFormasPago.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.DgvFormasPago.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DgvFormasPago.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DgvFormasPago.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DgvFormasPago.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.DgvFormasPago.Location = new global::System.Drawing.Point(0, 24);
			this.DgvFormasPago.Margin = new global::System.Windows.Forms.Padding(2);
			this.DgvFormasPago.MultiSelect = false;
			this.DgvFormasPago.Name = "DgvFormasPago";
			this.DgvFormasPago.ReadOnly = true;
			this.DgvFormasPago.RowHeadersVisible = false;
			this.DgvFormasPago.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.DgvFormasPago.RowTemplate.Height = 24;
			this.DgvFormasPago.Size = new global::System.Drawing.Size(640, 118);
			this.DgvFormasPago.TabIndex = 26;
			this.Panel9.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel9.Controls.Add(this.Label11);
			this.Panel9.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel9.Location = new global::System.Drawing.Point(0, 0);
			this.Panel9.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel9.Name = "Panel9";
			this.Panel9.Size = new global::System.Drawing.Size(640, 24);
			this.Panel9.TabIndex = 27;
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.Location = new global::System.Drawing.Point(6, 5);
			this.Label11.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(173, 13);
			this.Label11.TabIndex = 0;
			this.Label11.Text = "Formas de Pago de la cuenta";
			this.Panel6.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel6.Controls.Add(this.lblFacturado);
			this.Panel6.Controls.Add(this.CheckBox_Facturado);
			this.Panel6.Controls.Add(this.Label9);
			this.Panel6.Controls.Add(this.txtTotal);
			this.Panel6.Controls.Add(this.Label7);
			this.Panel6.Controls.Add(this.Label2);
			this.Panel6.Controls.Add(this.txtSubtotal);
			this.Panel6.Controls.Add(this.txtDescuento);
			this.Panel6.Controls.Add(this.txtPropina);
			this.Panel6.Controls.Add(this.Label6);
			this.Panel6.Controls.Add(this.lblPropina);
			this.Panel6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel6.Location = new global::System.Drawing.Point(0, 57);
			this.Panel6.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(640, 46);
			this.Panel6.TabIndex = 1;
			this.lblFacturado.AutoSize = true;
			this.lblFacturado.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.8f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblFacturado.Location = new global::System.Drawing.Point(91, 27);
			this.lblFacturado.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblFacturado.Name = "lblFacturado";
			this.lblFacturado.Size = new global::System.Drawing.Size(11, 13);
			this.lblFacturado.TabIndex = 48;
			this.lblFacturado.Text = ".";
			this.CheckBox_Facturado.AutoSize = true;
			this.CheckBox_Facturado.Enabled = false;
			this.CheckBox_Facturado.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox_Facturado.Location = new global::System.Drawing.Point(10, 25);
			this.CheckBox_Facturado.Margin = new global::System.Windows.Forms.Padding(2);
			this.CheckBox_Facturado.Name = "CheckBox_Facturado";
			this.CheckBox_Facturado.Size = new global::System.Drawing.Size(83, 17);
			this.CheckBox_Facturado.TabIndex = 47;
			this.CheckBox_Facturado.Text = "Facturado";
			this.CheckBox_Facturado.UseVisualStyleBackColor = true;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.ForeColor = global::System.Drawing.Color.Black;
			this.Label9.Location = new global::System.Drawing.Point(161, 7);
			this.Label9.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(16, 13);
			this.Label9.TabIndex = 41;
			this.Label9.Text = "%";
			this.txtTotal.BackColor = global::System.Drawing.Color.White;
			this.txtTotal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8f, global::System.Drawing.FontStyle.Bold);
			this.txtTotal.Location = new global::System.Drawing.Point(488, 8);
			this.txtTotal.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtTotal.Name = "txtTotal";
			this.txtTotal.ReadOnly = true;
			this.txtTotal.Size = new global::System.Drawing.Size(80, 13);
			this.txtTotal.TabIndex = 43;
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.175f, global::System.Drawing.FontStyle.Bold);
			this.Label7.ForeColor = global::System.Drawing.Color.Black;
			this.Label7.Location = new global::System.Drawing.Point(7, 7);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(87, 13);
			this.Label7.TabIndex = 40;
			this.Label7.Text = "Desc. Cuenta:";
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.175f, global::System.Drawing.FontStyle.Bold);
			this.Label2.ForeColor = global::System.Drawing.Color.Black;
			this.Label2.Location = new global::System.Drawing.Point(448, 7);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(38, 13);
			this.Label2.TabIndex = 44;
			this.Label2.Text = "Total:";
			this.txtSubtotal.BackColor = global::System.Drawing.Color.White;
			this.txtSubtotal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSubtotal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8f, global::System.Drawing.FontStyle.Bold);
			this.txtSubtotal.Location = new global::System.Drawing.Point(359, 8);
			this.txtSubtotal.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtSubtotal.Name = "txtSubtotal";
			this.txtSubtotal.ReadOnly = true;
			this.txtSubtotal.Size = new global::System.Drawing.Size(80, 13);
			this.txtSubtotal.TabIndex = 41;
			this.txtDescuento.BackColor = global::System.Drawing.SystemColors.Info;
			this.txtDescuento.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8f, global::System.Drawing.FontStyle.Bold);
			this.txtDescuento.Location = new global::System.Drawing.Point(112, 8);
			this.txtDescuento.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtDescuento.Name = "txtDescuento";
			this.txtDescuento.Size = new global::System.Drawing.Size(45, 13);
			this.txtDescuento.TabIndex = 39;
			this.txtPropina.BackColor = global::System.Drawing.Color.White;
			this.txtPropina.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPropina.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8f, global::System.Drawing.FontStyle.Bold);
			this.txtPropina.Location = new global::System.Drawing.Point(243, 8);
			this.txtPropina.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtPropina.Name = "txtPropina";
			this.txtPropina.ReadOnly = true;
			this.txtPropina.Size = new global::System.Drawing.Size(52, 13);
			this.txtPropina.TabIndex = 46;
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.175f, global::System.Drawing.FontStyle.Bold);
			this.Label6.ForeColor = global::System.Drawing.Color.Black;
			this.Label6.Location = new global::System.Drawing.Point(301, 7);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(58, 13);
			this.Label6.TabIndex = 42;
			this.Label6.Text = "Subtotal:";
			this.lblPropina.AutoSize = true;
			this.lblPropina.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.175f, global::System.Drawing.FontStyle.Bold);
			this.lblPropina.Location = new global::System.Drawing.Point(188, 7);
			this.lblPropina.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblPropina.Name = "lblPropina";
			this.lblPropina.Size = new global::System.Drawing.Size(54, 13);
			this.lblPropina.TabIndex = 45;
			this.lblPropina.Text = "Propina:";
			this.Panel_MovtosTicket.BackColor = global::System.Drawing.Color.PaleGoldenrod;
			this.Panel_MovtosTicket.Controls.Add(this.Button1);
			this.Panel_MovtosTicket.Controls.Add(this.Button2);
			this.Panel_MovtosTicket.Controls.Add(this.btnAddMovto);
			this.Panel_MovtosTicket.Controls.Add(this.GroupBox2);
			this.Panel_MovtosTicket.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel_MovtosTicket.Location = new global::System.Drawing.Point(0, 0);
			this.Panel_MovtosTicket.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel_MovtosTicket.Name = "Panel_MovtosTicket";
			this.Panel_MovtosTicket.Size = new global::System.Drawing.Size(640, 57);
			this.Panel_MovtosTicket.TabIndex = 0;
			this.Button1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Button1.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button1.Image");
			this.Button1.Location = new global::System.Drawing.Point(482, 0);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(2);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(116, 57);
			this.Button1.TabIndex = 0;
			this.Button1.Text = "Deshacer";
			this.Button1.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.Button1.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.Button1.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Button2.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Button2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button2.Image");
			this.Button2.Location = new global::System.Drawing.Point(366, 0);
			this.Button2.Margin = new global::System.Windows.Forms.Padding(2);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(116, 57);
			this.Button2.TabIndex = 1;
			this.Button2.Text = "Aplicar";
			this.Button2.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.Button2.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.Button2.UseVisualStyleBackColor = false;
			this.btnAddMovto.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.btnAddMovto.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.btnAddMovto.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnAddMovto.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnAddMovto.Image");
			this.btnAddMovto.Location = new global::System.Drawing.Point(250, 0);
			this.btnAddMovto.Margin = new global::System.Windows.Forms.Padding(2);
			this.btnAddMovto.Name = "btnAddMovto";
			this.btnAddMovto.Size = new global::System.Drawing.Size(116, 57);
			this.btnAddMovto.TabIndex = 2;
			this.btnAddMovto.Text = "Añadir Movto.";
			this.btnAddMovto.TextAlign = global::System.Drawing.ContentAlignment.BottomCenter;
			this.btnAddMovto.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.btnAddMovto.UseVisualStyleBackColor = false;
			this.GroupBox2.Controls.Add(this.Button4);
			this.GroupBox2.Controls.Add(this.Label10);
			this.GroupBox2.Controls.Add(this.txtBuscarFolio);
			this.GroupBox2.Controls.Add(this.txtSerie);
			this.GroupBox2.Controls.Add(this.lblSerie);
			this.GroupBox2.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.GroupBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox2.Location = new global::System.Drawing.Point(0, 0);
			this.GroupBox2.Margin = new global::System.Windows.Forms.Padding(2);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Padding = new global::System.Windows.Forms.Padding(2);
			this.GroupBox2.Size = new global::System.Drawing.Size(250, 57);
			this.GroupBox2.TabIndex = 162;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Buscar ticket";
			this.Button4.BackColor = global::System.Drawing.Color.Red;
			this.Button4.ForeColor = global::System.Drawing.Color.White;
			this.Button4.Location = new global::System.Drawing.Point(137, 15);
			this.Button4.Margin = new global::System.Windows.Forms.Padding(2);
			this.Button4.Name = "Button4";
			this.Button4.Size = new global::System.Drawing.Size(100, 35);
			this.Button4.TabIndex = 156;
			this.Button4.Text = "Buscar Ticket";
			this.Button4.UseVisualStyleBackColor = false;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.Location = new global::System.Drawing.Point(53, 14);
			this.Label10.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(32, 13);
			this.Label10.TabIndex = 155;
			this.Label10.Text = "Folio:";
			this.txtBuscarFolio.BackColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.txtBuscarFolio.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtBuscarFolio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBuscarFolio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtBuscarFolio.Location = new global::System.Drawing.Point(53, 28);
			this.txtBuscarFolio.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtBuscarFolio.Name = "txtBuscarFolio";
			this.txtBuscarFolio.Size = new global::System.Drawing.Size(76, 21);
			this.txtBuscarFolio.TabIndex = 152;
			this.txtBuscarFolio.Text = "000000000";
			this.txtBuscarFolio.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.txtSerie.BackColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.txtSerie.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtSerie.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtSerie.Location = new global::System.Drawing.Point(10, 28);
			this.txtSerie.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtSerie.Name = "txtSerie";
			this.txtSerie.Size = new global::System.Drawing.Size(42, 21);
			this.txtSerie.TabIndex = 149;
			this.lblSerie.AutoSize = true;
			this.lblSerie.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblSerie.Location = new global::System.Drawing.Point(10, 14);
			this.lblSerie.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblSerie.Name = "lblSerie";
			this.lblSerie.Size = new global::System.Drawing.Size(34, 13);
			this.lblSerie.TabIndex = 150;
			this.lblSerie.Text = "Serie:";
			this.PanelBuscarProducto.Anchor = global::System.Windows.Forms.AnchorStyles.Top;
			this.PanelBuscarProducto.AutoSize = true;
			this.PanelBuscarProducto.BackColor = global::System.Drawing.SystemColors.Control;
			this.PanelBuscarProducto.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.PanelBuscarProducto.Controls.Add(this.Panel17);
			this.PanelBuscarProducto.Controls.Add(this.Panel8);
			this.PanelBuscarProducto.Location = new global::System.Drawing.Point(262, 267);
			this.PanelBuscarProducto.Margin = new global::System.Windows.Forms.Padding(2);
			this.PanelBuscarProducto.Name = "PanelBuscarProducto";
			this.PanelBuscarProducto.Size = new global::System.Drawing.Size(592, 358);
			this.PanelBuscarProducto.TabIndex = 147;
			this.Panel17.Controls.Add(this.dgwProductos);
			this.Panel17.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel17.Location = new global::System.Drawing.Point(0, 28);
			this.Panel17.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel17.Name = "Panel17";
			this.Panel17.Size = new global::System.Drawing.Size(590, 328);
			this.Panel17.TabIndex = 3;
			this.dgwProductos.AllowUserToAddRows = false;
			this.dgwProductos.AllowUserToDeleteRows = false;
			this.dgwProductos.AllowUserToResizeColumns = false;
			this.dgwProductos.AllowUserToResizeRows = false;
			this.dgwProductos.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgwProductos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgwProductos.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgwProductos.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgwProductos.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgwProductos.Location = new global::System.Drawing.Point(0, 0);
			this.dgwProductos.Margin = new global::System.Windows.Forms.Padding(2);
			this.dgwProductos.MultiSelect = false;
			this.dgwProductos.Name = "dgwProductos";
			this.dgwProductos.ReadOnly = true;
			this.dgwProductos.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dgwProductos.RowHeadersVisible = false;
			this.dgwProductos.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgwProductos.RowTemplate.Height = 24;
			this.dgwProductos.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dgwProductos.Size = new global::System.Drawing.Size(590, 328);
			this.dgwProductos.TabIndex = 26;
			this.Panel8.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel8.Controls.Add(this.Label29);
			this.Panel8.Controls.Add(this.txtBuscarProducto);
			this.Panel8.Controls.Add(this.PictureBox4);
			this.Panel8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel8.Location = new global::System.Drawing.Point(0, 0);
			this.Panel8.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel8.Name = "Panel8";
			this.Panel8.Size = new global::System.Drawing.Size(590, 28);
			this.Panel8.TabIndex = 0;
			this.Label29.Anchor = global::System.Windows.Forms.AnchorStyles.Left;
			this.Label29.AutoSize = true;
			this.Label29.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label29.Location = new global::System.Drawing.Point(7, 6);
			this.Label29.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label29.Name = "Label29";
			this.Label29.Size = new global::System.Drawing.Size(121, 13);
			this.Label29.TabIndex = 41;
			this.Label29.Text = "Buscar Producto.....";
			this.txtBuscarProducto.Anchor = global::System.Windows.Forms.AnchorStyles.Left;
			this.txtBuscarProducto.BackColor = global::System.Drawing.Color.White;
			this.txtBuscarProducto.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtBuscarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBuscarProducto.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtBuscarProducto.Location = new global::System.Drawing.Point(131, 5);
			this.txtBuscarProducto.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtBuscarProducto.Name = "txtBuscarProducto";
			this.txtBuscarProducto.Size = new global::System.Drawing.Size(164, 19);
			this.txtBuscarProducto.TabIndex = 8;
			this.PictureBox4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox4.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			this.PictureBox4.Location = new global::System.Drawing.Point(562, 0);
			this.PictureBox4.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBox4.Name = "PictureBox4";
			this.PictureBox4.Size = new global::System.Drawing.Size(28, 28);
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox4.TabIndex = 6;
			this.PictureBox4.TabStop = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(1105, 674);
			base.Controls.Add(this.PanelBuscarProducto);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Panel14);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Margin = new global::System.Windows.Forms.Padding(2);
			base.Name = "FormModificarTicket";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "FormModificarTicket";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.groupPeriodo.ResumeLayout(false);
			this.groupPeriodo.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.BtnHorario).EndInit();
			this.groupParametros.ResumeLayout(false);
			this.groupParametros.PerformLayout();
			this.Panel14.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DgvTicketsPeriodo).EndInit();
			this.Panel2.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).EndInit();
			this.Panel5.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DgvFormasPago).EndInit();
			this.Panel9.ResumeLayout(false);
			this.Panel9.PerformLayout();
			this.Panel6.ResumeLayout(false);
			this.Panel6.PerformLayout();
			this.Panel_MovtosTicket.ResumeLayout(false);
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.PanelBuscarProducto.ResumeLayout(false);
			this.Panel17.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.dgwProductos).EndInit();
			this.Panel8.ResumeLayout(false);
			this.Panel8.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000034 RID: 52
		private global::System.ComponentModel.IContainer components;
	}
}
