namespace ModuloAdicional
{
	// Token: 0x02000009 RID: 9
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FormRespaldoSQL : global::System.Windows.Forms.Form
	{
		// Token: 0x06000132 RID: 306 RVA: 0x00011114 File Offset: 0x0000F314
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000133 RID: 307 RVA: 0x00011164 File Offset: 0x0000F364
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.FormRespaldoSQL));
			this.SaveFileDialog1 = new global::System.Windows.Forms.SaveFileDialog();
			this.OpenFileDialog1 = new global::System.Windows.Forms.OpenFileDialog();
			this.btnBackup = new global::System.Windows.Forms.Button();
			this.btnConectar = new global::System.Windows.Forms.Button();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.cboBaseDatos = new global::System.Windows.Forms.ComboBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.CboEstaciones = new global::System.Windows.Forms.ComboBox();
			this.btnBuscar = new global::System.Windows.Forms.Button();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.PanelInformacion = new global::System.Windows.Forms.Panel();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.CheckBoxEstacion = new global::System.Windows.Forms.CheckBox();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.btnRecuperar = new global::System.Windows.Forms.Button();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.lblBuscarruta = new global::System.Windows.Forms.Label();
			this.lblnombredbo = new global::System.Windows.Forms.Label();
			this.txtRutadboRestaurat = new global::System.Windows.Forms.TextBox();
			this.txtDboRestaurar = new global::System.Windows.Forms.TextBox();
			this.SaveFileDialog2 = new global::System.Windows.Forms.SaveFileDialog();
			this.OpenFileDialog2 = new global::System.Windows.Forms.OpenFileDialog();
			this.btnBuscarRuta = new global::System.Windows.Forms.PictureBox();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.PanelInformacion.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			this.GroupBox1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnBuscarRuta).BeginInit();
			base.SuspendLayout();
			this.OpenFileDialog1.FileName = "OpenFileDialog1";
			this.btnBackup.BackColor = global::System.Drawing.Color.FromArgb(51, 103, 204);
			this.btnBackup.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnBackup.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnBackup.ForeColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.btnBackup.Location = new global::System.Drawing.Point(198, 641);
			this.btnBackup.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnBackup.Name = "btnBackup";
			this.btnBackup.Size = new global::System.Drawing.Size(434, 88);
			this.btnBackup.TabIndex = 27;
			this.btnBackup.Text = "RESPALDAR";
			this.btnBackup.UseVisualStyleBackColor = false;
			this.btnConectar.BackColor = global::System.Drawing.SystemColors.Info;
			this.btnConectar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnConectar.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnConectar.Location = new global::System.Drawing.Point(645, 308);
			this.btnConectar.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnConectar.Name = "btnConectar";
			this.btnConectar.Size = new global::System.Drawing.Size(148, 47);
			this.btnConectar.TabIndex = 24;
			this.btnConectar.Text = "Conectar";
			this.btnConectar.UseVisualStyleBackColor = false;
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.Location = new global::System.Drawing.Point(14, 308);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(173, 29);
			this.Label5.TabIndex = 23;
			this.Label5.Text = "Base de datos:\r\n";
			this.cboBaseDatos.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cboBaseDatos.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboBaseDatos.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cboBaseDatos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cboBaseDatos.FormattingEnabled = true;
			this.cboBaseDatos.Location = new global::System.Drawing.Point(197, 308);
			this.cboBaseDatos.Margin = new global::System.Windows.Forms.Padding(6);
			this.cboBaseDatos.Name = "cboBaseDatos";
			this.cboBaseDatos.Size = new global::System.Drawing.Size(434, 37);
			this.cboBaseDatos.TabIndex = 22;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.Location = new global::System.Drawing.Point(6, 9);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(511, 74);
			this.Label2.TabIndex = 3;
			this.Label2.Text = "Respaldar y recuperar \r\nBase de Datos SQL Server .BAK\r\n";
			this.Panel1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Controls.Add(this.Label2);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(6);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(822, 106);
			this.Panel1.TabIndex = 21;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(774, 3);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(45, 45);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 127;
			this.PictureBox1.TabStop = false;
			this.PictureBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox3.BackColor = global::System.Drawing.SystemColors.Control;
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(774, 115);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(45, 45);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 128;
			this.PictureBox3.TabStop = false;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(294, 466);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(250, 166);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 28;
			this.PictureBox2.TabStop = false;
			this.Label1.AutoSize = true;
			this.Label1.ForeColor = global::System.Drawing.Color.DimGray;
			this.Label1.Location = new global::System.Drawing.Point(2, 128);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(565, 50);
			this.Label1.TabIndex = 29;
			this.Label1.Text = "* Los archivos se guardan en C:\\RespaldoSoftRestaurant\\\r\n\r\n";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.Location = new global::System.Drawing.Point(65, 256);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(122, 29);
			this.Label3.TabIndex = 30;
			this.Label3.Text = "Servidor : ";
			this.CboEstaciones.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CboEstaciones.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.CboEstaciones.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.CboEstaciones.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CboEstaciones.FormattingEnabled = true;
			this.CboEstaciones.Location = new global::System.Drawing.Point(197, 253);
			this.CboEstaciones.Margin = new global::System.Windows.Forms.Padding(6);
			this.CboEstaciones.Name = "CboEstaciones";
			this.CboEstaciones.Size = new global::System.Drawing.Size(434, 37);
			this.CboEstaciones.TabIndex = 31;
			this.btnBuscar.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.btnBuscar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnBuscar.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnBuscar.Location = new global::System.Drawing.Point(645, 248);
			this.btnBuscar.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.Size = new global::System.Drawing.Size(148, 47);
			this.btnBuscar.TabIndex = 32;
			this.btnBuscar.Text = "Buscar";
			this.btnBuscar.UseVisualStyleBackColor = false;
			this.PanelInformacion.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.PanelInformacion.Controls.Add(this.Label8);
			this.PanelInformacion.Controls.Add(this.PictureBox4);
			this.PanelInformacion.Controls.Add(this.Label7);
			this.PanelInformacion.Controls.Add(this.Label6);
			this.PanelInformacion.Controls.Add(this.Label4);
			this.PanelInformacion.Location = new global::System.Drawing.Point(79, 372);
			this.PanelInformacion.Name = "PanelInformacion";
			this.PanelInformacion.Size = new global::System.Drawing.Size(676, 318);
			this.PanelInformacion.TabIndex = 33;
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(8, 304);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(590, 75);
			this.Label8.TabIndex = 129;
			this.Label8.Text = "*Cuadro de selección Estación\r\nSi estas generando el respaldo desde una estación activalo.\r\ncaso contrario dejalo desactivado.\r\n";
			this.PictureBox4.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			this.PictureBox4.Location = new global::System.Drawing.Point(625, 3);
			this.PictureBox4.Name = "PictureBox4";
			this.PictureBox4.Size = new global::System.Drawing.Size(45, 45);
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox4.TabIndex = 128;
			this.PictureBox4.TabStop = false;
			this.Label7.AutoSize = true;
			this.Label7.Location = new global::System.Drawing.Point(8, 166);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(588, 150);
			this.Label7.TabIndex = 2;
			this.Label7.Text = componentResourceManager.GetString("Label7.Text");
			this.Label6.AutoSize = true;
			this.Label6.Location = new global::System.Drawing.Point(8, 94);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(403, 50);
			this.Label6.TabIndex = 1;
			this.Label6.Text = "*Base de Datos\r\nSelecciona la base de datos a respaldar.\r\n";
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(8, 14);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(592, 50);
			this.Label4.TabIndex = 0;
			this.Label4.Text = "*Servidor  \r\nNombre del equipo donde esta instalada la instancia de SQL";
			this.CheckBoxEstacion.AutoSize = true;
			this.CheckBoxEstacion.Location = new global::System.Drawing.Point(6, 30);
			this.CheckBoxEstacion.Name = "CheckBoxEstacion";
			this.CheckBoxEstacion.Size = new global::System.Drawing.Size(127, 29);
			this.CheckBoxEstacion.TabIndex = 34;
			this.CheckBoxEstacion.Text = "Estación";
			this.CheckBoxEstacion.UseVisualStyleBackColor = true;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Location = new global::System.Drawing.Point(139, 30);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(142, 29);
			this.CheckBox1.TabIndex = 35;
			this.CheckBox1.Text = "Respaldar";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Location = new global::System.Drawing.Point(287, 30);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(144, 29);
			this.CheckBox2.TabIndex = 36;
			this.CheckBox2.Text = "Recuperar";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.btnRecuperar.BackColor = global::System.Drawing.Color.Green;
			this.btnRecuperar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnRecuperar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnRecuperar.ForeColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.btnRecuperar.Location = new global::System.Drawing.Point(198, 636);
			this.btnRecuperar.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnRecuperar.Name = "btnRecuperar";
			this.btnRecuperar.Size = new global::System.Drawing.Size(434, 88);
			this.btnRecuperar.TabIndex = 37;
			this.btnRecuperar.Text = "RECUPERAR";
			this.btnRecuperar.UseVisualStyleBackColor = false;
			this.GroupBox1.Controls.Add(this.CheckBoxEstacion);
			this.GroupBox1.Controls.Add(this.CheckBox1);
			this.GroupBox1.Controls.Add(this.CheckBox2);
			this.GroupBox1.Location = new global::System.Drawing.Point(7, 160);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(512, 80);
			this.GroupBox1.TabIndex = 38;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Parametros";
			this.lblBuscarruta.AutoSize = true;
			this.lblBuscarruta.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblBuscarruta.Location = new global::System.Drawing.Point(82, 372);
			this.lblBuscarruta.Name = "lblBuscarruta";
			this.lblBuscarruta.Size = new global::System.Drawing.Size(105, 29);
			this.lblBuscarruta.TabIndex = 39;
			this.lblBuscarruta.Text = "Buscar : ";
			this.lblnombredbo.AutoSize = true;
			this.lblnombredbo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblnombredbo.Location = new global::System.Drawing.Point(8, 419);
			this.lblnombredbo.Name = "lblnombredbo";
			this.lblnombredbo.Size = new global::System.Drawing.Size(167, 58);
			this.lblnombredbo.TabIndex = 40;
			this.lblnombredbo.Text = "Base de datos\r\na recuperar :";
			this.txtRutadboRestaurat.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtRutadboRestaurat.Location = new global::System.Drawing.Point(197, 369);
			this.txtRutadboRestaurat.Name = "txtRutadboRestaurat";
			this.txtRutadboRestaurat.Size = new global::System.Drawing.Size(435, 35);
			this.txtRutadboRestaurat.TabIndex = 42;
			this.txtDboRestaurar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtDboRestaurar.Location = new global::System.Drawing.Point(197, 416);
			this.txtDboRestaurar.Name = "txtDboRestaurar";
			this.txtDboRestaurar.ReadOnly = true;
			this.txtDboRestaurar.Size = new global::System.Drawing.Size(435, 35);
			this.txtDboRestaurar.TabIndex = 44;
			this.OpenFileDialog2.FileName = "OpenFileDialog2";
			this.btnBuscarRuta.BackColor = global::System.Drawing.Color.Black;
			this.btnBuscarRuta.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnBuscarRuta.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnBuscarRuta.Image");
			this.btnBuscarRuta.Location = new global::System.Drawing.Point(648, 370);
			this.btnBuscarRuta.Name = "btnBuscarRuta";
			this.btnBuscarRuta.Size = new global::System.Drawing.Size(66, 33);
			this.btnBuscarRuta.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.btnBuscarRuta.TabIndex = 129;
			this.btnBuscarRuta.TabStop = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(822, 755);
			base.Controls.Add(this.PanelInformacion);
			base.Controls.Add(this.btnBuscarRuta);
			base.Controls.Add(this.PictureBox3);
			base.Controls.Add(this.txtDboRestaurar);
			base.Controls.Add(this.txtRutadboRestaurat);
			base.Controls.Add(this.lblnombredbo);
			base.Controls.Add(this.lblBuscarruta);
			base.Controls.Add(this.GroupBox1);
			base.Controls.Add(this.btnRecuperar);
			base.Controls.Add(this.btnBuscar);
			base.Controls.Add(this.CboEstaciones);
			base.Controls.Add(this.Label3);
			base.Controls.Add(this.Label1);
			base.Controls.Add(this.PictureBox2);
			base.Controls.Add(this.btnBackup);
			base.Controls.Add(this.btnConectar);
			base.Controls.Add(this.Label5);
			base.Controls.Add(this.cboBaseDatos);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Margin = new global::System.Windows.Forms.Padding(6);
			base.Name = "FormRespaldoSQL";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Form1";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.PanelInformacion.ResumeLayout(false);
			this.PanelInformacion.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnBuscarRuta).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000083 RID: 131
		private global::System.ComponentModel.IContainer components;
	}
}
