namespace ModuloAdicional
{
	// Token: 0x0200000D RID: 13
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FrmBitacora : global::System.Windows.Forms.Form
	{
		// Token: 0x060001DC RID: 476 RVA: 0x00015CB4 File Offset: 0x00013EB4
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060001DD RID: 477 RVA: 0x00015D04 File Offset: 0x00013F04
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.FrmBitacora));
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.dgvNotas = new global::System.Windows.Forms.DataGridView();
			this.Panelvercortes = new global::System.Windows.Forms.Panel();
			this.lblfacturapubnew = new global::System.Windows.Forms.Label();
			this.lblventasinfacturarnew = new global::System.Windows.Forms.Label();
			this.lblventafacturanew = new global::System.Windows.Forms.Label();
			this.lblfacturapub = new global::System.Windows.Forms.Label();
			this.lblventasinfacturarcorte = new global::System.Windows.Forms.Label();
			this.lblventaFacturada = new global::System.Windows.Forms.Label();
			this.Label60 = new global::System.Windows.Forms.Label();
			this.Label61 = new global::System.Windows.Forms.Label();
			this.Label62 = new global::System.Windows.Forms.Label();
			this.Label59 = new global::System.Windows.Forms.Label();
			this.Label58 = new global::System.Windows.Forms.Label();
			this.Label57 = new global::System.Windows.Forms.Label();
			this.Label53 = new global::System.Windows.Forms.Label();
			this.Label56 = new global::System.Windows.Forms.Label();
			this.Label40 = new global::System.Windows.Forms.Label();
			this.Label51 = new global::System.Windows.Forms.Label();
			this.Label52 = new global::System.Windows.Forms.Label();
			this.lblEfectivonuevocorte = new global::System.Windows.Forms.Label();
			this.lblsaldofinarlcortenuevo = new global::System.Windows.Forms.Label();
			this.lblpropinascortenuevo = new global::System.Windows.Forms.Label();
			this.lblcortenuevoretiros = new global::System.Windows.Forms.Label();
			this.lblcortenuevodepositos = new global::System.Windows.Forms.Label();
			this.lblcortenuevotros = new global::System.Windows.Forms.Label();
			this.lblcortenuevovales = new global::System.Windows.Forms.Label();
			this.lblcortetarjetanuevo = new global::System.Windows.Forms.Label();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.lblcorteefectivonuevo = new global::System.Windows.Forms.Label();
			this.lblfondoinicialnuevo = new global::System.Windows.Forms.Label();
			this.lblcortefondoinicialanterior = new global::System.Windows.Forms.Label();
			this.Label41 = new global::System.Windows.Forms.Label();
			this.Label42 = new global::System.Windows.Forms.Label();
			this.Label43 = new global::System.Windows.Forms.Label();
			this.Label44 = new global::System.Windows.Forms.Label();
			this.Label45 = new global::System.Windows.Forms.Label();
			this.Label46 = new global::System.Windows.Forms.Label();
			this.Label47 = new global::System.Windows.Forms.Label();
			this.Label48 = new global::System.Windows.Forms.Label();
			this.Label49 = new global::System.Windows.Forms.Label();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.lblcorteanteriorefectivofinal = new global::System.Windows.Forms.Label();
			this.lblcorteanteriorsaldo = new global::System.Windows.Forms.Label();
			this.lblcorteanteriorpropinas = new global::System.Windows.Forms.Label();
			this.lblcorteanteriorretirosefectivo = new global::System.Windows.Forms.Label();
			this.lblcorteanteriordepositosenefectivo = new global::System.Windows.Forms.Label();
			this.lblcorteanteriorotros = new global::System.Windows.Forms.Label();
			this.lblcorteanteriorvales = new global::System.Windows.Forms.Label();
			this.lblcorteefectivoanterior = new global::System.Windows.Forms.Label();
			this.lblcortetarjetaanterior = new global::System.Windows.Forms.Label();
			this.Label38 = new global::System.Windows.Forms.Label();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).BeginInit();
			this.Panelvercortes.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			base.SuspendLayout();
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(2326, 64);
			this.Panel1.TabIndex = 0;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(2263, 4);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(60, 60);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 144;
			this.PictureBox1.TabStop = false;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(13, 19);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(263, 29);
			this.Label1.TabIndex = 127;
			this.Label1.Text = "Bitacora de Procesos";
			this.dgvNotas.AllowUserToAddRows = false;
			this.dgvNotas.AllowUserToDeleteRows = false;
			this.dgvNotas.AllowUserToResizeColumns = false;
			this.dgvNotas.AllowUserToResizeRows = false;
			this.dgvNotas.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgvNotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvNotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvNotas.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgvNotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvNotas.Location = new global::System.Drawing.Point(0, 64);
			this.dgvNotas.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgvNotas.MultiSelect = false;
			this.dgvNotas.Name = "dgvNotas";
			this.dgvNotas.ReadOnly = true;
			this.dgvNotas.RowHeadersVisible = false;
			this.dgvNotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvNotas.RowTemplate.Height = 24;
			this.dgvNotas.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dgvNotas.Size = new global::System.Drawing.Size(2326, 1255);
			this.dgvNotas.TabIndex = 25;
			this.Panelvercortes.Anchor = global::System.Windows.Forms.AnchorStyles.Top;
			this.Panelvercortes.AutoSize = true;
			this.Panelvercortes.BackColor = global::System.Drawing.SystemColors.Info;
			this.Panelvercortes.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panelvercortes.Controls.Add(this.lblfacturapubnew);
			this.Panelvercortes.Controls.Add(this.lblventasinfacturarnew);
			this.Panelvercortes.Controls.Add(this.lblventafacturanew);
			this.Panelvercortes.Controls.Add(this.lblfacturapub);
			this.Panelvercortes.Controls.Add(this.lblventasinfacturarcorte);
			this.Panelvercortes.Controls.Add(this.lblventaFacturada);
			this.Panelvercortes.Controls.Add(this.Label60);
			this.Panelvercortes.Controls.Add(this.Label61);
			this.Panelvercortes.Controls.Add(this.Label62);
			this.Panelvercortes.Controls.Add(this.Label59);
			this.Panelvercortes.Controls.Add(this.Label58);
			this.Panelvercortes.Controls.Add(this.Label57);
			this.Panelvercortes.Controls.Add(this.Label53);
			this.Panelvercortes.Controls.Add(this.Label56);
			this.Panelvercortes.Controls.Add(this.Label40);
			this.Panelvercortes.Controls.Add(this.Label51);
			this.Panelvercortes.Controls.Add(this.Label52);
			this.Panelvercortes.Controls.Add(this.lblEfectivonuevocorte);
			this.Panelvercortes.Controls.Add(this.lblsaldofinarlcortenuevo);
			this.Panelvercortes.Controls.Add(this.lblpropinascortenuevo);
			this.Panelvercortes.Controls.Add(this.lblcortenuevoretiros);
			this.Panelvercortes.Controls.Add(this.lblcortenuevodepositos);
			this.Panelvercortes.Controls.Add(this.lblcortenuevotros);
			this.Panelvercortes.Controls.Add(this.lblcortenuevovales);
			this.Panelvercortes.Controls.Add(this.lblcortetarjetanuevo);
			this.Panelvercortes.Controls.Add(this.PictureBox3);
			this.Panelvercortes.Controls.Add(this.lblcorteefectivonuevo);
			this.Panelvercortes.Controls.Add(this.lblfondoinicialnuevo);
			this.Panelvercortes.Controls.Add(this.lblcortefondoinicialanterior);
			this.Panelvercortes.Controls.Add(this.Label41);
			this.Panelvercortes.Controls.Add(this.Label42);
			this.Panelvercortes.Controls.Add(this.Label43);
			this.Panelvercortes.Controls.Add(this.Label44);
			this.Panelvercortes.Controls.Add(this.Label45);
			this.Panelvercortes.Controls.Add(this.Label46);
			this.Panelvercortes.Controls.Add(this.Label47);
			this.Panelvercortes.Controls.Add(this.Label48);
			this.Panelvercortes.Controls.Add(this.Label49);
			this.Panelvercortes.Controls.Add(this.Label39);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriorefectivofinal);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriorsaldo);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriorpropinas);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriorretirosefectivo);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriordepositosenefectivo);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriorotros);
			this.Panelvercortes.Controls.Add(this.lblcorteanteriorvales);
			this.Panelvercortes.Controls.Add(this.lblcorteefectivoanterior);
			this.Panelvercortes.Controls.Add(this.lblcortetarjetaanterior);
			this.Panelvercortes.Controls.Add(this.Label38);
			this.Panelvercortes.Controls.Add(this.Label37);
			this.Panelvercortes.Controls.Add(this.Label36);
			this.Panelvercortes.Controls.Add(this.Label35);
			this.Panelvercortes.Controls.Add(this.Label34);
			this.Panelvercortes.Controls.Add(this.Label33);
			this.Panelvercortes.Controls.Add(this.Label32);
			this.Panelvercortes.Controls.Add(this.Label31);
			this.Panelvercortes.Controls.Add(this.Label30);
			this.Panelvercortes.Controls.Add(this.Label29);
			this.Panelvercortes.Controls.Add(this.Label28);
			this.Panelvercortes.Location = new global::System.Drawing.Point(274, 326);
			this.Panelvercortes.Name = "Panelvercortes";
			this.Panelvercortes.Size = new global::System.Drawing.Size(1355, 682);
			this.Panelvercortes.TabIndex = 26;
			this.lblfacturapubnew.AutoSize = true;
			this.lblfacturapubnew.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblfacturapubnew.ForeColor = global::System.Drawing.Color.Teal;
			this.lblfacturapubnew.Location = new global::System.Drawing.Point(973, 628);
			this.lblfacturapubnew.Name = "lblfacturapubnew";
			this.lblfacturapubnew.Size = new global::System.Drawing.Size(191, 25);
			this.lblfacturapubnew.TabIndex = 153;
			this.lblfacturapubnew.Text = "lblfacturapubnew";
			this.lblventasinfacturarnew.AutoSize = true;
			this.lblventasinfacturarnew.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblventasinfacturarnew.ForeColor = global::System.Drawing.Color.Teal;
			this.lblventasinfacturarnew.Location = new global::System.Drawing.Point(973, 582);
			this.lblventasinfacturarnew.Name = "lblventasinfacturarnew";
			this.lblventasinfacturarnew.Size = new global::System.Drawing.Size(249, 25);
			this.lblventasinfacturarnew.TabIndex = 152;
			this.lblventasinfacturarnew.Text = "lblventasinfacturarnew";
			this.lblventafacturanew.AutoSize = true;
			this.lblventafacturanew.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblventafacturanew.ForeColor = global::System.Drawing.Color.Teal;
			this.lblventafacturanew.Location = new global::System.Drawing.Point(974, 536);
			this.lblventafacturanew.Name = "lblventafacturanew";
			this.lblventafacturanew.Size = new global::System.Drawing.Size(210, 25);
			this.lblventafacturanew.TabIndex = 151;
			this.lblventafacturanew.Text = "lblventafacturanew";
			this.lblfacturapub.AutoSize = true;
			this.lblfacturapub.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblfacturapub.ForeColor = global::System.Drawing.Color.Teal;
			this.lblfacturapub.Location = new global::System.Drawing.Point(302, 628);
			this.lblfacturapub.Name = "lblfacturapub";
			this.lblfacturapub.Size = new global::System.Drawing.Size(149, 25);
			this.lblfacturapub.TabIndex = 150;
			this.lblfacturapub.Text = "lblfacturapub";
			this.lblventasinfacturarcorte.AutoSize = true;
			this.lblventasinfacturarcorte.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblventasinfacturarcorte.ForeColor = global::System.Drawing.Color.Teal;
			this.lblventasinfacturarcorte.Location = new global::System.Drawing.Point(302, 582);
			this.lblventasinfacturarcorte.Name = "lblventasinfacturarcorte";
			this.lblventasinfacturarcorte.Size = new global::System.Drawing.Size(207, 25);
			this.lblventasinfacturarcorte.TabIndex = 149;
			this.lblventasinfacturarcorte.Text = "lblventasinfacturar";
			this.lblventaFacturada.AutoSize = true;
			this.lblventaFacturada.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblventaFacturada.ForeColor = global::System.Drawing.Color.Teal;
			this.lblventaFacturada.Location = new global::System.Drawing.Point(303, 536);
			this.lblventaFacturada.Name = "lblventaFacturada";
			this.lblventaFacturada.Size = new global::System.Drawing.Size(201, 25);
			this.lblventaFacturada.TabIndex = 148;
			this.lblventaFacturada.Text = "lblventaFacturada";
			this.Label60.AutoSize = true;
			this.Label60.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label60.ForeColor = global::System.Drawing.Color.Black;
			this.Label60.Location = new global::System.Drawing.Point(681, 628);
			this.Label60.Name = "Label60";
			this.Label60.Size = new global::System.Drawing.Size(269, 25);
			this.Label60.TabIndex = 147;
			this.Label60.Text = "Factura publico en gral :";
			this.Label61.AutoSize = true;
			this.Label61.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label61.ForeColor = global::System.Drawing.Color.Black;
			this.Label61.Location = new global::System.Drawing.Point(681, 582);
			this.Label61.Name = "Label61";
			this.Label61.Size = new global::System.Drawing.Size(213, 25);
			this.Label61.TabIndex = 146;
			this.Label61.Text = "Venta sin facturar :";
			this.Label62.AutoSize = true;
			this.Label62.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label62.ForeColor = global::System.Drawing.Color.Black;
			this.Label62.Location = new global::System.Drawing.Point(680, 536);
			this.Label62.Name = "Label62";
			this.Label62.Size = new global::System.Drawing.Size(193, 25);
			this.Label62.TabIndex = 145;
			this.Label62.Text = "Venta facturada :";
			this.Label59.AutoSize = true;
			this.Label59.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label59.ForeColor = global::System.Drawing.Color.Black;
			this.Label59.Location = new global::System.Drawing.Point(14, 628);
			this.Label59.Name = "Label59";
			this.Label59.Size = new global::System.Drawing.Size(269, 25);
			this.Label59.TabIndex = 144;
			this.Label59.Text = "Factura publico en gral :";
			this.Label58.AutoSize = true;
			this.Label58.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label58.ForeColor = global::System.Drawing.Color.Black;
			this.Label58.Location = new global::System.Drawing.Point(14, 582);
			this.Label58.Name = "Label58";
			this.Label58.Size = new global::System.Drawing.Size(213, 25);
			this.Label58.TabIndex = 143;
			this.Label58.Text = "Venta sin facturar :";
			this.Label57.AutoSize = true;
			this.Label57.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label57.ForeColor = global::System.Drawing.Color.Black;
			this.Label57.Location = new global::System.Drawing.Point(13, 536);
			this.Label57.Name = "Label57";
			this.Label57.Size = new global::System.Drawing.Size(193, 25);
			this.Label57.TabIndex = 142;
			this.Label57.Text = "Venta facturada :";
			this.Label53.AutoSize = true;
			this.Label53.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label53.Location = new global::System.Drawing.Point(14, 491);
			this.Label53.Name = "Label53";
			this.Label53.Size = new global::System.Drawing.Size(588, 25);
			this.Label53.TabIndex = 141;
			this.Label53.Text = "________________________________________________";
			this.Label56.AutoSize = true;
			this.Label56.Location = new global::System.Drawing.Point(680, 491);
			this.Label56.Name = "Label56";
			this.Label56.Size = new global::System.Drawing.Size(588, 25);
			this.Label56.TabIndex = 140;
			this.Label56.Text = "________________________________________________";
			this.Label40.AutoSize = true;
			this.Label40.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label40.ForeColor = global::System.Drawing.Color.Black;
			this.Label40.Location = new global::System.Drawing.Point(682, 441);
			this.Label40.Name = "Label40";
			this.Label40.Size = new global::System.Drawing.Size(187, 50);
			this.Label40.TabIndex = 139;
			this.Label40.Text = "Efectivo final:\r\n(Deposito a cta.)";
			this.Label51.AutoSize = true;
			this.Label51.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label51.Location = new global::System.Drawing.Point(14, 364);
			this.Label51.Name = "Label51";
			this.Label51.Size = new global::System.Drawing.Size(588, 25);
			this.Label51.TabIndex = 138;
			this.Label51.Text = "________________________________________________";
			this.Label52.AutoSize = true;
			this.Label52.Location = new global::System.Drawing.Point(680, 364);
			this.Label52.Name = "Label52";
			this.Label52.Size = new global::System.Drawing.Size(588, 25);
			this.Label52.TabIndex = 137;
			this.Label52.Text = "________________________________________________";
			this.lblEfectivonuevocorte.AutoSize = true;
			this.lblEfectivonuevocorte.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblEfectivonuevocorte.ForeColor = global::System.Drawing.Color.Green;
			this.lblEfectivonuevocorte.Location = new global::System.Drawing.Point(970, 441);
			this.lblEfectivonuevocorte.Name = "lblEfectivonuevocorte";
			this.lblEfectivonuevocorte.Size = new global::System.Drawing.Size(239, 25);
			this.lblEfectivonuevocorte.TabIndex = 135;
			this.lblEfectivonuevocorte.Text = "lblEfectivonuevocorte";
			this.lblsaldofinarlcortenuevo.AutoSize = true;
			this.lblsaldofinarlcortenuevo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblsaldofinarlcortenuevo.ForeColor = global::System.Drawing.Color.DarkBlue;
			this.lblsaldofinarlcortenuevo.Location = new global::System.Drawing.Point(970, 403);
			this.lblsaldofinarlcortenuevo.Name = "lblsaldofinarlcortenuevo";
			this.lblsaldofinarlcortenuevo.Size = new global::System.Drawing.Size(264, 25);
			this.lblsaldofinarlcortenuevo.TabIndex = 134;
			this.lblsaldofinarlcortenuevo.Text = "lblsaldofinarlcortenuevo";
			this.lblpropinascortenuevo.AutoSize = true;
			this.lblpropinascortenuevo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblpropinascortenuevo.ForeColor = global::System.Drawing.Color.Red;
			this.lblpropinascortenuevo.Location = new global::System.Drawing.Point(970, 335);
			this.lblpropinascortenuevo.Name = "lblpropinascortenuevo";
			this.lblpropinascortenuevo.Size = new global::System.Drawing.Size(245, 25);
			this.lblpropinascortenuevo.TabIndex = 133;
			this.lblpropinascortenuevo.Text = "lblpropinascortenuevo";
			this.lblcortenuevoretiros.AutoSize = true;
			this.lblcortenuevoretiros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortenuevoretiros.ForeColor = global::System.Drawing.Color.Red;
			this.lblcortenuevoretiros.Location = new global::System.Drawing.Point(970, 293);
			this.lblcortenuevoretiros.Name = "lblcortenuevoretiros";
			this.lblcortenuevoretiros.Size = new global::System.Drawing.Size(221, 25);
			this.lblcortenuevoretiros.TabIndex = 132;
			this.lblcortenuevoretiros.Text = "lblcortenuevoretiros";
			this.lblcortenuevodepositos.AutoSize = true;
			this.lblcortenuevodepositos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortenuevodepositos.ForeColor = global::System.Drawing.Color.Green;
			this.lblcortenuevodepositos.Location = new global::System.Drawing.Point(970, 253);
			this.lblcortenuevodepositos.Name = "lblcortenuevodepositos";
			this.lblcortenuevodepositos.Size = new global::System.Drawing.Size(256, 25);
			this.lblcortenuevodepositos.TabIndex = 131;
			this.lblcortenuevodepositos.Text = "lblcortenuevodepositos";
			this.lblcortenuevotros.AutoSize = true;
			this.lblcortenuevotros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortenuevotros.ForeColor = global::System.Drawing.Color.Green;
			this.lblcortenuevotros.Location = new global::System.Drawing.Point(970, 211);
			this.lblcortenuevotros.Name = "lblcortenuevotros";
			this.lblcortenuevotros.Size = new global::System.Drawing.Size(194, 25);
			this.lblcortenuevotros.TabIndex = 130;
			this.lblcortenuevotros.Text = "lblcortenuevotros";
			this.lblcortenuevovales.AutoSize = true;
			this.lblcortenuevovales.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortenuevovales.ForeColor = global::System.Drawing.Color.Green;
			this.lblcortenuevovales.Location = new global::System.Drawing.Point(970, 171);
			this.lblcortenuevovales.Name = "lblcortenuevovales";
			this.lblcortenuevovales.Size = new global::System.Drawing.Size(210, 25);
			this.lblcortenuevovales.TabIndex = 129;
			this.lblcortenuevovales.Text = "lblcortenuevovales";
			this.lblcortetarjetanuevo.AutoSize = true;
			this.lblcortetarjetanuevo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortetarjetanuevo.ForeColor = global::System.Drawing.Color.Green;
			this.lblcortetarjetanuevo.Location = new global::System.Drawing.Point(970, 133);
			this.lblcortetarjetanuevo.Name = "lblcortetarjetanuevo";
			this.lblcortetarjetanuevo.Size = new global::System.Drawing.Size(221, 25);
			this.lblcortetarjetanuevo.TabIndex = 128;
			this.lblcortetarjetanuevo.Text = "lblcortetarjetanuevo";
			this.PictureBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(1309, -1);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(45, 45);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 127;
			this.PictureBox3.TabStop = false;
			this.lblcorteefectivonuevo.AutoSize = true;
			this.lblcorteefectivonuevo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteefectivonuevo.ForeColor = global::System.Drawing.Color.Green;
			this.lblcorteefectivonuevo.Location = new global::System.Drawing.Point(970, 97);
			this.lblcorteefectivonuevo.Name = "lblcorteefectivonuevo";
			this.lblcorteefectivonuevo.Size = new global::System.Drawing.Size(237, 25);
			this.lblcorteefectivonuevo.TabIndex = 33;
			this.lblcorteefectivonuevo.Text = "lblcorteefectivonuevo";
			this.lblfondoinicialnuevo.AutoSize = true;
			this.lblfondoinicialnuevo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblfondoinicialnuevo.ForeColor = global::System.Drawing.Color.Green;
			this.lblfondoinicialnuevo.Location = new global::System.Drawing.Point(970, 63);
			this.lblfondoinicialnuevo.Name = "lblfondoinicialnuevo";
			this.lblfondoinicialnuevo.Size = new global::System.Drawing.Size(222, 25);
			this.lblfondoinicialnuevo.TabIndex = 32;
			this.lblfondoinicialnuevo.Text = "lblfondoinicialnuevo";
			this.lblcortefondoinicialanterior.AutoSize = true;
			this.lblcortefondoinicialanterior.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortefondoinicialanterior.ForeColor = global::System.Drawing.Color.Green;
			this.lblcortefondoinicialanterior.Location = new global::System.Drawing.Point(302, 63);
			this.lblcortefondoinicialanterior.Name = "lblcortefondoinicialanterior";
			this.lblcortefondoinicialanterior.Size = new global::System.Drawing.Size(292, 25);
			this.lblcortefondoinicialanterior.TabIndex = 31;
			this.lblcortefondoinicialanterior.Text = "lblcortefondoinicialanterior";
			this.Label41.AutoSize = true;
			this.Label41.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label41.ForeColor = global::System.Drawing.Color.Black;
			this.Label41.Location = new global::System.Drawing.Point(680, 403);
			this.Label41.Name = "Label41";
			this.Label41.Size = new global::System.Drawing.Size(138, 25);
			this.Label41.TabIndex = 29;
			this.Label41.Text = "Saldo final :";
			this.Label42.AutoSize = true;
			this.Label42.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label42.ForeColor = global::System.Drawing.Color.Black;
			this.Label42.Location = new global::System.Drawing.Point(680, 335);
			this.Label42.Name = "Label42";
			this.Label42.Size = new global::System.Drawing.Size(231, 25);
			this.Label42.TabIndex = 28;
			this.Label42.Text = "- Propinas pagadas :";
			this.Label43.AutoSize = true;
			this.Label43.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label43.ForeColor = global::System.Drawing.Color.Black;
			this.Label43.Location = new global::System.Drawing.Point(680, 293);
			this.Label43.Name = "Label43";
			this.Label43.Size = new global::System.Drawing.Size(239, 25);
			this.Label43.TabIndex = 27;
			this.Label43.Text = "- Retiros en efectivo :";
			this.Label44.AutoSize = true;
			this.Label44.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label44.ForeColor = global::System.Drawing.Color.Black;
			this.Label44.Location = new global::System.Drawing.Point(680, 253);
			this.Label44.Name = "Label44";
			this.Label44.Size = new global::System.Drawing.Size(274, 25);
			this.Label44.TabIndex = 26;
			this.Label44.Text = "+ Depositos en efectivo :";
			this.Label45.AutoSize = true;
			this.Label45.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label45.ForeColor = global::System.Drawing.Color.Black;
			this.Label45.Location = new global::System.Drawing.Point(680, 211);
			this.Label45.Name = "Label45";
			this.Label45.Size = new global::System.Drawing.Size(103, 25);
			this.Label45.TabIndex = 25;
			this.Label45.Text = "+ Otros :";
			this.Label46.AutoSize = true;
			this.Label46.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label46.ForeColor = global::System.Drawing.Color.Black;
			this.Label46.Location = new global::System.Drawing.Point(680, 171);
			this.Label46.Name = "Label46";
			this.Label46.Size = new global::System.Drawing.Size(105, 25);
			this.Label46.TabIndex = 24;
			this.Label46.Text = "+ Vales :";
			this.Label47.AutoSize = true;
			this.Label47.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label47.ForeColor = global::System.Drawing.Color.Black;
			this.Label47.Location = new global::System.Drawing.Point(680, 133);
			this.Label47.Name = "Label47";
			this.Label47.Size = new global::System.Drawing.Size(120, 25);
			this.Label47.TabIndex = 23;
			this.Label47.Text = "+ Tarjeta :";
			this.Label48.AutoSize = true;
			this.Label48.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label48.ForeColor = global::System.Drawing.Color.Black;
			this.Label48.Location = new global::System.Drawing.Point(680, 97);
			this.Label48.Name = "Label48";
			this.Label48.Size = new global::System.Drawing.Size(131, 25);
			this.Label48.TabIndex = 22;
			this.Label48.Text = "+ Efectivo :";
			this.Label49.AutoSize = true;
			this.Label49.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label49.ForeColor = global::System.Drawing.Color.Black;
			this.Label49.Location = new global::System.Drawing.Point(680, 63);
			this.Label49.Name = "Label49";
			this.Label49.Size = new global::System.Drawing.Size(181, 25);
			this.Label49.TabIndex = 21;
			this.Label49.Text = "+ Fondo inicial :";
			this.Label39.AutoSize = true;
			this.Label39.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label39.Location = new global::System.Drawing.Point(680, 11);
			this.Label39.Name = "Label39";
			this.Label39.Size = new global::System.Drawing.Size(594, 37);
			this.Label39.TabIndex = 20;
			this.Label39.Text = "CORTE RESULTADO (MODIFICADO)";
			this.lblcorteanteriorefectivofinal.AutoSize = true;
			this.lblcorteanteriorefectivofinal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriorefectivofinal.ForeColor = global::System.Drawing.Color.Green;
			this.lblcorteanteriorefectivofinal.Location = new global::System.Drawing.Point(303, 441);
			this.lblcorteanteriorefectivofinal.Name = "lblcorteanteriorefectivofinal";
			this.lblcorteanteriorefectivofinal.Size = new global::System.Drawing.Size(299, 25);
			this.lblcorteanteriorefectivofinal.TabIndex = 19;
			this.lblcorteanteriorefectivofinal.Text = "lblcorteanteriorefectivofinal";
			this.lblcorteanteriorsaldo.AutoSize = true;
			this.lblcorteanteriorsaldo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriorsaldo.ForeColor = global::System.Drawing.Color.DarkBlue;
			this.lblcorteanteriorsaldo.Location = new global::System.Drawing.Point(303, 403);
			this.lblcorteanteriorsaldo.Name = "lblcorteanteriorsaldo";
			this.lblcorteanteriorsaldo.Size = new global::System.Drawing.Size(228, 25);
			this.lblcorteanteriorsaldo.TabIndex = 18;
			this.lblcorteanteriorsaldo.Text = "lblcorteanteriorsaldo";
			this.lblcorteanteriorpropinas.AutoSize = true;
			this.lblcorteanteriorpropinas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriorpropinas.ForeColor = global::System.Drawing.Color.Red;
			this.lblcorteanteriorpropinas.Location = new global::System.Drawing.Point(302, 335);
			this.lblcorteanteriorpropinas.Name = "lblcorteanteriorpropinas";
			this.lblcorteanteriorpropinas.Size = new global::System.Drawing.Size(262, 25);
			this.lblcorteanteriorpropinas.TabIndex = 17;
			this.lblcorteanteriorpropinas.Text = "lblcorteanteriorpropinas";
			this.lblcorteanteriorretirosefectivo.AutoSize = true;
			this.lblcorteanteriorretirosefectivo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriorretirosefectivo.ForeColor = global::System.Drawing.Color.Red;
			this.lblcorteanteriorretirosefectivo.Location = new global::System.Drawing.Point(302, 293);
			this.lblcorteanteriorretirosefectivo.Name = "lblcorteanteriorretirosefectivo";
			this.lblcorteanteriorretirosefectivo.Size = new global::System.Drawing.Size(321, 25);
			this.lblcorteanteriorretirosefectivo.TabIndex = 16;
			this.lblcorteanteriorretirosefectivo.Text = "lblcorteanteriorretirosefectivo";
			this.lblcorteanteriordepositosenefectivo.AutoSize = true;
			this.lblcorteanteriordepositosenefectivo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriordepositosenefectivo.ForeColor = global::System.Drawing.Color.Green;
			this.lblcorteanteriordepositosenefectivo.Location = new global::System.Drawing.Point(302, 253);
			this.lblcorteanteriordepositosenefectivo.Name = "lblcorteanteriordepositosenefectivo";
			this.lblcorteanteriordepositosenefectivo.Size = new global::System.Drawing.Size(382, 25);
			this.lblcorteanteriordepositosenefectivo.TabIndex = 15;
			this.lblcorteanteriordepositosenefectivo.Text = "lblcorteanteriordepositosenefectivo";
			this.lblcorteanteriorotros.AutoSize = true;
			this.lblcorteanteriorotros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriorotros.ForeColor = global::System.Drawing.Color.Green;
			this.lblcorteanteriorotros.Location = new global::System.Drawing.Point(302, 211);
			this.lblcorteanteriorotros.Name = "lblcorteanteriorotros";
			this.lblcorteanteriorotros.Size = new global::System.Drawing.Size(224, 25);
			this.lblcorteanteriorotros.TabIndex = 14;
			this.lblcorteanteriorotros.Text = "lblcorteanteriorotros";
			this.lblcorteanteriorvales.AutoSize = true;
			this.lblcorteanteriorvales.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteanteriorvales.ForeColor = global::System.Drawing.Color.Green;
			this.lblcorteanteriorvales.Location = new global::System.Drawing.Point(302, 171);
			this.lblcorteanteriorvales.Name = "lblcorteanteriorvales";
			this.lblcorteanteriorvales.Size = new global::System.Drawing.Size(227, 25);
			this.lblcorteanteriorvales.TabIndex = 13;
			this.lblcorteanteriorvales.Text = "lblcorteanteriorvales";
			this.lblcorteefectivoanterior.AutoSize = true;
			this.lblcorteefectivoanterior.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcorteefectivoanterior.ForeColor = global::System.Drawing.Color.Green;
			this.lblcorteefectivoanterior.Location = new global::System.Drawing.Point(302, 97);
			this.lblcorteefectivoanterior.Name = "lblcorteefectivoanterior";
			this.lblcorteefectivoanterior.Size = new global::System.Drawing.Size(254, 25);
			this.lblcorteefectivoanterior.TabIndex = 12;
			this.lblcorteefectivoanterior.Text = "lblcorteefectivoanterior";
			this.lblcortetarjetaanterior.AutoSize = true;
			this.lblcortetarjetaanterior.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblcortetarjetaanterior.ForeColor = global::System.Drawing.Color.Green;
			this.lblcortetarjetaanterior.Location = new global::System.Drawing.Point(302, 133);
			this.lblcortetarjetaanterior.Name = "lblcortetarjetaanterior";
			this.lblcortetarjetaanterior.Size = new global::System.Drawing.Size(238, 25);
			this.lblcortetarjetaanterior.TabIndex = 11;
			this.lblcortetarjetaanterior.Text = "lblcortetarjetaanterior";
			this.Label38.AutoSize = true;
			this.Label38.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label38.ForeColor = global::System.Drawing.Color.Black;
			this.Label38.Location = new global::System.Drawing.Point(13, 441);
			this.Label38.Name = "Label38";
			this.Label38.Size = new global::System.Drawing.Size(187, 50);
			this.Label38.TabIndex = 10;
			this.Label38.Text = "Efectivo final:\r\n(Deposito a cta.)";
			this.Label37.AutoSize = true;
			this.Label37.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label37.ForeColor = global::System.Drawing.Color.Black;
			this.Label37.Location = new global::System.Drawing.Point(13, 403);
			this.Label37.Name = "Label37";
			this.Label37.Size = new global::System.Drawing.Size(138, 25);
			this.Label37.TabIndex = 9;
			this.Label37.Text = "Saldo final :";
			this.Label36.AutoSize = true;
			this.Label36.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label36.ForeColor = global::System.Drawing.Color.Black;
			this.Label36.Location = new global::System.Drawing.Point(13, 335);
			this.Label36.Name = "Label36";
			this.Label36.Size = new global::System.Drawing.Size(231, 25);
			this.Label36.TabIndex = 8;
			this.Label36.Text = "- Propinas pagadas :";
			this.Label35.AutoSize = true;
			this.Label35.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label35.ForeColor = global::System.Drawing.Color.Black;
			this.Label35.Location = new global::System.Drawing.Point(13, 293);
			this.Label35.Name = "Label35";
			this.Label35.Size = new global::System.Drawing.Size(239, 25);
			this.Label35.TabIndex = 7;
			this.Label35.Text = "- Retiros en efectivo :";
			this.Label34.AutoSize = true;
			this.Label34.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label34.ForeColor = global::System.Drawing.Color.Black;
			this.Label34.Location = new global::System.Drawing.Point(13, 253);
			this.Label34.Name = "Label34";
			this.Label34.Size = new global::System.Drawing.Size(274, 25);
			this.Label34.TabIndex = 6;
			this.Label34.Text = "+ Depositos en efectivo :";
			this.Label33.AutoSize = true;
			this.Label33.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label33.ForeColor = global::System.Drawing.Color.Black;
			this.Label33.Location = new global::System.Drawing.Point(13, 211);
			this.Label33.Name = "Label33";
			this.Label33.Size = new global::System.Drawing.Size(103, 25);
			this.Label33.TabIndex = 5;
			this.Label33.Text = "+ Otros :";
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label32.ForeColor = global::System.Drawing.Color.Black;
			this.Label32.Location = new global::System.Drawing.Point(13, 171);
			this.Label32.Name = "Label32";
			this.Label32.Size = new global::System.Drawing.Size(105, 25);
			this.Label32.TabIndex = 4;
			this.Label32.Text = "+ Vales :";
			this.Label31.AutoSize = true;
			this.Label31.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label31.ForeColor = global::System.Drawing.Color.Black;
			this.Label31.Location = new global::System.Drawing.Point(13, 133);
			this.Label31.Name = "Label31";
			this.Label31.Size = new global::System.Drawing.Size(120, 25);
			this.Label31.TabIndex = 3;
			this.Label31.Text = "+ Tarjeta :";
			this.Label30.AutoSize = true;
			this.Label30.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label30.ForeColor = global::System.Drawing.Color.Black;
			this.Label30.Location = new global::System.Drawing.Point(13, 97);
			this.Label30.Name = "Label30";
			this.Label30.Size = new global::System.Drawing.Size(131, 25);
			this.Label30.TabIndex = 2;
			this.Label30.Text = "+ Efectivo :";
			this.Label29.AutoSize = true;
			this.Label29.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label29.ForeColor = global::System.Drawing.Color.Black;
			this.Label29.Location = new global::System.Drawing.Point(13, 63);
			this.Label29.Name = "Label29";
			this.Label29.Size = new global::System.Drawing.Size(181, 25);
			this.Label29.TabIndex = 1;
			this.Label29.Text = "+ Fondo inicial :";
			this.Label28.AutoSize = true;
			this.Label28.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label28.Location = new global::System.Drawing.Point(11, 11);
			this.Label28.Name = "Label28";
			this.Label28.Size = new global::System.Drawing.Size(516, 37);
			this.Label28.TabIndex = 0;
			this.Label28.Text = "CORTE REAL (SIN MODIFICAR)";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(2326, 1319);
			base.Controls.Add(this.Panelvercortes);
			base.Controls.Add(this.dgvNotas);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "FrmBitacora";
			this.Text = "FrmBitacora";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).EndInit();
			this.Panelvercortes.ResumeLayout(false);
			this.Panelvercortes.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040000C5 RID: 197
		private global::System.ComponentModel.IContainer components;
	}
}
