namespace ModuloAdicional
{
	// Token: 0x0200000E RID: 14
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmDatosEmpresa : global::System.Windows.Forms.Form
	{
		// Token: 0x06000266 RID: 614 RVA: 0x0001A508 File Offset: 0x00018708
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000267 RID: 615 RVA: 0x0001A558 File Offset: 0x00018758
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmDatosEmpresa));
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.CheckBoxLeyenda3 = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxLeyenda2 = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxLeyenda1 = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxEstadoSuc = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxCiudadSuc = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxCodigoPostalSuc = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxDirSucursal = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxTelefono = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxRFC = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxEstado = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxPais = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxCP = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxCiudad = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxDirFiscal = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxRazonSocial = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxNombreComercial = new global::System.Windows.Forms.CheckBox();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_ImprimeCompuestos = new global::System.Windows.Forms.CheckBox();
			this.CheckBox_AgrupaTickets = new global::System.Windows.Forms.CheckBox();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.CheckBoxImpresionTicket = new global::System.Windows.Forms.CheckBox();
			this.txtLeyenda3 = new global::System.Windows.Forms.TextBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.txtLeyenda2 = new global::System.Windows.Forms.TextBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.txtLeyenda1 = new global::System.Windows.Forms.TextBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txtSucEstado = new global::System.Windows.Forms.TextBox();
			this.txtSucCodigoPostal = new global::System.Windows.Forms.TextBox();
			this.txtSucCiudaad = new global::System.Windows.Forms.TextBox();
			this.txtDirSucursal = new global::System.Windows.Forms.TextBox();
			this.TxtTelefono = new global::System.Windows.Forms.TextBox();
			this.txtRFC = new global::System.Windows.Forms.TextBox();
			this.txtPais = new global::System.Windows.Forms.TextBox();
			this.txtEstado = new global::System.Windows.Forms.TextBox();
			this.txtCiudad = new global::System.Windows.Forms.TextBox();
			this.txtCodigoPostal = new global::System.Windows.Forms.TextBox();
			this.txtDireccionFiscal = new global::System.Windows.Forms.TextBox();
			this.txtRazonSocial = new global::System.Windows.Forms.TextBox();
			this.txtNombreComercial = new global::System.Windows.Forms.TextBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.btnPruebaPrint = new global::System.Windows.Forms.Button();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			this.Panel2.SuspendLayout();
			this.Panel3.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			base.SuspendLayout();
			this.Panel1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel1.Controls.Add(this.PictureBox3);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(1494, 50);
			this.Panel1.TabIndex = 2;
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(1436, 0);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(58, 50);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 13;
			this.PictureBox3.TabStop = false;
			this.PictureBox3.Visible = false;
			this.Label1.Anchor = global::System.Windows.Forms.AnchorStyles.Left;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(6, 10);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(641, 124);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Captura los datos que se imprimiran en el Ticket\r\n\r\n\r\n\r\n";
			this.Panel2.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel2.Controls.Add(this.Button1);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel2.Location = new global::System.Drawing.Point(0, 985);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(1494, 96);
			this.Panel2.TabIndex = 3;
			this.Button1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.Button1.BackColor = global::System.Drawing.Color.Green;
			this.Button1.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.Button1.FlatAppearance.BorderSize = 2;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.Color.White;
			this.Button1.Location = new global::System.Drawing.Point(1188, 10);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(294, 74);
			this.Button1.TabIndex = 0;
			this.Button1.Text = "Guardar";
			this.Button1.UseVisualStyleBackColor = false;
			this.Panel3.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel3.Controls.Add(this.Label19);
			this.Panel3.Controls.Add(this.CheckBoxLeyenda3);
			this.Panel3.Controls.Add(this.CheckBoxLeyenda2);
			this.Panel3.Controls.Add(this.CheckBoxLeyenda1);
			this.Panel3.Controls.Add(this.CheckBoxEstadoSuc);
			this.Panel3.Controls.Add(this.CheckBoxCiudadSuc);
			this.Panel3.Controls.Add(this.CheckBoxCodigoPostalSuc);
			this.Panel3.Controls.Add(this.CheckBoxDirSucursal);
			this.Panel3.Controls.Add(this.CheckBoxTelefono);
			this.Panel3.Controls.Add(this.CheckBoxRFC);
			this.Panel3.Controls.Add(this.CheckBoxEstado);
			this.Panel3.Controls.Add(this.CheckBoxPais);
			this.Panel3.Controls.Add(this.CheckBoxCP);
			this.Panel3.Controls.Add(this.CheckBoxCiudad);
			this.Panel3.Controls.Add(this.CheckBoxDirFiscal);
			this.Panel3.Controls.Add(this.CheckBoxRazonSocial);
			this.Panel3.Controls.Add(this.CheckBoxNombreComercial);
			this.Panel3.Controls.Add(this.GroupBox1);
			this.Panel3.Controls.Add(this.txtLeyenda3);
			this.Panel3.Controls.Add(this.Label17);
			this.Panel3.Controls.Add(this.txtLeyenda2);
			this.Panel3.Controls.Add(this.Label16);
			this.Panel3.Controls.Add(this.txtLeyenda1);
			this.Panel3.Controls.Add(this.Label15);
			this.Panel3.Controls.Add(this.txtSucEstado);
			this.Panel3.Controls.Add(this.txtSucCodigoPostal);
			this.Panel3.Controls.Add(this.txtSucCiudaad);
			this.Panel3.Controls.Add(this.txtDirSucursal);
			this.Panel3.Controls.Add(this.TxtTelefono);
			this.Panel3.Controls.Add(this.txtRFC);
			this.Panel3.Controls.Add(this.txtPais);
			this.Panel3.Controls.Add(this.txtEstado);
			this.Panel3.Controls.Add(this.txtCiudad);
			this.Panel3.Controls.Add(this.txtCodigoPostal);
			this.Panel3.Controls.Add(this.txtDireccionFiscal);
			this.Panel3.Controls.Add(this.txtRazonSocial);
			this.Panel3.Controls.Add(this.txtNombreComercial);
			this.Panel3.Controls.Add(this.Label14);
			this.Panel3.Controls.Add(this.Label13);
			this.Panel3.Controls.Add(this.Label12);
			this.Panel3.Controls.Add(this.Label11);
			this.Panel3.Controls.Add(this.Label10);
			this.Panel3.Controls.Add(this.Label9);
			this.Panel3.Controls.Add(this.Label8);
			this.Panel3.Controls.Add(this.Label7);
			this.Panel3.Controls.Add(this.Label6);
			this.Panel3.Controls.Add(this.Label5);
			this.Panel3.Controls.Add(this.Label4);
			this.Panel3.Controls.Add(this.Label3);
			this.Panel3.Controls.Add(this.Label2);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel3.Location = new global::System.Drawing.Point(0, 50);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(1494, 935);
			this.Panel3.TabIndex = 4;
			this.Label19.AutoSize = true;
			this.Label19.ForeColor = global::System.Drawing.Color.Red;
			this.Label19.Location = new global::System.Drawing.Point(906, 31);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(366, 25);
			this.Label19.TabIndex = 54;
			this.Label19.Text = "*La impresora requiere ser  de 80mm";
			this.CheckBoxLeyenda3.AutoSize = true;
			this.CheckBoxLeyenda3.Location = new global::System.Drawing.Point(1357, 702);
			this.CheckBoxLeyenda3.Name = "CheckBoxLeyenda3";
			this.CheckBoxLeyenda3.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxLeyenda3.TabIndex = 53;
			this.CheckBoxLeyenda3.UseVisualStyleBackColor = true;
			this.CheckBoxLeyenda2.AutoSize = true;
			this.CheckBoxLeyenda2.Location = new global::System.Drawing.Point(1357, 544);
			this.CheckBoxLeyenda2.Name = "CheckBoxLeyenda2";
			this.CheckBoxLeyenda2.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxLeyenda2.TabIndex = 52;
			this.CheckBoxLeyenda2.UseVisualStyleBackColor = true;
			this.CheckBoxLeyenda1.AutoSize = true;
			this.CheckBoxLeyenda1.Location = new global::System.Drawing.Point(1357, 383);
			this.CheckBoxLeyenda1.Name = "CheckBoxLeyenda1";
			this.CheckBoxLeyenda1.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxLeyenda1.TabIndex = 51;
			this.CheckBoxLeyenda1.UseVisualStyleBackColor = true;
			this.CheckBoxEstadoSuc.AutoSize = true;
			this.CheckBoxEstadoSuc.Location = new global::System.Drawing.Point(442, 670);
			this.CheckBoxEstadoSuc.Name = "CheckBoxEstadoSuc";
			this.CheckBoxEstadoSuc.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxEstadoSuc.TabIndex = 50;
			this.CheckBoxEstadoSuc.UseVisualStyleBackColor = true;
			this.CheckBoxCiudadSuc.AutoSize = true;
			this.CheckBoxCiudadSuc.Location = new global::System.Drawing.Point(442, 614);
			this.CheckBoxCiudadSuc.Name = "CheckBoxCiudadSuc";
			this.CheckBoxCiudadSuc.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxCiudadSuc.TabIndex = 49;
			this.CheckBoxCiudadSuc.UseVisualStyleBackColor = true;
			this.CheckBoxCodigoPostalSuc.AutoSize = true;
			this.CheckBoxCodigoPostalSuc.Location = new global::System.Drawing.Point(847, 614);
			this.CheckBoxCodigoPostalSuc.Name = "CheckBoxCodigoPostalSuc";
			this.CheckBoxCodigoPostalSuc.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxCodigoPostalSuc.TabIndex = 48;
			this.CheckBoxCodigoPostalSuc.UseVisualStyleBackColor = true;
			this.CheckBoxDirSucursal.AutoSize = true;
			this.CheckBoxDirSucursal.Location = new global::System.Drawing.Point(847, 456);
			this.CheckBoxDirSucursal.Name = "CheckBoxDirSucursal";
			this.CheckBoxDirSucursal.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxDirSucursal.TabIndex = 47;
			this.CheckBoxDirSucursal.UseVisualStyleBackColor = true;
			this.CheckBoxTelefono.AutoSize = true;
			this.CheckBoxTelefono.Location = new global::System.Drawing.Point(847, 384);
			this.CheckBoxTelefono.Name = "CheckBoxTelefono";
			this.CheckBoxTelefono.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxTelefono.TabIndex = 46;
			this.CheckBoxTelefono.UseVisualStyleBackColor = true;
			this.CheckBoxRFC.AutoSize = true;
			this.CheckBoxRFC.Location = new global::System.Drawing.Point(442, 388);
			this.CheckBoxRFC.Name = "CheckBoxRFC";
			this.CheckBoxRFC.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxRFC.TabIndex = 45;
			this.CheckBoxRFC.UseVisualStyleBackColor = true;
			this.CheckBoxEstado.AutoSize = true;
			this.CheckBoxEstado.Location = new global::System.Drawing.Point(442, 323);
			this.CheckBoxEstado.Name = "CheckBoxEstado";
			this.CheckBoxEstado.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxEstado.TabIndex = 44;
			this.CheckBoxEstado.UseVisualStyleBackColor = true;
			this.CheckBoxPais.AutoSize = true;
			this.CheckBoxPais.Location = new global::System.Drawing.Point(847, 323);
			this.CheckBoxPais.Name = "CheckBoxPais";
			this.CheckBoxPais.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxPais.TabIndex = 43;
			this.CheckBoxPais.UseVisualStyleBackColor = true;
			this.CheckBoxCP.AutoSize = true;
			this.CheckBoxCP.Location = new global::System.Drawing.Point(442, 258);
			this.CheckBoxCP.Name = "CheckBoxCP";
			this.CheckBoxCP.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxCP.TabIndex = 42;
			this.CheckBoxCP.UseVisualStyleBackColor = true;
			this.CheckBoxCiudad.AutoSize = true;
			this.CheckBoxCiudad.Location = new global::System.Drawing.Point(847, 258);
			this.CheckBoxCiudad.Name = "CheckBoxCiudad";
			this.CheckBoxCiudad.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxCiudad.TabIndex = 41;
			this.CheckBoxCiudad.UseVisualStyleBackColor = true;
			this.CheckBoxDirFiscal.AutoSize = true;
			this.CheckBoxDirFiscal.Location = new global::System.Drawing.Point(847, 120);
			this.CheckBoxDirFiscal.Name = "CheckBoxDirFiscal";
			this.CheckBoxDirFiscal.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxDirFiscal.TabIndex = 40;
			this.CheckBoxDirFiscal.UseVisualStyleBackColor = true;
			this.CheckBoxRazonSocial.AutoSize = true;
			this.CheckBoxRazonSocial.Location = new global::System.Drawing.Point(847, 74);
			this.CheckBoxRazonSocial.Name = "CheckBoxRazonSocial";
			this.CheckBoxRazonSocial.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxRazonSocial.TabIndex = 39;
			this.CheckBoxRazonSocial.UseVisualStyleBackColor = true;
			this.CheckBoxNombreComercial.AutoSize = true;
			this.CheckBoxNombreComercial.Location = new global::System.Drawing.Point(847, 28);
			this.CheckBoxNombreComercial.Name = "CheckBoxNombreComercial";
			this.CheckBoxNombreComercial.Size = new global::System.Drawing.Size(28, 27);
			this.CheckBoxNombreComercial.TabIndex = 38;
			this.CheckBoxNombreComercial.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.btnPruebaPrint);
			this.GroupBox1.Controls.Add(this.CheckBox_ImprimeCompuestos);
			this.GroupBox1.Controls.Add(this.CheckBox_AgrupaTickets);
			this.GroupBox1.Controls.Add(this.ComboBox1);
			this.GroupBox1.Controls.Add(this.Label18);
			this.GroupBox1.Controls.Add(this.CheckBoxImpresionTicket);
			this.GroupBox1.Location = new global::System.Drawing.Point(906, 70);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(560, 274);
			this.GroupBox1.TabIndex = 37;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Impresion";
			this.CheckBox_ImprimeCompuestos.AutoSize = true;
			this.CheckBox_ImprimeCompuestos.Location = new global::System.Drawing.Point(13, 219);
			this.CheckBox_ImprimeCompuestos.Name = "CheckBox_ImprimeCompuestos";
			this.CheckBox_ImprimeCompuestos.Size = new global::System.Drawing.Size(245, 29);
			this.CheckBox_ImprimeCompuestos.TabIndex = 38;
			this.CheckBox_ImprimeCompuestos.Text = "Imprimir Compuestos";
			this.CheckBox_ImprimeCompuestos.UseVisualStyleBackColor = true;
			this.CheckBox_AgrupaTickets.AutoSize = true;
			this.CheckBox_AgrupaTickets.Location = new global::System.Drawing.Point(13, 173);
			this.CheckBox_AgrupaTickets.Name = "CheckBox_AgrupaTickets";
			this.CheckBox_AgrupaTickets.Size = new global::System.Drawing.Size(221, 29);
			this.CheckBox_AgrupaTickets.TabIndex = 37;
			this.CheckBox_AgrupaTickets.Text = "Agrupar productos";
			this.CheckBox_AgrupaTickets.UseVisualStyleBackColor = true;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(13, 108);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(453, 33);
			this.ComboBox1.TabIndex = 36;
			this.Label18.AutoSize = true;
			this.Label18.Location = new global::System.Drawing.Point(8, 72);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(289, 25);
			this.Label18.TabIndex = 33;
			this.Label18.Text = "Elige la impresora de Tickets";
			this.CheckBoxImpresionTicket.AutoSize = true;
			this.CheckBoxImpresionTicket.Location = new global::System.Drawing.Point(13, 32);
			this.CheckBoxImpresionTicket.Name = "CheckBoxImpresionTicket";
			this.CheckBoxImpresionTicket.Size = new global::System.Drawing.Size(324, 29);
			this.CheckBoxImpresionTicket.TabIndex = 32;
			this.CheckBoxImpresionTicket.Text = "Activar la impresion del ticket";
			this.CheckBoxImpresionTicket.UseVisualStyleBackColor = true;
			this.txtLeyenda3.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtLeyenda3.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtLeyenda3.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtLeyenda3.Location = new global::System.Drawing.Point(911, 702);
			this.txtLeyenda3.Multiline = true;
			this.txtLeyenda3.Name = "txtLeyenda3";
			this.txtLeyenda3.Size = new global::System.Drawing.Size(431, 119);
			this.txtLeyenda3.TabIndex = 31;
			this.Label17.AutoSize = true;
			this.Label17.Location = new global::System.Drawing.Point(911, 669);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(113, 25);
			this.Label17.TabIndex = 30;
			this.Label17.Text = "Leyenda 3";
			this.txtLeyenda2.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtLeyenda2.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtLeyenda2.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtLeyenda2.Location = new global::System.Drawing.Point(911, 543);
			this.txtLeyenda2.Multiline = true;
			this.txtLeyenda2.Name = "txtLeyenda2";
			this.txtLeyenda2.Size = new global::System.Drawing.Size(428, 119);
			this.txtLeyenda2.TabIndex = 29;
			this.Label16.AutoSize = true;
			this.Label16.Location = new global::System.Drawing.Point(914, 510);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(113, 25);
			this.Label16.TabIndex = 28;
			this.Label16.Text = "Leyenda 2";
			this.txtLeyenda1.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtLeyenda1.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtLeyenda1.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtLeyenda1.Location = new global::System.Drawing.Point(911, 380);
			this.txtLeyenda1.Multiline = true;
			this.txtLeyenda1.Name = "txtLeyenda1";
			this.txtLeyenda1.Size = new global::System.Drawing.Size(428, 119);
			this.txtLeyenda1.TabIndex = 27;
			this.Label15.AutoSize = true;
			this.Label15.Location = new global::System.Drawing.Point(914, 347);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(113, 25);
			this.Label15.TabIndex = 26;
			this.Label15.Text = "Leyenda 1";
			this.txtSucEstado.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtSucEstado.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSucEstado.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtSucEstado.Location = new global::System.Drawing.Point(203, 667);
			this.txtSucEstado.Name = "txtSucEstado";
			this.txtSucEstado.Size = new global::System.Drawing.Size(228, 24);
			this.txtSucEstado.TabIndex = 25;
			this.txtSucCodigoPostal.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtSucCodigoPostal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSucCodigoPostal.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtSucCodigoPostal.Location = new global::System.Drawing.Point(625, 611);
			this.txtSucCodigoPostal.Name = "txtSucCodigoPostal";
			this.txtSucCodigoPostal.Size = new global::System.Drawing.Size(210, 24);
			this.txtSucCodigoPostal.TabIndex = 24;
			this.txtSucCiudaad.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtSucCiudaad.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSucCiudaad.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtSucCiudaad.Location = new global::System.Drawing.Point(203, 611);
			this.txtSucCiudaad.Name = "txtSucCiudaad";
			this.txtSucCiudaad.Size = new global::System.Drawing.Size(228, 24);
			this.txtSucCiudaad.TabIndex = 23;
			this.txtDirSucursal.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtDirSucursal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtDirSucursal.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtDirSucursal.Location = new global::System.Drawing.Point(203, 456);
			this.txtDirSucursal.Multiline = true;
			this.txtDirSucursal.Name = "txtDirSucursal";
			this.txtDirSucursal.Size = new global::System.Drawing.Size(632, 119);
			this.txtDirSucursal.TabIndex = 22;
			this.TxtTelefono.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.TxtTelefono.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TxtTelefono.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.TxtTelefono.Location = new global::System.Drawing.Point(581, 381);
			this.TxtTelefono.Name = "TxtTelefono";
			this.TxtTelefono.Size = new global::System.Drawing.Size(254, 24);
			this.TxtTelefono.TabIndex = 21;
			this.txtRFC.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtRFC.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtRFC.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtRFC.Location = new global::System.Drawing.Point(203, 384);
			this.txtRFC.Name = "txtRFC";
			this.txtRFC.Size = new global::System.Drawing.Size(228, 24);
			this.txtRFC.TabIndex = 20;
			this.txtPais.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtPais.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPais.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtPais.Location = new global::System.Drawing.Point(581, 317);
			this.txtPais.Name = "txtPais";
			this.txtPais.Size = new global::System.Drawing.Size(254, 24);
			this.txtPais.TabIndex = 19;
			this.txtEstado.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtEstado.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtEstado.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtEstado.Location = new global::System.Drawing.Point(203, 317);
			this.txtEstado.Name = "txtEstado";
			this.txtEstado.Size = new global::System.Drawing.Size(228, 24);
			this.txtEstado.TabIndex = 18;
			this.txtCiudad.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtCiudad.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtCiudad.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtCiudad.Location = new global::System.Drawing.Point(581, 255);
			this.txtCiudad.Name = "txtCiudad";
			this.txtCiudad.Size = new global::System.Drawing.Size(254, 24);
			this.txtCiudad.TabIndex = 17;
			this.txtCodigoPostal.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtCodigoPostal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtCodigoPostal.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtCodigoPostal.Location = new global::System.Drawing.Point(203, 255);
			this.txtCodigoPostal.Name = "txtCodigoPostal";
			this.txtCodigoPostal.Size = new global::System.Drawing.Size(228, 24);
			this.txtCodigoPostal.TabIndex = 16;
			this.txtDireccionFiscal.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtDireccionFiscal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtDireccionFiscal.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtDireccionFiscal.Location = new global::System.Drawing.Point(203, 118);
			this.txtDireccionFiscal.Multiline = true;
			this.txtDireccionFiscal.Name = "txtDireccionFiscal";
			this.txtDireccionFiscal.Size = new global::System.Drawing.Size(632, 119);
			this.txtDireccionFiscal.TabIndex = 15;
			this.txtRazonSocial.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtRazonSocial.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtRazonSocial.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtRazonSocial.Location = new global::System.Drawing.Point(203, 73);
			this.txtRazonSocial.Name = "txtRazonSocial";
			this.txtRazonSocial.Size = new global::System.Drawing.Size(632, 24);
			this.txtRazonSocial.TabIndex = 14;
			this.txtNombreComercial.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtNombreComercial.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtNombreComercial.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtNombreComercial.Location = new global::System.Drawing.Point(203, 28);
			this.txtNombreComercial.Name = "txtNombreComercial";
			this.txtNombreComercial.Size = new global::System.Drawing.Size(632, 24);
			this.txtNombreComercial.TabIndex = 13;
			this.Label14.AutoSize = true;
			this.Label14.Location = new global::System.Drawing.Point(475, 614);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(144, 25);
			this.Label14.TabIndex = 12;
			this.Label14.Text = "Codigo postal";
			this.Label13.AutoSize = true;
			this.Label13.Location = new global::System.Drawing.Point(12, 673);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(79, 25);
			this.Label13.TabIndex = 11;
			this.Label13.Text = "Estado";
			this.Label12.AutoSize = true;
			this.Label12.Location = new global::System.Drawing.Point(12, 617);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(80, 25);
			this.Label12.TabIndex = 10;
			this.Label12.Text = "Ciudad";
			this.Label11.AutoSize = true;
			this.Label11.Location = new global::System.Drawing.Point(12, 456);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(189, 25);
			this.Label11.TabIndex = 9;
			this.Label11.Text = "Direccion sucursal";
			this.Label10.AutoSize = true;
			this.Label10.Location = new global::System.Drawing.Point(474, 387);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(96, 25);
			this.Label10.TabIndex = 8;
			this.Label10.Text = "Telefono";
			this.Label9.AutoSize = true;
			this.Label9.Location = new global::System.Drawing.Point(12, 387);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(44, 25);
			this.Label9.TabIndex = 7;
			this.Label9.Text = "Rfc";
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(474, 323);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(54, 25);
			this.Label8.TabIndex = 6;
			this.Label8.Text = "Pais";
			this.Label7.AutoSize = true;
			this.Label7.Location = new global::System.Drawing.Point(12, 323);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(79, 25);
			this.Label7.TabIndex = 5;
			this.Label7.Text = "Estado";
			this.Label6.AutoSize = true;
			this.Label6.Location = new global::System.Drawing.Point(474, 261);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(80, 25);
			this.Label6.TabIndex = 4;
			this.Label6.Text = "Ciudad";
			this.Label5.AutoSize = true;
			this.Label5.Location = new global::System.Drawing.Point(12, 261);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(144, 25);
			this.Label5.TabIndex = 3;
			this.Label5.Text = "Codigo postal";
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(12, 121);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(158, 25);
			this.Label4.TabIndex = 2;
			this.Label4.Text = "Direccion fiscal";
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(12, 79);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(136, 25);
			this.Label3.TabIndex = 1;
			this.Label3.Text = "Razon social";
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(12, 34);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(185, 25);
			this.Label2.TabIndex = 0;
			this.Label2.Text = "Nombre comercial";
			this.btnPruebaPrint.BackColor = global::System.Drawing.Color.White;
			this.btnPruebaPrint.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.btnPruebaPrint.FlatAppearance.BorderSize = 2;
			this.btnPruebaPrint.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnPruebaPrint.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnPruebaPrint.ForeColor = global::System.Drawing.Color.Black;
			this.btnPruebaPrint.Location = new global::System.Drawing.Point(264, 172);
			this.btnPruebaPrint.Name = "btnPruebaPrint";
			this.btnPruebaPrint.Size = new global::System.Drawing.Size(278, 81);
			this.btnPruebaPrint.TabIndex = 39;
			this.btnPruebaPrint.Text = "Prueba de Impresion";
			this.btnPruebaPrint.UseVisualStyleBackColor = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(1494, 1081);
			base.Controls.Add(this.Panel3);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "frmDatosEmpresa";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "frmDatosEmpresa";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			this.Panel2.ResumeLayout(false);
			this.Panel3.ResumeLayout(false);
			this.Panel3.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x04000106 RID: 262
		private global::System.ComponentModel.IContainer components;
	}
}
