namespace ModuloAdicional
{
	// Token: 0x02000016 RID: 22
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmEmail : global::System.Windows.Forms.Form
	{
		// Token: 0x06000819 RID: 2073 RVA: 0x00097CD8 File Offset: 0x00095ED8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600081A RID: 2074 RVA: 0x00097D28 File Offset: 0x00095F28
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmEmail));
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.lblDesencriptarpwd = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txtWebmail = new global::System.Windows.Forms.TextBox();
			this.txtPuerto = new global::System.Windows.Forms.TextBox();
			this.txtEmail = new global::System.Windows.Forms.TextBox();
			this.txtPassword = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.txtDestinatario = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox3 = new global::System.Windows.Forms.CheckBox();
			this.lblServidor = new global::System.Windows.Forms.Label();
			this.lblPuerto = new global::System.Windows.Forms.Label();
			this.lblemailenvio = new global::System.Windows.Forms.Label();
			this.lblpwd = new global::System.Windows.Forms.Label();
			this.CheckBox4 = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxActivar = new global::System.Windows.Forms.CheckBox();
			this.lblEncrpPassword = new global::System.Windows.Forms.Label();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			base.SuspendLayout();
			this.Panel1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel1.Controls.Add(this.lblDesencriptarpwd);
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Controls.Add(this.PictureBox3);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(814, 50);
			this.Panel1.TabIndex = 0;
			this.lblDesencriptarpwd.AutoSize = true;
			this.lblDesencriptarpwd.Location = new global::System.Drawing.Point(532, 26);
			this.lblDesencriptarpwd.Name = "lblDesencriptarpwd";
			this.lblDesencriptarpwd.Size = new global::System.Drawing.Size(77, 25);
			this.lblDesencriptarpwd.TabIndex = 130;
			this.lblDesencriptarpwd.Text = "Label8";
			this.lblDesencriptarpwd.Visible = false;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(2, 1);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(49, 49);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 129;
			this.PictureBox1.TabStop = false;
			this.PictureBox3.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(766, 3);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(45, 45);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 128;
			this.PictureBox3.TabStop = false;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(57, 9);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(384, 29);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Configurar parametros de Email";
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.Location = new global::System.Drawing.Point(8, 66);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(178, 29);
			this.Label2.TabIndex = 1;
			this.Label2.Text = "Servidor SMTP";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.Location = new global::System.Drawing.Point(8, 109);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(220, 29);
			this.Label3.TabIndex = 2;
			this.Label3.Text = "Servidor de correo:";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.Location = new global::System.Drawing.Point(12, 155);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(90, 29);
			this.Label4.TabIndex = 3;
			this.Label4.Text = "Puerto:";
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.Location = new global::System.Drawing.Point(12, 201);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(192, 29);
			this.Label5.TabIndex = 4;
			this.Label5.Text = "Correo de envio:";
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Checked = true;
			this.CheckBox1.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox1.Enabled = false;
			this.CheckBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox1.Location = new global::System.Drawing.Point(428, 153);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(142, 33);
			this.CheckBox1.TabIndex = 5;
			this.CheckBox1.Text = "SSL/TLS";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.Location = new global::System.Drawing.Point(12, 299);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(142, 29);
			this.Label6.TabIndex = 6;
			this.Label6.Text = "Contraseña:";
			this.txtWebmail.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtWebmail.Location = new global::System.Drawing.Point(234, 106);
			this.txtWebmail.Name = "txtWebmail";
			this.txtWebmail.Size = new global::System.Drawing.Size(566, 35);
			this.txtWebmail.TabIndex = 7;
			this.txtPuerto.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtPuerto.Location = new global::System.Drawing.Point(234, 152);
			this.txtPuerto.Name = "txtPuerto";
			this.txtPuerto.Size = new global::System.Drawing.Size(183, 35);
			this.txtPuerto.TabIndex = 8;
			this.txtEmail.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtEmail.Location = new global::System.Drawing.Point(234, 198);
			this.txtEmail.Name = "txtEmail";
			this.txtEmail.Size = new global::System.Drawing.Size(566, 35);
			this.txtEmail.TabIndex = 9;
			this.txtPassword.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtPassword.Location = new global::System.Drawing.Point(234, 296);
			this.txtPassword.Name = "txtPassword";
			this.txtPassword.Size = new global::System.Drawing.Size(416, 35);
			this.txtPassword.TabIndex = 10;
			this.txtPassword.UseSystemPasswordChar = true;
			this.Button1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button1.Image");
			this.Button1.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Button1.Location = new global::System.Drawing.Point(563, 398);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(239, 81);
			this.Button1.TabIndex = 11;
			this.Button1.Text = "Guardar";
			this.Button1.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button1.UseVisualStyleBackColor = false;
			this.Button2.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Button2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button2.Image");
			this.Button2.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Button2.Location = new global::System.Drawing.Point(316, 398);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(239, 81);
			this.Button2.TabIndex = 12;
			this.Button2.Text = "Prueba";
			this.Button2.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.Button2.UseVisualStyleBackColor = false;
			this.txtDestinatario.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtDestinatario.Location = new global::System.Drawing.Point(234, 345);
			this.txtDestinatario.Name = "txtDestinatario";
			this.txtDestinatario.Size = new global::System.Drawing.Size(566, 35);
			this.txtDestinatario.TabIndex = 14;
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.Location = new global::System.Drawing.Point(12, 348);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(147, 29);
			this.Label7.TabIndex = 13;
			this.Label7.Text = "Destinatario:";
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Checked = true;
			this.CheckBox2.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox2.Location = new global::System.Drawing.Point(234, 251);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(274, 33);
			this.CheckBox2.TabIndex = 15;
			this.CheckBox2.Text = "Requiere Contraseña";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.CheckBox3.AutoSize = true;
			this.CheckBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox3.Location = new global::System.Drawing.Point(234, 66);
			this.CheckBox3.Name = "CheckBox3";
			this.CheckBox3.Size = new global::System.Drawing.Size(247, 29);
			this.CheckBox3.TabIndex = 16;
			this.CheckBox3.Text = "Usar Predeterminado";
			this.CheckBox3.UseVisualStyleBackColor = true;
			this.lblServidor.AutoSize = true;
			this.lblServidor.Location = new global::System.Drawing.Point(-5, 398);
			this.lblServidor.Name = "lblServidor";
			this.lblServidor.Size = new global::System.Drawing.Size(244, 25);
			this.lblServidor.TabIndex = 17;
			this.lblServidor.Text = "secure.tuproveedor.com";
			this.lblServidor.Visible = false;
			this.lblPuerto.AutoSize = true;
			this.lblPuerto.Location = new global::System.Drawing.Point(12, 429);
			this.lblPuerto.Name = "lblPuerto";
			this.lblPuerto.Size = new global::System.Drawing.Size(48, 25);
			this.lblPuerto.TabIndex = 18;
			this.lblPuerto.Text = "587";
			this.lblPuerto.Visible = false;
			this.lblemailenvio.AutoSize = true;
			this.lblemailenvio.Location = new global::System.Drawing.Point(24, 461);
			this.lblemailenvio.Name = "lblemailenvio";
			this.lblemailenvio.Size = new global::System.Drawing.Size(237, 25);
			this.lblemailenvio.TabIndex = 19;
			this.lblemailenvio.Text = "alertas@tudominio.com";
			this.lblemailenvio.Visible = false;
			this.lblpwd.AutoSize = true;
			this.lblpwd.Location = new global::System.Drawing.Point(12, 255);
			this.lblpwd.Name = "lblpwd";
			this.lblpwd.Size = new global::System.Drawing.Size(120, 25);
			this.lblpwd.TabIndex = 20;
			this.lblpwd.Text = "345345345";
			this.lblpwd.Visible = false;
			this.CheckBox4.AutoSize = true;
			this.CheckBox4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox4.Location = new global::System.Drawing.Point(656, 297);
			this.CheckBox4.Name = "CheckBox4";
			this.CheckBox4.Size = new global::System.Drawing.Size(82, 33);
			this.CheckBox4.TabIndex = 21;
			this.CheckBox4.Text = "Ver";
			this.CheckBox4.UseVisualStyleBackColor = true;
			this.CheckBoxActivar.AutoSize = true;
			this.CheckBoxActivar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBoxActivar.Location = new global::System.Drawing.Point(632, 66);
			this.CheckBoxActivar.Name = "CheckBoxActivar";
			this.CheckBoxActivar.Size = new global::System.Drawing.Size(170, 29);
			this.CheckBoxActivar.TabIndex = 130;
			this.CheckBoxActivar.Text = "Activar Envio";
			this.CheckBoxActivar.UseVisualStyleBackColor = true;
			this.lblEncrpPassword.AutoSize = true;
			this.lblEncrpPassword.Location = new global::System.Drawing.Point(592, 268);
			this.lblEncrpPassword.Name = "lblEncrpPassword";
			this.lblEncrpPassword.Size = new global::System.Drawing.Size(77, 25);
			this.lblEncrpPassword.TabIndex = 131;
			this.lblEncrpPassword.Text = "Label8";
			this.lblEncrpPassword.Visible = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(814, 495);
			base.Controls.Add(this.lblEncrpPassword);
			base.Controls.Add(this.CheckBoxActivar);
			base.Controls.Add(this.CheckBox4);
			base.Controls.Add(this.lblpwd);
			base.Controls.Add(this.lblemailenvio);
			base.Controls.Add(this.lblPuerto);
			base.Controls.Add(this.lblServidor);
			base.Controls.Add(this.CheckBox3);
			base.Controls.Add(this.CheckBox2);
			base.Controls.Add(this.txtDestinatario);
			base.Controls.Add(this.Label7);
			base.Controls.Add(this.Button2);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.txtPassword);
			base.Controls.Add(this.txtEmail);
			base.Controls.Add(this.txtPuerto);
			base.Controls.Add(this.txtWebmail);
			base.Controls.Add(this.Label6);
			base.Controls.Add(this.CheckBox1);
			base.Controls.Add(this.Label5);
			base.Controls.Add(this.Label4);
			base.Controls.Add(this.Label3);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "frmEmail";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "frmEmail";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040003B9 RID: 953
		private global::System.ComponentModel.IContainer components;
	}
}
