namespace ModuloAdicional
{
	// Token: 0x02000010 RID: 16
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmEditarTicketvb : global::System.Windows.Forms.Form
	{
		// Token: 0x0600031C RID: 796 RVA: 0x0001FFB0 File Offset: 0x0001E1B0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600031D RID: 797 RVA: 0x00020000 File Offset: 0x0001E200
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmEditarTicketvb));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.lblRefolear = new global::System.Windows.Forms.Label();
			this.chkRenumerar = new global::System.Windows.Forms.CheckBox();
			this.PanelInformacion = new global::System.Windows.Forms.Panel();
			this.PanelVariables = new global::System.Windows.Forms.Panel();
			this.lblEfectivoTurno1 = new global::System.Windows.Forms.Label();
			this.dateHoraFin = new global::System.Windows.Forms.DateTimePicker();
			this.dateHoraIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.lblTotalOtrosSinDescuento = new global::System.Windows.Forms.Label();
			this.lblTotalOtros = new global::System.Windows.Forms.Label();
			this.lblTotalBebidasDesc = new global::System.Windows.Forms.Label();
			this.lblTotalAlimentos = new global::System.Windows.Forms.Label();
			this.lblTotalAlimentosDescuento = new global::System.Windows.Forms.Label();
			this.lblTotalBebidas = new global::System.Windows.Forms.Label();
			this.lblFechadelProducto = new global::System.Windows.Forms.Label();
			this.lblidFoliodet = new global::System.Windows.Forms.Label();
			this.lblidturno_cierre = new global::System.Windows.Forms.Label();
			this.lblContarFilas = new global::System.Windows.Forms.Label();
			this.lblIdEstacion = new global::System.Windows.Forms.Label();
			this.lblMesero = new global::System.Windows.Forms.Label();
			this.btnEliminarProducto = new global::System.Windows.Forms.PictureBox();
			this.BtnAgregarProducto = new global::System.Windows.Forms.PictureBox();
			this.BtnVolver = new global::System.Windows.Forms.PictureBox();
			this.btnAplicar = new global::System.Windows.Forms.PictureBox();
			this.txtFechadelTicket = new global::System.Windows.Forms.TextBox();
			this.TxtFacturado = new global::System.Windows.Forms.TextBox();
			this.lblFolio = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.PanelBuscarProducto = new global::System.Windows.Forms.Panel();
			this.Panel17 = new global::System.Windows.Forms.Panel();
			this.dgwProductos = new global::System.Windows.Forms.DataGridView();
			this.Panel16 = new global::System.Windows.Forms.Panel();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.txtBuscarProducto = new global::System.Windows.Forms.TextBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.dateFechaFin = new global::System.Windows.Forms.DateTimePicker();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.dateFechaIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.cmbAnio = new global::System.Windows.Forms.ComboBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.lblEmpresa = new global::System.Windows.Forms.Label();
			this.txtPersonas = new global::System.Windows.Forms.TextBox();
			this.ComboBoxIdEmpresa = new global::System.Windows.Forms.ComboBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.lblPersonas = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.txtSerie = new global::System.Windows.Forms.TextBox();
			this.txtBuscarFolio = new global::System.Windows.Forms.TextBox();
			this.lblSerie = new global::System.Windows.Forms.Label();
			this.PanelBot = new global::System.Windows.Forms.Panel();
			this.Panel13 = new global::System.Windows.Forms.Panel();
			this.txtDescuento = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel14 = new global::System.Windows.Forms.Panel();
			this.txtSubtotal = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Panel15 = new global::System.Windows.Forms.Panel();
			this.txtTotal = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.PanelDGW = new global::System.Windows.Forms.Panel();
			this.dgvNotas = new global::System.Windows.Forms.DataGridView();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.progBar = new global::System.Windows.Forms.ProgressBar();
			this.Panel11 = new global::System.Windows.Forms.Panel();
			this.PanelPropina = new global::System.Windows.Forms.Panel();
			this.txtPropina = new global::System.Windows.Forms.TextBox();
			this.lblPropina = new global::System.Windows.Forms.Label();
			this.PanelOtros = new global::System.Windows.Forms.Panel();
			this.txtotros = new global::System.Windows.Forms.TextBox();
			this.lblOtros = new global::System.Windows.Forms.Label();
			this.PanelVales = new global::System.Windows.Forms.Panel();
			this.txtvales = new global::System.Windows.Forms.TextBox();
			this.lblVales = new global::System.Windows.Forms.Label();
			this.PanelTarjeta = new global::System.Windows.Forms.Panel();
			this.txtTarjeta = new global::System.Windows.Forms.TextBox();
			this.lbltarjeta = new global::System.Windows.Forms.Label();
			this.PanelEfectivo = new global::System.Windows.Forms.Panel();
			this.txtEfectivo = new global::System.Windows.Forms.TextBox();
			this.lblefectivo = new global::System.Windows.Forms.Label();
			this.Panel12 = new global::System.Windows.Forms.Panel();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.PanelInformacion.SuspendLayout();
			this.PanelVariables.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnEliminarProducto).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnAgregarProducto).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnVolver).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.btnAplicar).BeginInit();
			this.GroupBox1.SuspendLayout();
			this.PanelBuscarProducto.SuspendLayout();
			this.Panel17.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgwProductos).BeginInit();
			this.Panel16.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.PanelBot.SuspendLayout();
			this.Panel13.SuspendLayout();
			this.Panel14.SuspendLayout();
			this.Panel15.SuspendLayout();
			this.PanelDGW.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).BeginInit();
			this.Panel2.SuspendLayout();
			this.Panel11.SuspendLayout();
			this.PanelPropina.SuspendLayout();
			this.PanelOtros.SuspendLayout();
			this.PanelVales.SuspendLayout();
			this.PanelTarjeta.SuspendLayout();
			this.PanelEfectivo.SuspendLayout();
			this.Panel12.SuspendLayout();
			base.SuspendLayout();
			this.lblRefolear.AutoSize = true;
			this.lblRefolear.Location = new global::System.Drawing.Point(200, 96);
			this.lblRefolear.Name = "lblRefolear";
			this.lblRefolear.Size = new global::System.Drawing.Size(132, 25);
			this.lblRefolear.TabIndex = 2;
			this.lblRefolear.Text = "lblrenumerar";
			this.lblRefolear.Visible = false;
			this.chkRenumerar.AutoSize = true;
			this.chkRenumerar.Checked = true;
			this.chkRenumerar.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.chkRenumerar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.chkRenumerar.Location = new global::System.Drawing.Point(258, 83);
			this.chkRenumerar.Name = "chkRenumerar";
			this.chkRenumerar.Size = new global::System.Drawing.Size(111, 27);
			this.chkRenumerar.TabIndex = 1;
			this.chkRenumerar.Text = "Renumerar";
			this.chkRenumerar.UseVisualStyleBackColor = true;
			this.chkRenumerar.Visible = false;
			this.PanelInformacion.AutoSize = true;
			this.PanelInformacion.Controls.Add(this.PanelVariables);
			this.PanelInformacion.Controls.Add(this.btnEliminarProducto);
			this.PanelInformacion.Controls.Add(this.BtnAgregarProducto);
			this.PanelInformacion.Controls.Add(this.BtnVolver);
			this.PanelInformacion.Controls.Add(this.btnAplicar);
			this.PanelInformacion.Controls.Add(this.txtFechadelTicket);
			this.PanelInformacion.Controls.Add(this.TxtFacturado);
			this.PanelInformacion.Controls.Add(this.lblFolio);
			this.PanelInformacion.Controls.Add(this.Label19);
			this.PanelInformacion.Controls.Add(this.GroupBox1);
			this.PanelInformacion.Controls.Add(this.Label7);
			this.PanelInformacion.Controls.Add(this.lblEmpresa);
			this.PanelInformacion.Controls.Add(this.txtPersonas);
			this.PanelInformacion.Controls.Add(this.ComboBoxIdEmpresa);
			this.PanelInformacion.Controls.Add(this.Label1);
			this.PanelInformacion.Controls.Add(this.lblPersonas);
			this.PanelInformacion.Controls.Add(this.PictureBox1);
			this.PanelInformacion.Controls.Add(this.txtSerie);
			this.PanelInformacion.Controls.Add(this.txtBuscarFolio);
			this.PanelInformacion.Controls.Add(this.lblSerie);
			this.PanelInformacion.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.PanelInformacion.Location = new global::System.Drawing.Point(0, 0);
			this.PanelInformacion.Name = "PanelInformacion";
			this.PanelInformacion.Size = new global::System.Drawing.Size(2066, 634);
			this.PanelInformacion.TabIndex = 1;
			this.PanelVariables.Controls.Add(this.lblEfectivoTurno1);
			this.PanelVariables.Controls.Add(this.dateHoraFin);
			this.PanelVariables.Controls.Add(this.dateHoraIni);
			this.PanelVariables.Controls.Add(this.Label10);
			this.PanelVariables.Controls.Add(this.Label11);
			this.PanelVariables.Controls.Add(this.lblTotalOtrosSinDescuento);
			this.PanelVariables.Controls.Add(this.lblTotalOtros);
			this.PanelVariables.Controls.Add(this.lblTotalBebidasDesc);
			this.PanelVariables.Controls.Add(this.lblTotalAlimentos);
			this.PanelVariables.Controls.Add(this.lblTotalAlimentosDescuento);
			this.PanelVariables.Controls.Add(this.lblTotalBebidas);
			this.PanelVariables.Controls.Add(this.lblFechadelProducto);
			this.PanelVariables.Controls.Add(this.lblidFoliodet);
			this.PanelVariables.Controls.Add(this.lblidturno_cierre);
			this.PanelVariables.Controls.Add(this.lblContarFilas);
			this.PanelVariables.Controls.Add(this.chkRenumerar);
			this.PanelVariables.Controls.Add(this.lblIdEstacion);
			this.PanelVariables.Controls.Add(this.lblRefolear);
			this.PanelVariables.Controls.Add(this.lblMesero);
			this.PanelVariables.Location = new global::System.Drawing.Point(1478, 127);
			this.PanelVariables.Name = "PanelVariables";
			this.PanelVariables.Size = new global::System.Drawing.Size(809, 296);
			this.PanelVariables.TabIndex = 27;
			this.lblEfectivoTurno1.AutoSize = true;
			this.lblEfectivoTurno1.Location = new global::System.Drawing.Point(489, 73);
			this.lblEfectivoTurno1.Name = "lblEfectivoTurno1";
			this.lblEfectivoTurno1.Size = new global::System.Drawing.Size(167, 25);
			this.lblEfectivoTurno1.TabIndex = 91;
			this.lblEfectivoTurno1.Text = "lblEfectivoTurno";
			this.lblEfectivoTurno1.Visible = false;
			this.dateHoraFin.Enabled = false;
			this.dateHoraFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraFin.Location = new global::System.Drawing.Point(424, 249);
			this.dateHoraFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraFin.Name = "dateHoraFin";
			this.dateHoraFin.ShowUpDown = true;
			this.dateHoraFin.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraFin.TabIndex = 86;
			this.dateHoraFin.TabStop = false;
			this.dateHoraIni.Enabled = false;
			this.dateHoraIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraIni.Location = new global::System.Drawing.Point(424, 199);
			this.dateHoraIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraIni.Name = "dateHoraIni";
			this.dateHoraIni.ShowUpDown = true;
			this.dateHoraIni.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraIni.TabIndex = 84;
			this.dateHoraIni.TabStop = false;
			this.Label10.AutoSize = true;
			this.Label10.Location = new global::System.Drawing.Point(30, 247);
			this.Label10.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(143, 25);
			this.Label10.TabIndex = 88;
			this.Label10.Text = "Fecha FInal : ";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label11.AutoSize = true;
			this.Label11.Location = new global::System.Drawing.Point(22, 197);
			this.Label11.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(151, 25);
			this.Label11.TabIndex = 87;
			this.Label11.Text = "Fecha Inicial : ";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lblTotalOtrosSinDescuento.AutoSize = true;
			this.lblTotalOtrosSinDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalOtrosSinDescuento.Location = new global::System.Drawing.Point(205, 73);
			this.lblTotalOtrosSinDescuento.Name = "lblTotalOtrosSinDescuento";
			this.lblTotalOtrosSinDescuento.Size = new global::System.Drawing.Size(177, 17);
			this.lblTotalOtrosSinDescuento.TabIndex = 47;
			this.lblTotalOtrosSinDescuento.Text = "lblTotalOtrosSinDescuento";
			this.lblTotalOtrosSinDescuento.Visible = false;
			this.lblTotalOtros.AutoSize = true;
			this.lblTotalOtros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalOtros.Location = new global::System.Drawing.Point(237, 36);
			this.lblTotalOtros.Name = "lblTotalOtros";
			this.lblTotalOtros.Size = new global::System.Drawing.Size(89, 17);
			this.lblTotalOtros.TabIndex = 22;
			this.lblTotalOtros.Text = "lblTotalOtros";
			this.lblTotalOtros.Visible = false;
			this.lblTotalBebidasDesc.AutoSize = true;
			this.lblTotalBebidasDesc.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalBebidasDesc.Location = new global::System.Drawing.Point(13, 91);
			this.lblTotalBebidasDesc.Name = "lblTotalBebidasDesc";
			this.lblTotalBebidasDesc.Size = new global::System.Drawing.Size(137, 17);
			this.lblTotalBebidasDesc.TabIndex = 46;
			this.lblTotalBebidasDesc.Text = "lblTotalBebidasDesc";
			this.lblTotalBebidasDesc.Visible = false;
			this.lblTotalAlimentos.AutoSize = true;
			this.lblTotalAlimentos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalAlimentos.Location = new global::System.Drawing.Point(13, 34);
			this.lblTotalAlimentos.Name = "lblTotalAlimentos";
			this.lblTotalAlimentos.Size = new global::System.Drawing.Size(115, 17);
			this.lblTotalAlimentos.TabIndex = 20;
			this.lblTotalAlimentos.Text = "lblTotalAlimentos";
			this.lblTotalAlimentos.Visible = false;
			this.lblTotalAlimentosDescuento.AutoSize = true;
			this.lblTotalAlimentosDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalAlimentosDescuento.Location = new global::System.Drawing.Point(13, 69);
			this.lblTotalAlimentosDescuento.Name = "lblTotalAlimentosDescuento";
			this.lblTotalAlimentosDescuento.Size = new global::System.Drawing.Size(183, 17);
			this.lblTotalAlimentosDescuento.TabIndex = 45;
			this.lblTotalAlimentosDescuento.Text = "lblTotalAlimentosDescuento";
			this.lblTotalAlimentosDescuento.Visible = false;
			this.lblTotalBebidas.AutoSize = true;
			this.lblTotalBebidas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalBebidas.Location = new global::System.Drawing.Point(133, 36);
			this.lblTotalBebidas.Name = "lblTotalBebidas";
			this.lblTotalBebidas.Size = new global::System.Drawing.Size(105, 17);
			this.lblTotalBebidas.TabIndex = 21;
			this.lblTotalBebidas.Text = "lblTotalBebidas";
			this.lblTotalBebidas.Visible = false;
			this.lblFechadelProducto.AutoSize = true;
			this.lblFechadelProducto.Location = new global::System.Drawing.Point(360, 88);
			this.lblFechadelProducto.Name = "lblFechadelProducto";
			this.lblFechadelProducto.Size = new global::System.Drawing.Size(77, 25);
			this.lblFechadelProducto.TabIndex = 6;
			this.lblFechadelProducto.Text = "Label3";
			this.lblFechadelProducto.Visible = false;
			this.lblidFoliodet.AutoSize = true;
			this.lblidFoliodet.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblidFoliodet.Location = new global::System.Drawing.Point(56, 20);
			this.lblidFoliodet.Name = "lblidFoliodet";
			this.lblidFoliodet.Size = new global::System.Drawing.Size(72, 17);
			this.lblidFoliodet.TabIndex = 18;
			this.lblidFoliodet.Text = "lblFoliodet";
			this.lblidFoliodet.Visible = false;
			this.lblidturno_cierre.AutoSize = true;
			this.lblidturno_cierre.Location = new global::System.Drawing.Point(296, 71);
			this.lblidturno_cierre.Name = "lblidturno_cierre";
			this.lblidturno_cierre.Size = new global::System.Drawing.Size(166, 25);
			this.lblidturno_cierre.TabIndex = 5;
			this.lblidturno_cierre.Text = "lblidturno_cierre";
			this.lblidturno_cierre.Visible = false;
			this.lblContarFilas.AutoSize = true;
			this.lblContarFilas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblContarFilas.Location = new global::System.Drawing.Point(134, 20);
			this.lblContarFilas.Name = "lblContarFilas";
			this.lblContarFilas.Size = new global::System.Drawing.Size(93, 17);
			this.lblContarFilas.TabIndex = 19;
			this.lblContarFilas.Text = "lblContarFilas";
			this.lblContarFilas.Visible = false;
			this.lblIdEstacion.AutoSize = true;
			this.lblIdEstacion.Location = new global::System.Drawing.Point(220, 80);
			this.lblIdEstacion.Name = "lblIdEstacion";
			this.lblIdEstacion.Size = new global::System.Drawing.Size(134, 25);
			this.lblIdEstacion.TabIndex = 4;
			this.lblIdEstacion.Text = "lblIdEstacion";
			this.lblIdEstacion.Visible = false;
			this.lblMesero.AutoSize = true;
			this.lblMesero.Location = new global::System.Drawing.Point(254, 85);
			this.lblMesero.Name = "lblMesero";
			this.lblMesero.Size = new global::System.Drawing.Size(106, 25);
			this.lblMesero.TabIndex = 3;
			this.lblMesero.Text = "lblMesero";
			this.lblMesero.Visible = false;
			this.btnEliminarProducto.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnEliminarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnEliminarProducto.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnEliminarProducto.Image");
			this.btnEliminarProducto.Location = new global::System.Drawing.Point(652, 40);
			this.btnEliminarProducto.Name = "btnEliminarProducto";
			this.btnEliminarProducto.Size = new global::System.Drawing.Size(61, 32);
			this.btnEliminarProducto.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.btnEliminarProducto.TabIndex = 3;
			this.btnEliminarProducto.TabStop = false;
			this.BtnAgregarProducto.BackColor = global::System.Drawing.SystemColors.Control;
			this.BtnAgregarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.BtnAgregarProducto.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnAgregarProducto.Image");
			this.BtnAgregarProducto.Location = new global::System.Drawing.Point(591, 40);
			this.BtnAgregarProducto.Name = "BtnAgregarProducto";
			this.BtnAgregarProducto.Size = new global::System.Drawing.Size(61, 32);
			this.BtnAgregarProducto.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.BtnAgregarProducto.TabIndex = 2;
			this.BtnAgregarProducto.TabStop = false;
			this.BtnVolver.BackColor = global::System.Drawing.SystemColors.Control;
			this.BtnVolver.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.BtnVolver.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnVolver.Image");
			this.BtnVolver.Location = new global::System.Drawing.Point(1974, 22);
			this.BtnVolver.Name = "BtnVolver";
			this.BtnVolver.Size = new global::System.Drawing.Size(61, 32);
			this.BtnVolver.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.BtnVolver.TabIndex = 5;
			this.BtnVolver.TabStop = false;
			this.btnAplicar.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnAplicar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnAplicar.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnAplicar.Image");
			this.btnAplicar.Location = new global::System.Drawing.Point(1839, 12);
			this.btnAplicar.Name = "btnAplicar";
			this.btnAplicar.Size = new global::System.Drawing.Size(61, 32);
			this.btnAplicar.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.btnAplicar.TabIndex = 4;
			this.btnAplicar.TabStop = false;
			this.txtFechadelTicket.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtFechadelTicket.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtFechadelTicket.Enabled = false;
			this.txtFechadelTicket.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtFechadelTicket.Location = new global::System.Drawing.Point(1132, 72);
			this.txtFechadelTicket.Name = "txtFechadelTicket";
			this.txtFechadelTicket.Size = new global::System.Drawing.Size(163, 24);
			this.txtFechadelTicket.TabIndex = 6;
			this.TxtFacturado.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.TxtFacturado.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TxtFacturado.Enabled = false;
			this.TxtFacturado.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.TxtFacturado.Location = new global::System.Drawing.Point(1308, 72);
			this.TxtFacturado.Name = "TxtFacturado";
			this.TxtFacturado.Size = new global::System.Drawing.Size(114, 24);
			this.TxtFacturado.TabIndex = 16;
			this.lblFolio.AutoSize = true;
			this.lblFolio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblFolio.Location = new global::System.Drawing.Point(1132, 32);
			this.lblFolio.Name = "lblFolio";
			this.lblFolio.Size = new global::System.Drawing.Size(170, 25);
			this.lblFolio.TabIndex = 7;
			this.lblFolio.Text = "Fecha del ticket:";
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.Red;
			this.Label19.Location = new global::System.Drawing.Point(1439, 32);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(394, 60);
			this.Label19.TabIndex = 146;
			this.Label19.Text = "*Nota\r\nGenera un respaldo antes de aplicar el proceso,\r\nesta accion es irreversible.\r\n";
			this.GroupBox1.AutoSize = true;
			this.GroupBox1.Controls.Add(this.PanelBuscarProducto);
			this.GroupBox1.Controls.Add(this.dateFechaFin);
			this.GroupBox1.Controls.Add(this.Label13);
			this.GroupBox1.Controls.Add(this.dateFechaIni);
			this.GroupBox1.Controls.Add(this.Label12);
			this.GroupBox1.Controls.Add(this.ComboBox1);
			this.GroupBox1.Controls.Add(this.Label9);
			this.GroupBox1.Controls.Add(this.cmbAnio);
			this.GroupBox1.Controls.Add(this.Label14);
			this.GroupBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.GroupBox1.Location = new global::System.Drawing.Point(9, 9);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(1671, 622);
			this.GroupBox1.TabIndex = 90;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Periodo:";
			this.PanelBuscarProducto.BackColor = global::System.Drawing.SystemColors.Control;
			this.PanelBuscarProducto.Controls.Add(this.Panel17);
			this.PanelBuscarProducto.Controls.Add(this.Panel16);
			this.PanelBuscarProducto.Controls.Add(this.Panel1);
			this.PanelBuscarProducto.Location = new global::System.Drawing.Point(297, 214);
			this.PanelBuscarProducto.Name = "PanelBuscarProducto";
			this.PanelBuscarProducto.Size = new global::System.Drawing.Size(1368, 378);
			this.PanelBuscarProducto.TabIndex = 26;
			this.Panel17.Controls.Add(this.dgwProductos);
			this.Panel17.Location = new global::System.Drawing.Point(0, 404);
			this.Panel17.Name = "Panel17";
			this.Panel17.Size = new global::System.Drawing.Size(2066, 181);
			this.Panel17.TabIndex = 3;
			this.dgwProductos.AllowUserToAddRows = false;
			this.dgwProductos.AllowUserToDeleteRows = false;
			this.dgwProductos.AllowUserToResizeColumns = false;
			this.dgwProductos.AllowUserToResizeRows = false;
			this.dgwProductos.BackgroundColor = global::System.Drawing.Color.White;
			this.dgwProductos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgwProductos.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgwProductos.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgwProductos.Location = new global::System.Drawing.Point(0, 468);
			this.dgwProductos.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgwProductos.MultiSelect = false;
			this.dgwProductos.Name = "dgwProductos";
			this.dgwProductos.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dgwProductos.RowHeadersVisible = false;
			this.dgwProductos.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgwProductos.RowTemplate.Height = 24;
			this.dgwProductos.Size = new global::System.Drawing.Size(2066, 73);
			this.dgwProductos.TabIndex = 26;
			this.Panel16.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel16.Controls.Add(this.PictureBox2);
			this.Panel16.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel16.Location = new global::System.Drawing.Point(0, 338);
			this.Panel16.Name = "Panel16";
			this.Panel16.Size = new global::System.Drawing.Size(1368, 40);
			this.Panel16.TabIndex = 1;
			this.PictureBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox2.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(1338, 0);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(30, 40);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 0;
			this.PictureBox2.TabStop = false;
			this.Panel1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel1.Controls.Add(this.txtBuscarProducto);
			this.Panel1.Controls.Add(this.PictureBox3);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(1368, 44);
			this.Panel1.TabIndex = 0;
			this.txtBuscarProducto.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.txtBuscarProducto.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtBuscarProducto.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtBuscarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBuscarProducto.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtBuscarProducto.Location = new global::System.Drawing.Point(9, 10);
			this.txtBuscarProducto.Name = "txtBuscarProducto";
			this.txtBuscarProducto.Size = new global::System.Drawing.Size(498, 24);
			this.txtBuscarProducto.TabIndex = 8;
			this.txtBuscarProducto.Text = "BUSCAR PRODUCTO...";
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(1338, 0);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(30, 44);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 6;
			this.PictureBox3.TabStop = false;
			this.dateFechaFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaFin.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.dateFechaFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Custom;
			this.dateFechaFin.Location = new global::System.Drawing.Point(136, 84);
			this.dateFechaFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaFin.Name = "dateFechaFin";
			this.dateFechaFin.Size = new global::System.Drawing.Size(148, 31);
			this.dateFechaFin.TabIndex = 96;
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label13.ForeColor = global::System.Drawing.Color.Black;
			this.Label13.Location = new global::System.Drawing.Point(11, 89);
			this.Label13.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(143, 25);
			this.Label13.TabIndex = 95;
			this.Label13.Text = "Fecha FInal : ";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dateFechaIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaIni.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.dateFechaIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.dateFechaIni.Location = new global::System.Drawing.Point(137, 126);
			this.dateFechaIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaIni.MaxDate = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.dateFechaIni.MinDate = new global::System.DateTime(2017, 1, 1, 0, 0, 0, 0);
			this.dateFechaIni.Name = "dateFechaIni";
			this.dateFechaIni.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dateFechaIni.Size = new global::System.Drawing.Size(148, 31);
			this.dateFechaIni.TabIndex = 94;
			this.dateFechaIni.Value = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label12.ForeColor = global::System.Drawing.Color.Black;
			this.Label12.Location = new global::System.Drawing.Point(4, 129);
			this.Label12.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(151, 25);
			this.Label12.TabIndex = 93;
			this.Label12.Text = "Fecha Inicial : ";
			this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.ComboBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(264, 32);
			this.ComboBox1.Margin = new global::System.Windows.Forms.Padding(6);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(120, 33);
			this.ComboBox1.TabIndex = 92;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label9.ForeColor = global::System.Drawing.Color.Black;
			this.Label9.Location = new global::System.Drawing.Point(202, 40);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(53, 25);
			this.Label9.TabIndex = 91;
			this.Label9.Text = "Mes";
			this.cmbAnio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbAnio.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAnio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.cmbAnio.FormattingEnabled = true;
			this.cmbAnio.Location = new global::System.Drawing.Point(61, 32);
			this.cmbAnio.Margin = new global::System.Windows.Forms.Padding(6);
			this.cmbAnio.Name = "cmbAnio";
			this.cmbAnio.Size = new global::System.Drawing.Size(120, 33);
			this.cmbAnio.TabIndex = 90;
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label14.ForeColor = global::System.Drawing.Color.Black;
			this.Label14.Location = new global::System.Drawing.Point(7, 40);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(50, 25);
			this.Label14.TabIndex = 89;
			this.Label14.Text = "Año";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label7.Location = new global::System.Drawing.Point(1308, 32);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(115, 25);
			this.Label7.TabIndex = 15;
			this.Label7.Text = "Facturado:";
			this.lblEmpresa.AutoSize = true;
			this.lblEmpresa.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblEmpresa.Location = new global::System.Drawing.Point(932, 32);
			this.lblEmpresa.Name = "lblEmpresa";
			this.lblEmpresa.Size = new global::System.Drawing.Size(103, 25);
			this.lblEmpresa.TabIndex = 1;
			this.lblEmpresa.Text = "Empresa:";
			this.txtPersonas.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtPersonas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPersonas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtPersonas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtPersonas.Location = new global::System.Drawing.Point(1172, 140);
			this.txtPersonas.Name = "txtPersonas";
			this.txtPersonas.Size = new global::System.Drawing.Size(109, 24);
			this.txtPersonas.TabIndex = 8;
			this.txtPersonas.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.ComboBoxIdEmpresa.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.ComboBoxIdEmpresa.FlatStyle = global::System.Windows.Forms.FlatStyle.Popup;
			this.ComboBoxIdEmpresa.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.ComboBoxIdEmpresa.ForeColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.ComboBoxIdEmpresa.FormattingEnabled = true;
			this.ComboBoxIdEmpresa.Location = new global::System.Drawing.Point(932, 63);
			this.ComboBoxIdEmpresa.Name = "ComboBoxIdEmpresa";
			this.ComboBoxIdEmpresa.Size = new global::System.Drawing.Size(103, 33);
			this.ComboBoxIdEmpresa.TabIndex = 0;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label1.Location = new global::System.Drawing.Point(932, 106);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(138, 25);
			this.Label1.TabIndex = 4;
			this.Label1.Text = "Buscar Folio:";
			this.lblPersonas.AutoSize = true;
			this.lblPersonas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblPersonas.Location = new global::System.Drawing.Point(1172, 106);
			this.lblPersonas.Name = "lblPersonas";
			this.lblPersonas.Size = new global::System.Drawing.Size(109, 25);
			this.lblPersonas.TabIndex = 9;
			this.lblPersonas.Text = "Personas:";
			this.PictureBox1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.InitialImage = null;
			this.PictureBox1.Location = new global::System.Drawing.Point(1099, 127);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(45, 37);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 6;
			this.PictureBox1.TabStop = false;
			this.txtSerie.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtSerie.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSerie.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtSerie.Location = new global::System.Drawing.Point(1054, 72);
			this.txtSerie.Name = "txtSerie";
			this.txtSerie.Size = new global::System.Drawing.Size(56, 24);
			this.txtSerie.TabIndex = 2;
			this.txtSerie.Visible = false;
			this.txtBuscarFolio.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtBuscarFolio.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtBuscarFolio.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtBuscarFolio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBuscarFolio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtBuscarFolio.Location = new global::System.Drawing.Point(932, 140);
			this.txtBuscarFolio.Name = "txtBuscarFolio";
			this.txtBuscarFolio.Size = new global::System.Drawing.Size(155, 24);
			this.txtBuscarFolio.TabIndex = 5;
			this.txtBuscarFolio.Text = "000000000";
			this.lblSerie.AutoSize = true;
			this.lblSerie.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblSerie.Location = new global::System.Drawing.Point(1054, 32);
			this.lblSerie.Name = "lblSerie";
			this.lblSerie.Size = new global::System.Drawing.Size(68, 25);
			this.lblSerie.TabIndex = 3;
			this.lblSerie.Text = "Serie:";
			this.lblSerie.Visible = false;
			this.PanelBot.BackColor = global::System.Drawing.SystemColors.Control;
			this.PanelBot.Controls.Add(this.Panel13);
			this.PanelBot.Controls.Add(this.Panel14);
			this.PanelBot.Controls.Add(this.Panel15);
			this.PanelBot.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.PanelBot.Location = new global::System.Drawing.Point(0, 1106);
			this.PanelBot.Name = "PanelBot";
			this.PanelBot.Size = new global::System.Drawing.Size(2066, 56);
			this.PanelBot.TabIndex = 2;
			this.Panel13.Controls.Add(this.txtDescuento);
			this.Panel13.Controls.Add(this.Label2);
			this.Panel13.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Panel13.Location = new global::System.Drawing.Point(1732, 0);
			this.Panel13.Name = "Panel13";
			this.Panel13.Size = new global::System.Drawing.Size(122, 56);
			this.Panel13.TabIndex = 0;
			this.txtDescuento.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtDescuento.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtDescuento.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtDescuento.Location = new global::System.Drawing.Point(0, 25);
			this.txtDescuento.Name = "txtDescuento";
			this.txtDescuento.ReadOnly = true;
			this.txtDescuento.Size = new global::System.Drawing.Size(122, 24);
			this.txtDescuento.TabIndex = 0;
			this.Label2.AutoSize = true;
			this.Label2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label2.ForeColor = global::System.Drawing.Color.Black;
			this.Label2.Location = new global::System.Drawing.Point(0, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(113, 25);
			this.Label2.TabIndex = 1;
			this.Label2.Text = "Desc.Gral:";
			this.Panel14.Controls.Add(this.txtSubtotal);
			this.Panel14.Controls.Add(this.Label4);
			this.Panel14.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Panel14.Location = new global::System.Drawing.Point(1854, 0);
			this.Panel14.Name = "Panel14";
			this.Panel14.Size = new global::System.Drawing.Size(120, 56);
			this.Panel14.TabIndex = 1;
			this.txtSubtotal.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtSubtotal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSubtotal.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtSubtotal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtSubtotal.Location = new global::System.Drawing.Point(0, 25);
			this.txtSubtotal.Name = "txtSubtotal";
			this.txtSubtotal.ReadOnly = true;
			this.txtSubtotal.Size = new global::System.Drawing.Size(120, 24);
			this.txtSubtotal.TabIndex = 4;
			this.Label4.AutoSize = true;
			this.Label4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label4.ForeColor = global::System.Drawing.Color.Black;
			this.Label4.Location = new global::System.Drawing.Point(0, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(97, 25);
			this.Label4.TabIndex = 5;
			this.Label4.Text = "Subtotal:";
			this.Panel15.Controls.Add(this.txtTotal);
			this.Panel15.Controls.Add(this.Label5);
			this.Panel15.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Panel15.Location = new global::System.Drawing.Point(1974, 0);
			this.Panel15.Name = "Panel15";
			this.Panel15.Size = new global::System.Drawing.Size(92, 56);
			this.Panel15.TabIndex = 2;
			this.txtTotal.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtTotal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotal.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtTotal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtTotal.Location = new global::System.Drawing.Point(0, 25);
			this.txtTotal.Name = "txtTotal";
			this.txtTotal.ReadOnly = true;
			this.txtTotal.Size = new global::System.Drawing.Size(92, 24);
			this.txtTotal.TabIndex = 6;
			this.Label5.AutoSize = true;
			this.Label5.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label5.ForeColor = global::System.Drawing.Color.Black;
			this.Label5.Location = new global::System.Drawing.Point(0, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(66, 25);
			this.Label5.TabIndex = 7;
			this.Label5.Text = "Total:";
			this.PanelDGW.Controls.Add(this.dgvNotas);
			this.PanelDGW.Location = new global::System.Drawing.Point(0, 739);
			this.PanelDGW.Name = "PanelDGW";
			this.PanelDGW.Size = new global::System.Drawing.Size(2066, 363);
			this.PanelDGW.TabIndex = 3;
			this.dgvNotas.AllowUserToAddRows = false;
			this.dgvNotas.AllowUserToDeleteRows = false;
			this.dgvNotas.AllowUserToResizeColumns = false;
			this.dgvNotas.AllowUserToResizeRows = false;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.dgvNotas.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle;
			this.dgvNotas.BackgroundColor = global::System.Drawing.SystemColors.ActiveCaptionText;
			this.dgvNotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvNotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvNotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvNotas.Location = new global::System.Drawing.Point(0, 114);
			this.dgvNotas.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgvNotas.MultiSelect = false;
			this.dgvNotas.Name = "dgvNotas";
			this.dgvNotas.ReadOnly = true;
			this.dgvNotas.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dgvNotas.RowHeadersVisible = false;
			this.dgvNotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvNotas.RowTemplate.Height = 24;
			this.dgvNotas.Size = new global::System.Drawing.Size(2066, 511);
			this.dgvNotas.TabIndex = 25;
			this.Panel2.BackColor = global::System.Drawing.Color.White;
			this.Panel2.Controls.Add(this.progBar);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel2.Location = new global::System.Drawing.Point(0, 1102);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(2066, 4);
			this.Panel2.TabIndex = 4;
			this.progBar.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.progBar.Location = new global::System.Drawing.Point(0, 0);
			this.progBar.Margin = new global::System.Windows.Forms.Padding(6);
			this.progBar.Name = "progBar";
			this.progBar.Size = new global::System.Drawing.Size(2066, 4);
			this.progBar.TabIndex = 143;
			this.progBar.Visible = false;
			this.Panel11.Controls.Add(this.PanelPropina);
			this.Panel11.Controls.Add(this.PanelOtros);
			this.Panel11.Controls.Add(this.PanelVales);
			this.Panel11.Controls.Add(this.PanelTarjeta);
			this.Panel11.Controls.Add(this.PanelEfectivo);
			this.Panel11.Controls.Add(this.Panel12);
			this.Panel11.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel11.Location = new global::System.Drawing.Point(0, 634);
			this.Panel11.Name = "Panel11";
			this.Panel11.Size = new global::System.Drawing.Size(2066, 51);
			this.Panel11.TabIndex = 5;
			this.PanelPropina.Controls.Add(this.txtPropina);
			this.PanelPropina.Controls.Add(this.lblPropina);
			this.PanelPropina.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.PanelPropina.Location = new global::System.Drawing.Point(531, 0);
			this.PanelPropina.Name = "PanelPropina";
			this.PanelPropina.Size = new global::System.Drawing.Size(105, 51);
			this.PanelPropina.TabIndex = 43;
			this.txtPropina.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtPropina.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPropina.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtPropina.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtPropina.Location = new global::System.Drawing.Point(0, 25);
			this.txtPropina.Name = "txtPropina";
			this.txtPropina.ReadOnly = true;
			this.txtPropina.Size = new global::System.Drawing.Size(105, 24);
			this.txtPropina.TabIndex = 38;
			this.lblPropina.AutoSize = true;
			this.lblPropina.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.lblPropina.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblPropina.Location = new global::System.Drawing.Point(0, 0);
			this.lblPropina.Name = "lblPropina";
			this.lblPropina.Size = new global::System.Drawing.Size(92, 25);
			this.lblPropina.TabIndex = 37;
			this.lblPropina.Text = "Propina:";
			this.PanelOtros.Controls.Add(this.txtotros);
			this.PanelOtros.Controls.Add(this.lblOtros);
			this.PanelOtros.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.PanelOtros.Location = new global::System.Drawing.Point(426, 0);
			this.PanelOtros.Name = "PanelOtros";
			this.PanelOtros.Size = new global::System.Drawing.Size(105, 51);
			this.PanelOtros.TabIndex = 44;
			this.txtotros.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtotros.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtotros.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtotros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtotros.Location = new global::System.Drawing.Point(0, 25);
			this.txtotros.Name = "txtotros";
			this.txtotros.ReadOnly = true;
			this.txtotros.Size = new global::System.Drawing.Size(105, 24);
			this.txtotros.TabIndex = 34;
			this.lblOtros.AutoSize = true;
			this.lblOtros.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.lblOtros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblOtros.Location = new global::System.Drawing.Point(0, 0);
			this.lblOtros.Name = "lblOtros";
			this.lblOtros.Size = new global::System.Drawing.Size(70, 25);
			this.lblOtros.TabIndex = 35;
			this.lblOtros.Text = "Otros:";
			this.PanelVales.Controls.Add(this.txtvales);
			this.PanelVales.Controls.Add(this.lblVales);
			this.PanelVales.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.PanelVales.Location = new global::System.Drawing.Point(321, 0);
			this.PanelVales.Name = "PanelVales";
			this.PanelVales.Size = new global::System.Drawing.Size(105, 51);
			this.PanelVales.TabIndex = 42;
			this.txtvales.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtvales.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtvales.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtvales.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtvales.Location = new global::System.Drawing.Point(0, 25);
			this.txtvales.Name = "txtvales";
			this.txtvales.ReadOnly = true;
			this.txtvales.Size = new global::System.Drawing.Size(105, 24);
			this.txtvales.TabIndex = 32;
			this.lblVales.AutoSize = true;
			this.lblVales.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.lblVales.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblVales.Location = new global::System.Drawing.Point(0, 0);
			this.lblVales.Name = "lblVales";
			this.lblVales.Size = new global::System.Drawing.Size(72, 25);
			this.lblVales.TabIndex = 33;
			this.lblVales.Text = "Vales:";
			this.PanelTarjeta.Controls.Add(this.txtTarjeta);
			this.PanelTarjeta.Controls.Add(this.lbltarjeta);
			this.PanelTarjeta.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.PanelTarjeta.Location = new global::System.Drawing.Point(216, 0);
			this.PanelTarjeta.Name = "PanelTarjeta";
			this.PanelTarjeta.Size = new global::System.Drawing.Size(105, 51);
			this.PanelTarjeta.TabIndex = 41;
			this.txtTarjeta.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtTarjeta.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTarjeta.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtTarjeta.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtTarjeta.Location = new global::System.Drawing.Point(0, 25);
			this.txtTarjeta.Name = "txtTarjeta";
			this.txtTarjeta.ReadOnly = true;
			this.txtTarjeta.Size = new global::System.Drawing.Size(105, 24);
			this.txtTarjeta.TabIndex = 30;
			this.lbltarjeta.AutoSize = true;
			this.lbltarjeta.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.lbltarjeta.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lbltarjeta.Location = new global::System.Drawing.Point(0, 0);
			this.lbltarjeta.Name = "lbltarjeta";
			this.lbltarjeta.Size = new global::System.Drawing.Size(85, 25);
			this.lbltarjeta.TabIndex = 31;
			this.lbltarjeta.Text = "Tarjeta:";
			this.PanelEfectivo.Controls.Add(this.txtEfectivo);
			this.PanelEfectivo.Controls.Add(this.lblefectivo);
			this.PanelEfectivo.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.PanelEfectivo.Location = new global::System.Drawing.Point(111, 0);
			this.PanelEfectivo.Name = "PanelEfectivo";
			this.PanelEfectivo.Size = new global::System.Drawing.Size(105, 51);
			this.PanelEfectivo.TabIndex = 40;
			this.txtEfectivo.BackColor = global::System.Drawing.SystemColors.GradientInactiveCaption;
			this.txtEfectivo.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtEfectivo.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.txtEfectivo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtEfectivo.Location = new global::System.Drawing.Point(0, 25);
			this.txtEfectivo.Name = "txtEfectivo";
			this.txtEfectivo.ReadOnly = true;
			this.txtEfectivo.Size = new global::System.Drawing.Size(105, 24);
			this.txtEfectivo.TabIndex = 28;
			this.lblefectivo.AutoSize = true;
			this.lblefectivo.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.lblefectivo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.lblefectivo.Location = new global::System.Drawing.Point(0, 0);
			this.lblefectivo.Name = "lblefectivo";
			this.lblefectivo.Size = new global::System.Drawing.Size(95, 25);
			this.lblefectivo.TabIndex = 29;
			this.lblefectivo.Text = "Efectivo:";
			this.Panel12.Controls.Add(this.Label8);
			this.Panel12.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Panel12.Location = new global::System.Drawing.Point(0, 0);
			this.Panel12.Name = "Panel12";
			this.Panel12.Size = new global::System.Drawing.Size(111, 51);
			this.Panel12.TabIndex = 39;
			this.Label8.AutoSize = true;
			this.Label8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label8.Location = new global::System.Drawing.Point(0, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(159, 25);
			this.Label8.TabIndex = 27;
			this.Label8.Text = "Forma de Pago";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.AutoSize = true;
			base.ClientSize = new global::System.Drawing.Size(2066, 1162);
			base.Controls.Add(this.PanelDGW);
			base.Controls.Add(this.Panel11);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.PanelBot);
			base.Controls.Add(this.PanelInformacion);
			this.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Strikeout, global::System.Drawing.GraphicsUnit.Point, 0);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.MinimizeBox = false;
			base.Name = "frmEditarTicketvb";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Editar un ticket";
			this.PanelInformacion.ResumeLayout(false);
			this.PanelInformacion.PerformLayout();
			this.PanelVariables.ResumeLayout(false);
			this.PanelVariables.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnEliminarProducto).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnAgregarProducto).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnVolver).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.btnAplicar).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.PanelBuscarProducto.ResumeLayout(false);
			this.Panel17.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.dgwProductos).EndInit();
			this.Panel16.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.PanelBot.ResumeLayout(false);
			this.Panel13.ResumeLayout(false);
			this.Panel13.PerformLayout();
			this.Panel14.ResumeLayout(false);
			this.Panel14.PerformLayout();
			this.Panel15.ResumeLayout(false);
			this.Panel15.PerformLayout();
			this.PanelDGW.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).EndInit();
			this.Panel2.ResumeLayout(false);
			this.Panel11.ResumeLayout(false);
			this.PanelPropina.ResumeLayout(false);
			this.PanelPropina.PerformLayout();
			this.PanelOtros.ResumeLayout(false);
			this.PanelOtros.PerformLayout();
			this.PanelVales.ResumeLayout(false);
			this.PanelVales.PerformLayout();
			this.PanelTarjeta.ResumeLayout(false);
			this.PanelTarjeta.PerformLayout();
			this.PanelEfectivo.ResumeLayout(false);
			this.PanelEfectivo.PerformLayout();
			this.Panel12.ResumeLayout(false);
			this.Panel12.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x0400016B RID: 363
		private global::System.ComponentModel.IContainer components;
	}
}
