namespace ModuloAdicional
{
	// Token: 0x02000011 RID: 17
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmEditarTurnos : global::System.Windows.Forms.Form
	{
		// Token: 0x060003F1 RID: 1009 RVA: 0x0002C3A0 File Offset: 0x0002A5A0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060003F2 RID: 1010 RVA: 0x0002C3F0 File Offset: 0x0002A5F0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmEditarTurnos));
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.GroupBoxReprocesar = new global::System.Windows.Forms.GroupBox();
			this.CheckBoxSinPropina = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxPropina = new global::System.Windows.Forms.CheckBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.lblTarjeta = new global::System.Windows.Forms.Label();
			this.btnVistaPrevia = new global::System.Windows.Forms.Button();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.groupPeriodo = new global::System.Windows.Forms.GroupBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.cmbxEmpresa = new global::System.Windows.Forms.ComboBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.cmbxSerie = new global::System.Windows.Forms.ComboBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.cmbAnio = new global::System.Windows.Forms.ComboBox();
			this.dateHoraFin = new global::System.Windows.Forms.DateTimePicker();
			this.dateHoraIni = new global::System.Windows.Forms.DateTimePicker();
			this.dateFechaFin = new global::System.Windows.Forms.DateTimePicker();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.dateFechaIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.dgvNotas = new global::System.Windows.Forms.DataGridView();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.Panel1.SuspendLayout();
			this.GroupBoxReprocesar.SuspendLayout();
			this.groupPeriodo.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).BeginInit();
			base.SuspendLayout();
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(1859, 3);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(60, 60);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 144;
			this.PictureBox1.TabStop = false;
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.GroupBoxReprocesar);
			this.Panel1.Controls.Add(this.lblTarjeta);
			this.Panel1.Controls.Add(this.btnVistaPrevia);
			this.Panel1.Controls.Add(this.Label19);
			this.Panel1.Controls.Add(this.groupPeriodo);
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(1926, 238);
			this.Panel1.TabIndex = 145;
			this.GroupBoxReprocesar.Controls.Add(this.CheckBoxSinPropina);
			this.GroupBoxReprocesar.Controls.Add(this.CheckBoxPropina);
			this.GroupBoxReprocesar.Controls.Add(this.Button1);
			this.GroupBoxReprocesar.Location = new global::System.Drawing.Point(701, 7);
			this.GroupBoxReprocesar.Name = "GroupBoxReprocesar";
			this.GroupBoxReprocesar.Size = new global::System.Drawing.Size(300, 218);
			this.GroupBoxReprocesar.TabIndex = 151;
			this.GroupBoxReprocesar.TabStop = false;
			this.GroupBoxReprocesar.Text = "Reprocesar declaraciones";
			this.CheckBoxSinPropina.AutoSize = true;
			this.CheckBoxSinPropina.Location = new global::System.Drawing.Point(17, 76);
			this.CheckBoxSinPropina.Name = "CheckBoxSinPropina";
			this.CheckBoxSinPropina.Size = new global::System.Drawing.Size(166, 29);
			this.CheckBoxSinPropina.TabIndex = 151;
			this.CheckBoxSinPropina.Text = "Sin Propinas";
			this.CheckBoxSinPropina.UseVisualStyleBackColor = true;
			this.CheckBoxPropina.AutoSize = true;
			this.CheckBoxPropina.Checked = true;
			this.CheckBoxPropina.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBoxPropina.Location = new global::System.Drawing.Point(17, 36);
			this.CheckBoxPropina.Name = "CheckBoxPropina";
			this.CheckBoxPropina.Size = new global::System.Drawing.Size(174, 29);
			this.CheckBoxPropina.TabIndex = 150;
			this.CheckBoxPropina.Text = "Con Propinas";
			this.CheckBoxPropina.UseVisualStyleBackColor = true;
			this.Button1.BackColor = global::System.Drawing.Color.White;
			this.Button1.FlatAppearance.BorderSize = 2;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.Location = new global::System.Drawing.Point(17, 128);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(6);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(266, 74);
			this.Button1.TabIndex = 149;
			this.Button1.Text = "Reprocesar Declaraciones";
			this.Button1.UseVisualStyleBackColor = false;
			this.lblTarjeta.AutoSize = true;
			this.lblTarjeta.Location = new global::System.Drawing.Point(1660, 98);
			this.lblTarjeta.Name = "lblTarjeta";
			this.lblTarjeta.Size = new global::System.Drawing.Size(77, 25);
			this.lblTarjeta.TabIndex = 150;
			this.lblTarjeta.Text = "Label1";
			this.lblTarjeta.Visible = false;
			this.btnVistaPrevia.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.btnVistaPrevia.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.btnVistaPrevia.FlatAppearance.BorderSize = 2;
			this.btnVistaPrevia.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnVistaPrevia.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 13.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnVistaPrevia.ForeColor = global::System.Drawing.Color.White;
			this.btnVistaPrevia.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnVistaPrevia.Image");
			this.btnVistaPrevia.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnVistaPrevia.Location = new global::System.Drawing.Point(1010, 125);
			this.btnVistaPrevia.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnVistaPrevia.Name = "btnVistaPrevia";
			this.btnVistaPrevia.Size = new global::System.Drawing.Size(312, 99);
			this.btnVistaPrevia.TabIndex = 148;
			this.btnVistaPrevia.Text = "Vista Previa";
			this.btnVistaPrevia.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.btnVistaPrevia.UseVisualStyleBackColor = false;
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.Red;
			this.Label19.Location = new global::System.Drawing.Point(1029, 18);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(394, 60);
			this.Label19.TabIndex = 147;
			this.Label19.Text = "*Nota\r\nGenera un respaldo antes de aplicar el proceso,\r\nesta accion es irreversible.\r\n";
			this.groupPeriodo.Controls.Add(this.Label4);
			this.groupPeriodo.Controls.Add(this.cmbxEmpresa);
			this.groupPeriodo.Controls.Add(this.Label18);
			this.groupPeriodo.Controls.Add(this.ComboBox1);
			this.groupPeriodo.Controls.Add(this.Label7);
			this.groupPeriodo.Controls.Add(this.cmbxSerie);
			this.groupPeriodo.Controls.Add(this.Label17);
			this.groupPeriodo.Controls.Add(this.cmbAnio);
			this.groupPeriodo.Controls.Add(this.dateHoraFin);
			this.groupPeriodo.Controls.Add(this.dateHoraIni);
			this.groupPeriodo.Controls.Add(this.dateFechaFin);
			this.groupPeriodo.Controls.Add(this.Label3);
			this.groupPeriodo.Controls.Add(this.dateFechaIni);
			this.groupPeriodo.Controls.Add(this.Label8);
			this.groupPeriodo.Location = new global::System.Drawing.Point(6, 6);
			this.groupPeriodo.Margin = new global::System.Windows.Forms.Padding(6);
			this.groupPeriodo.Name = "groupPeriodo";
			this.groupPeriodo.Padding = new global::System.Windows.Forms.Padding(6);
			this.groupPeriodo.Size = new global::System.Drawing.Size(694, 219);
			this.groupPeriodo.TabIndex = 146;
			this.groupPeriodo.TabStop = false;
			this.groupPeriodo.Text = "Periodo";
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(20, 168);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(109, 25);
			this.Label4.TabIndex = 92;
			this.Label4.Text = "Empresa :";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.cmbxEmpresa.BackColor = global::System.Drawing.SystemColors.Window;
			this.cmbxEmpresa.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbxEmpresa.Enabled = false;
			this.cmbxEmpresa.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbxEmpresa.FormattingEnabled = true;
			this.cmbxEmpresa.Location = new global::System.Drawing.Point(137, 164);
			this.cmbxEmpresa.Margin = new global::System.Windows.Forms.Padding(4);
			this.cmbxEmpresa.Name = "cmbxEmpresa";
			this.cmbxEmpresa.Size = new global::System.Drawing.Size(166, 33);
			this.cmbxEmpresa.TabIndex = 90;
			this.Label18.AutoSize = true;
			this.Label18.Location = new global::System.Drawing.Point(344, 37);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(59, 25);
			this.Label18.TabIndex = 89;
			this.Label18.Text = "Mes:";
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(416, 29);
			this.ComboBox1.Margin = new global::System.Windows.Forms.Padding(6);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(234, 33);
			this.ComboBox1.TabIndex = 88;
			this.Label7.AutoSize = true;
			this.Label7.Location = new global::System.Drawing.Point(356, 179);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(74, 25);
			this.Label7.TabIndex = 85;
			this.Label7.Text = "Serie :";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label7.Visible = false;
			this.cmbxSerie.BackColor = global::System.Drawing.SystemColors.Window;
			this.cmbxSerie.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbxSerie.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbxSerie.FormattingEnabled = true;
			this.cmbxSerie.Location = new global::System.Drawing.Point(438, 171);
			this.cmbxSerie.Margin = new global::System.Windows.Forms.Padding(4);
			this.cmbxSerie.Name = "cmbxSerie";
			this.cmbxSerie.Size = new global::System.Drawing.Size(166, 33);
			this.cmbxSerie.TabIndex = 5;
			this.cmbxSerie.TabStop = false;
			this.cmbxSerie.Visible = false;
			this.Label17.AutoSize = true;
			this.Label17.Location = new global::System.Drawing.Point(32, 37);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(62, 25);
			this.Label17.TabIndex = 87;
			this.Label17.Text = "Año: ";
			this.cmbAnio.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAnio.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbAnio.FormattingEnabled = true;
			this.cmbAnio.Location = new global::System.Drawing.Point(108, 29);
			this.cmbAnio.Margin = new global::System.Windows.Forms.Padding(6);
			this.cmbAnio.Name = "cmbAnio";
			this.cmbAnio.Size = new global::System.Drawing.Size(194, 33);
			this.cmbAnio.Sorted = true;
			this.cmbAnio.TabIndex = 86;
			this.dateHoraFin.Enabled = false;
			this.dateHoraFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraFin.Location = new global::System.Drawing.Point(422, 119);
			this.dateHoraFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraFin.Name = "dateHoraFin";
			this.dateHoraFin.ShowUpDown = true;
			this.dateHoraFin.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraFin.TabIndex = 3;
			this.dateHoraFin.TabStop = false;
			this.dateHoraFin.Value = new global::System.DateTime(2022, 6, 15, 5, 59, 59, 0);
			this.dateHoraIni.Enabled = false;
			this.dateHoraIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraIni.Location = new global::System.Drawing.Point(422, 76);
			this.dateHoraIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraIni.Name = "dateHoraIni";
			this.dateHoraIni.ShowUpDown = true;
			this.dateHoraIni.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraIni.TabIndex = 1;
			this.dateHoraIni.TabStop = false;
			this.dateHoraIni.Value = new global::System.DateTime(2022, 6, 15, 6, 0, 0, 0);
			this.dateFechaFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Custom;
			this.dateFechaFin.Location = new global::System.Drawing.Point(180, 119);
			this.dateFechaFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaFin.Name = "dateFechaFin";
			this.dateFechaFin.Size = new global::System.Drawing.Size(196, 31);
			this.dateFechaFin.TabIndex = 1;
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(28, 122);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(143, 25);
			this.Label3.TabIndex = 82;
			this.Label3.Text = "Fecha FInal : ";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dateFechaIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.dateFechaIni.Location = new global::System.Drawing.Point(180, 76);
			this.dateFechaIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaIni.MaxDate = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.dateFechaIni.MinDate = new global::System.DateTime(2017, 1, 1, 0, 0, 0, 0);
			this.dateFechaIni.Name = "dateFechaIni";
			this.dateFechaIni.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dateFechaIni.Size = new global::System.Drawing.Size(196, 31);
			this.dateFechaIni.TabIndex = 0;
			this.dateFechaIni.Value = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(20, 79);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(151, 25);
			this.Label8.TabIndex = 80;
			this.Label8.Text = "Fecha Inicial : ";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dgvNotas.AllowUserToAddRows = false;
			this.dgvNotas.AllowUserToDeleteRows = false;
			this.dgvNotas.AllowUserToResizeColumns = false;
			this.dgvNotas.AllowUserToResizeRows = false;
			this.dgvNotas.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgvNotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvNotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvNotas.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgvNotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvNotas.Location = new global::System.Drawing.Point(0, 238);
			this.dgvNotas.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgvNotas.MultiSelect = false;
			this.dgvNotas.Name = "dgvNotas";
			this.dgvNotas.RowHeadersVisible = false;
			this.dgvNotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvNotas.RowTemplate.Height = 24;
			this.dgvNotas.Size = new global::System.Drawing.Size(1926, 611);
			this.dgvNotas.TabIndex = 146;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.Control;
			base.ClientSize = new global::System.Drawing.Size(1926, 849);
			base.Controls.Add(this.dgvNotas);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "frmEditarTurnos";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "frmEditarTurnos";
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.GroupBoxReprocesar.ResumeLayout(false);
			this.GroupBoxReprocesar.PerformLayout();
			this.groupPeriodo.ResumeLayout(false);
			this.groupPeriodo.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x040001C7 RID: 455
		private global::System.ComponentModel.IContainer components;
	}
}
