namespace ModuloAdicional
{
	// Token: 0x02000018 RID: 24
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmImprimir_Tickets : global::System.Windows.Forms.Form
	{
		// Token: 0x060009FE RID: 2558 RVA: 0x000AEED8 File Offset: 0x000AD0D8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060009FF RID: 2559 RVA: 0x000AEF28 File Offset: 0x000AD128
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmImprimir_Tickets));
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.CheckBox3_Todos = new global::System.Windows.Forms.CheckBox();
			this.lblimpresora = new global::System.Windows.Forms.Label();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.GroupBox_Imprimir = new global::System.Windows.Forms.GroupBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txtTotalTickets = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.lblTarjeta = new global::System.Windows.Forms.Label();
			this.btnVistaPrevia = new global::System.Windows.Forms.Button();
			this.groupPeriodo = new global::System.Windows.Forms.GroupBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.cmbxEmpresa = new global::System.Windows.Forms.ComboBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.cmbxSerie = new global::System.Windows.Forms.ComboBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.cmbAnio = new global::System.Windows.Forms.ComboBox();
			this.dateHoraFin = new global::System.Windows.Forms.DateTimePicker();
			this.dateHoraIni = new global::System.Windows.Forms.DateTimePicker();
			this.dateFechaFin = new global::System.Windows.Forms.DateTimePicker();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.dateFechaIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.dgvNotas = new global::System.Windows.Forms.DataGridView();
			this.Panel1.SuspendLayout();
			this.GroupBox_Imprimir.SuspendLayout();
			this.groupPeriodo.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).BeginInit();
			base.SuspendLayout();
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.CheckBox3_Todos);
			this.Panel1.Controls.Add(this.lblimpresora);
			this.Panel1.Controls.Add(this.CheckBox2);
			this.Panel1.Controls.Add(this.CheckBox1);
			this.Panel1.Controls.Add(this.GroupBox_Imprimir);
			this.Panel1.Controls.Add(this.lblTarjeta);
			this.Panel1.Controls.Add(this.btnVistaPrevia);
			this.Panel1.Controls.Add(this.groupPeriodo);
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(2120, 238);
			this.Panel1.TabIndex = 146;
			this.CheckBox3_Todos.AutoSize = true;
			this.CheckBox3_Todos.Checked = true;
			this.CheckBox3_Todos.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox3_Todos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.CheckBox3_Todos.Location = new global::System.Drawing.Point(1016, 21);
			this.CheckBox3_Todos.Name = "CheckBox3_Todos";
			this.CheckBox3_Todos.Size = new global::System.Drawing.Size(233, 29);
			this.CheckBox3_Todos.TabIndex = 154;
			this.CheckBox3_Todos.Text = "Seleccionar todos";
			this.CheckBox3_Todos.UseVisualStyleBackColor = true;
			this.lblimpresora.AutoSize = true;
			this.lblimpresora.Location = new global::System.Drawing.Point(1979, 79);
			this.lblimpresora.Name = "lblimpresora";
			this.lblimpresora.Size = new global::System.Drawing.Size(129, 25);
			this.lblimpresora.TabIndex = 153;
			this.lblimpresora.Text = "lblimpresora";
			this.lblimpresora.Visible = false;
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Checked = true;
			this.CheckBox2.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox2.Location = new global::System.Drawing.Point(1967, 75);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(153, 29);
			this.CheckBox2.TabIndex = 152;
			this.CheckBox2.Text = "Mini Printer";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.CheckBox2.Visible = false;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox1.Location = new global::System.Drawing.Point(1967, 78);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(116, 29);
			this.CheckBox1.TabIndex = 151;
			this.CheckBox1.Text = "Archivo";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.CheckBox1.Visible = false;
			this.GroupBox_Imprimir.Controls.Add(this.Label1);
			this.GroupBox_Imprimir.Controls.Add(this.txtTotalTickets);
			this.GroupBox_Imprimir.Controls.Add(this.Button1);
			this.GroupBox_Imprimir.Location = new global::System.Drawing.Point(699, 7);
			this.GroupBox_Imprimir.Name = "GroupBox_Imprimir";
			this.GroupBox_Imprimir.Size = new global::System.Drawing.Size(308, 211);
			this.GroupBox_Imprimir.TabIndex = 152;
			this.GroupBox_Imprimir.TabStop = false;
			this.GroupBox_Imprimir.Text = "Impresión";
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(16, 34);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(188, 25);
			this.Label1.TabIndex = 155;
			this.Label1.Text = "Total de Tickets ";
			this.txtTotalTickets.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalTickets.Location = new global::System.Drawing.Point(23, 65);
			this.txtTotalTickets.Name = "txtTotalTickets";
			this.txtTotalTickets.ReadOnly = true;
			this.txtTotalTickets.Size = new global::System.Drawing.Size(171, 24);
			this.txtTotalTickets.TabIndex = 154;
			this.Button1.BackColor = global::System.Drawing.Color.White;
			this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button1.FlatAppearance.BorderSize = 2;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 13.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Button1.Image");
			this.Button1.Location = new global::System.Drawing.Point(21, 99);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(6);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(266, 99);
			this.Button1.TabIndex = 153;
			this.Button1.UseVisualStyleBackColor = false;
			this.lblTarjeta.AutoSize = true;
			this.lblTarjeta.Location = new global::System.Drawing.Point(2040, 79);
			this.lblTarjeta.Name = "lblTarjeta";
			this.lblTarjeta.Size = new global::System.Drawing.Size(77, 25);
			this.lblTarjeta.TabIndex = 150;
			this.lblTarjeta.Text = "Label1";
			this.lblTarjeta.Visible = false;
			this.btnVistaPrevia.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.btnVistaPrevia.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnVistaPrevia.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.btnVistaPrevia.FlatAppearance.BorderSize = 2;
			this.btnVistaPrevia.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnVistaPrevia.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 13.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnVistaPrevia.ForeColor = global::System.Drawing.Color.White;
			this.btnVistaPrevia.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnVistaPrevia.Image");
			this.btnVistaPrevia.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnVistaPrevia.Location = new global::System.Drawing.Point(1016, 106);
			this.btnVistaPrevia.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnVistaPrevia.Name = "btnVistaPrevia";
			this.btnVistaPrevia.Size = new global::System.Drawing.Size(312, 99);
			this.btnVistaPrevia.TabIndex = 148;
			this.btnVistaPrevia.Text = "Vista Previa";
			this.btnVistaPrevia.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.btnVistaPrevia.UseVisualStyleBackColor = false;
			this.groupPeriodo.Controls.Add(this.Label4);
			this.groupPeriodo.Controls.Add(this.cmbxEmpresa);
			this.groupPeriodo.Controls.Add(this.Label18);
			this.groupPeriodo.Controls.Add(this.ComboBox1);
			this.groupPeriodo.Controls.Add(this.Label7);
			this.groupPeriodo.Controls.Add(this.cmbxSerie);
			this.groupPeriodo.Controls.Add(this.Label17);
			this.groupPeriodo.Controls.Add(this.cmbAnio);
			this.groupPeriodo.Controls.Add(this.dateHoraFin);
			this.groupPeriodo.Controls.Add(this.dateHoraIni);
			this.groupPeriodo.Controls.Add(this.dateFechaFin);
			this.groupPeriodo.Controls.Add(this.Label3);
			this.groupPeriodo.Controls.Add(this.dateFechaIni);
			this.groupPeriodo.Controls.Add(this.Label8);
			this.groupPeriodo.Location = new global::System.Drawing.Point(6, 6);
			this.groupPeriodo.Margin = new global::System.Windows.Forms.Padding(6);
			this.groupPeriodo.Name = "groupPeriodo";
			this.groupPeriodo.Padding = new global::System.Windows.Forms.Padding(6);
			this.groupPeriodo.Size = new global::System.Drawing.Size(694, 212);
			this.groupPeriodo.TabIndex = 146;
			this.groupPeriodo.TabStop = false;
			this.groupPeriodo.Text = "Periodo";
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(20, 166);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(109, 25);
			this.Label4.TabIndex = 92;
			this.Label4.Text = "Empresa :";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.cmbxEmpresa.BackColor = global::System.Drawing.SystemColors.Window;
			this.cmbxEmpresa.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbxEmpresa.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbxEmpresa.Enabled = false;
			this.cmbxEmpresa.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbxEmpresa.FormattingEnabled = true;
			this.cmbxEmpresa.Location = new global::System.Drawing.Point(137, 162);
			this.cmbxEmpresa.Margin = new global::System.Windows.Forms.Padding(4);
			this.cmbxEmpresa.Name = "cmbxEmpresa";
			this.cmbxEmpresa.Size = new global::System.Drawing.Size(166, 33);
			this.cmbxEmpresa.TabIndex = 90;
			this.Label18.AutoSize = true;
			this.Label18.Location = new global::System.Drawing.Point(344, 32);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(59, 25);
			this.Label18.TabIndex = 89;
			this.Label18.Text = "Mes:";
			this.ComboBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(416, 28);
			this.ComboBox1.Margin = new global::System.Windows.Forms.Padding(6);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(234, 33);
			this.ComboBox1.TabIndex = 88;
			this.Label7.AutoSize = true;
			this.Label7.Location = new global::System.Drawing.Point(356, 166);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(74, 25);
			this.Label7.TabIndex = 85;
			this.Label7.Text = "Serie :";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.cmbxSerie.BackColor = global::System.Drawing.SystemColors.Window;
			this.cmbxSerie.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbxSerie.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbxSerie.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbxSerie.FormattingEnabled = true;
			this.cmbxSerie.Location = new global::System.Drawing.Point(438, 162);
			this.cmbxSerie.Margin = new global::System.Windows.Forms.Padding(4);
			this.cmbxSerie.Name = "cmbxSerie";
			this.cmbxSerie.Size = new global::System.Drawing.Size(166, 33);
			this.cmbxSerie.TabIndex = 5;
			this.cmbxSerie.TabStop = false;
			this.Label17.AutoSize = true;
			this.Label17.Location = new global::System.Drawing.Point(32, 32);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(62, 25);
			this.Label17.TabIndex = 87;
			this.Label17.Text = "Año: ";
			this.cmbAnio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbAnio.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAnio.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbAnio.FormattingEnabled = true;
			this.cmbAnio.Location = new global::System.Drawing.Point(108, 28);
			this.cmbAnio.Margin = new global::System.Windows.Forms.Padding(6);
			this.cmbAnio.Name = "cmbAnio";
			this.cmbAnio.Size = new global::System.Drawing.Size(194, 33);
			this.cmbAnio.Sorted = true;
			this.cmbAnio.TabIndex = 86;
			this.dateHoraFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateHoraFin.Enabled = false;
			this.dateHoraFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraFin.Location = new global::System.Drawing.Point(422, 118);
			this.dateHoraFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraFin.Name = "dateHoraFin";
			this.dateHoraFin.ShowUpDown = true;
			this.dateHoraFin.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraFin.TabIndex = 3;
			this.dateHoraFin.TabStop = false;
			this.dateHoraFin.Value = new global::System.DateTime(2022, 6, 15, 5, 59, 59, 0);
			this.dateHoraIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateHoraIni.Enabled = false;
			this.dateHoraIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraIni.Location = new global::System.Drawing.Point(422, 75);
			this.dateHoraIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraIni.Name = "dateHoraIni";
			this.dateHoraIni.ShowUpDown = true;
			this.dateHoraIni.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraIni.TabIndex = 1;
			this.dateHoraIni.TabStop = false;
			this.dateHoraIni.Value = new global::System.DateTime(2022, 6, 15, 6, 0, 0, 0);
			this.dateFechaFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Custom;
			this.dateFechaFin.Location = new global::System.Drawing.Point(180, 118);
			this.dateFechaFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaFin.Name = "dateFechaFin";
			this.dateFechaFin.Size = new global::System.Drawing.Size(196, 31);
			this.dateFechaFin.TabIndex = 1;
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(28, 121);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(143, 25);
			this.Label3.TabIndex = 82;
			this.Label3.Text = "Fecha FInal : ";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dateFechaIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.dateFechaIni.Location = new global::System.Drawing.Point(180, 75);
			this.dateFechaIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaIni.MaxDate = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.dateFechaIni.MinDate = new global::System.DateTime(2017, 1, 1, 0, 0, 0, 0);
			this.dateFechaIni.Name = "dateFechaIni";
			this.dateFechaIni.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dateFechaIni.Size = new global::System.Drawing.Size(196, 31);
			this.dateFechaIni.TabIndex = 0;
			this.dateFechaIni.Value = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(20, 78);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(151, 25);
			this.Label8.TabIndex = 80;
			this.Label8.Text = "Fecha Inicial : ";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(2053, 3);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(60, 60);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 144;
			this.PictureBox1.TabStop = false;
			this.dgvNotas.AllowUserToAddRows = false;
			this.dgvNotas.AllowUserToDeleteRows = false;
			this.dgvNotas.AllowUserToResizeColumns = false;
			this.dgvNotas.AllowUserToResizeRows = false;
			this.dgvNotas.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgvNotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvNotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvNotas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dgvNotas.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgvNotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvNotas.Location = new global::System.Drawing.Point(0, 238);
			this.dgvNotas.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgvNotas.MultiSelect = false;
			this.dgvNotas.Name = "dgvNotas";
			this.dgvNotas.ReadOnly = true;
			this.dgvNotas.RowHeadersVisible = false;
			this.dgvNotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvNotas.RowTemplate.Height = 24;
			this.dgvNotas.Size = new global::System.Drawing.Size(2120, 869);
			this.dgvNotas.TabIndex = 147;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(2120, 1107);
			base.Controls.Add(this.dgvNotas);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "frmImprimir_Tickets";
			this.Text = "frmImprimir_Tickets";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.GroupBox_Imprimir.ResumeLayout(false);
			this.GroupBox_Imprimir.PerformLayout();
			this.groupPeriodo.ResumeLayout(false);
			this.groupPeriodo.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x04000492 RID: 1170
		private global::System.ComponentModel.IContainer components;
	}
}
