namespace ModuloAdicional
{
	// Token: 0x0200001B RID: 27
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmLogin : global::System.Windows.Forms.Form
	{
		// Token: 0x06000AB0 RID: 2736 RVA: 0x000B7458 File Offset: 0x000B5658
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000AB1 RID: 2737 RVA: 0x000B74A8 File Offset: 0x000B56A8
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmLogin));
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.txtcontraseña = new global::System.Windows.Forms.TextBox();
			this.txtlogin = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.datalistado = new global::System.Windows.Forms.DataGridView();
			this.Eli = new global::System.Windows.Forms.DataGridViewImageColumn();
			this.btnCrearUsuario = new global::System.Windows.Forms.Button();
			this.lblmodificaticket = new global::System.Windows.Forms.Label();
			this.lblEliminaFolios = new global::System.Windows.Forms.Label();
			this.lblidperfil = new global::System.Windows.Forms.Label();
			this.lblEliminarproductos = new global::System.Windows.Forms.Label();
			this.lblModificaTurnos = new global::System.Windows.Forms.Label();
			this.lblReportes = new global::System.Windows.Forms.Label();
			this.lblSOS = new global::System.Windows.Forms.Label();
			this.lblBitacora = new global::System.Windows.Forms.Label();
			this.lblconfiguracion = new global::System.Windows.Forms.Label();
			this.lblBasededatos = new global::System.Windows.Forms.Label();
			this.lblusuarioperfil = new global::System.Windows.Forms.Label();
			this.lblparametros = new global::System.Windows.Forms.Label();
			this.lblconexiondbo = new global::System.Windows.Forms.Label();
			this.lblautofactura = new global::System.Windows.Forms.Label();
			this.lblasignarproducto = new global::System.Windows.Forms.Label();
			this.lblicencia = new global::System.Windows.Forms.Label();
			this.lblcontador = new global::System.Windows.Forms.Label();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.lblEmail = new global::System.Windows.Forms.Label();
			this.lblSustituirProd = new global::System.Windows.Forms.Label();
			this.lblEliminarReemplaza = new global::System.Windows.Forms.Label();
			this.lblImprimeTicket = new global::System.Windows.Forms.Label();
			this.lblEmpresa_Tickets = new global::System.Windows.Forms.Label();
			this.btnVerPassword = new global::System.Windows.Forms.PictureBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.lblseconds = new global::System.Windows.Forms.Label();
			this.lbl5segundos = new global::System.Windows.Forms.Label();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.datalistado).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.btnVerPassword).BeginInit();
			this.Panel3.SuspendLayout();
			base.SuspendLayout();
			this.Button1.BackColor = global::System.Drawing.Color.FromArgb(51, 103, 204);
			this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button1.FlatAppearance.BorderSize = 0;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button1.ForeColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.Button1.Location = new global::System.Drawing.Point(12, 275);
			this.Button1.Margin = new global::System.Windows.Forms.Padding(2);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(167, 40);
			this.Button1.TabIndex = 16;
			this.Button1.Text = "Iniciar Sesión";
			this.Button1.UseVisualStyleBackColor = false;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.DimGray;
			this.Label2.Location = new global::System.Drawing.Point(18, 262);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(69, 9);
			this.Label2.TabIndex = 15;
			this.Label2.Text = "Ingresa contraseña";
			this.Panel2.BackColor = global::System.Drawing.Color.DimGray;
			this.Panel2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.125f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Panel2.Location = new global::System.Drawing.Point(18, 254);
			this.Panel2.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(145, 2);
			this.Panel2.TabIndex = 14;
			this.Panel1.BackColor = global::System.Drawing.Color.DimGray;
			this.Panel1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.125f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Panel1.Location = new global::System.Drawing.Point(18, 222);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(145, 2);
			this.Panel1.TabIndex = 13;
			this.txtcontraseña.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtcontraseña.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtcontraseña.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtcontraseña.Location = new global::System.Drawing.Point(18, 235);
			this.txtcontraseña.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtcontraseña.Name = "txtcontraseña";
			this.txtcontraseña.Size = new global::System.Drawing.Size(144, 17);
			this.txtcontraseña.TabIndex = 12;
			this.txtcontraseña.Text = "Nueva Contraseña";
			this.txtcontraseña.UseSystemPasswordChar = true;
			this.txtlogin.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtlogin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtlogin.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtlogin.Location = new global::System.Drawing.Point(18, 202);
			this.txtlogin.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtlogin.Name = "txtlogin";
			this.txtlogin.Size = new global::System.Drawing.Size(144, 17);
			this.txtlogin.TabIndex = 11;
			this.txtlogin.Text = "Nuevo Usuario";
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(64, 176);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(68, 20);
			this.Label1.TabIndex = 10;
			this.Label1.Text = "Acceso";
			this.PictureBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.PictureBox1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.None;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(22, 32);
			this.PictureBox1.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(145, 142);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 9;
			this.PictureBox1.TabStop = false;
			this.datalistado.AllowUserToAddRows = false;
			this.datalistado.AllowUserToDeleteRows = false;
			this.datalistado.AllowUserToResizeRows = false;
			this.datalistado.BackgroundColor = global::System.Drawing.Color.White;
			this.datalistado.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.datalistado.CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.datalistado.ColumnHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			this.datalistado.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.datalistado.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.Eli
			});
			this.datalistado.EnableHeadersVisualStyles = false;
			this.datalistado.Location = new global::System.Drawing.Point(50, 30);
			this.datalistado.Margin = new global::System.Windows.Forms.Padding(2);
			this.datalistado.Name = "datalistado";
			this.datalistado.ReadOnly = true;
			this.datalistado.RowHeadersBorderStyle = global::System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
			this.datalistado.RowHeadersVisible = false;
			this.datalistado.RowTemplate.DefaultCellStyle.SelectionBackColor = global::System.Drawing.Color.FromArgb(224, 224, 224);
			this.datalistado.RowTemplate.DefaultCellStyle.SelectionForeColor = global::System.Drawing.Color.Black;
			this.datalistado.RowTemplate.Height = 33;
			this.datalistado.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.datalistado.Size = new global::System.Drawing.Size(90, 119);
			this.datalistado.TabIndex = 17;
			this.datalistado.Visible = false;
			this.Eli.HeaderText = "";
			this.Eli.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("Eli.Image");
			this.Eli.ImageLayout = global::System.Windows.Forms.DataGridViewImageCellLayout.Zoom;
			this.Eli.Name = "Eli";
			this.Eli.ReadOnly = true;
			this.btnCrearUsuario.BackColor = global::System.Drawing.Color.FromArgb(255, 128, 0);
			this.btnCrearUsuario.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnCrearUsuario.FlatAppearance.BorderSize = 0;
			this.btnCrearUsuario.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnCrearUsuario.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnCrearUsuario.ForeColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.btnCrearUsuario.Location = new global::System.Drawing.Point(12, 275);
			this.btnCrearUsuario.Margin = new global::System.Windows.Forms.Padding(2);
			this.btnCrearUsuario.Name = "btnCrearUsuario";
			this.btnCrearUsuario.Size = new global::System.Drawing.Size(167, 40);
			this.btnCrearUsuario.TabIndex = 19;
			this.btnCrearUsuario.Text = "Crear Usuario";
			this.btnCrearUsuario.UseVisualStyleBackColor = false;
			this.lblmodificaticket.AutoSize = true;
			this.lblmodificaticket.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblmodificaticket.Location = new global::System.Drawing.Point(59, 51);
			this.lblmodificaticket.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblmodificaticket.Name = "lblmodificaticket";
			this.lblmodificaticket.Size = new global::System.Drawing.Size(58, 7);
			this.lblmodificaticket.TabIndex = 20;
			this.lblmodificaticket.Text = "lblmodificaticket";
			this.lblmodificaticket.Visible = false;
			this.lblEliminaFolios.AutoSize = true;
			this.lblEliminaFolios.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblEliminaFolios.Location = new global::System.Drawing.Point(59, 51);
			this.lblEliminaFolios.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblEliminaFolios.Name = "lblEliminaFolios";
			this.lblEliminaFolios.Size = new global::System.Drawing.Size(57, 7);
			this.lblEliminaFolios.TabIndex = 21;
			this.lblEliminaFolios.Text = "lblEliminaFolios";
			this.lblEliminaFolios.Visible = false;
			this.lblidperfil.AutoSize = true;
			this.lblidperfil.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblidperfil.Location = new global::System.Drawing.Point(72, 51);
			this.lblidperfil.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblidperfil.Name = "lblidperfil";
			this.lblidperfil.Size = new global::System.Drawing.Size(26, 7);
			this.lblidperfil.TabIndex = 22;
			this.lblidperfil.Text = "Label3";
			this.lblidperfil.Visible = false;
			this.lblEliminarproductos.AutoSize = true;
			this.lblEliminarproductos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblEliminarproductos.Location = new global::System.Drawing.Point(48, 51);
			this.lblEliminarproductos.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblEliminarproductos.Name = "lblEliminarproductos";
			this.lblEliminarproductos.Size = new global::System.Drawing.Size(71, 7);
			this.lblEliminarproductos.TabIndex = 23;
			this.lblEliminarproductos.Text = "lblEliminarproductos";
			this.lblEliminarproductos.Visible = false;
			this.lblModificaTurnos.AutoSize = true;
			this.lblModificaTurnos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblModificaTurnos.Location = new global::System.Drawing.Point(54, 51);
			this.lblModificaTurnos.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblModificaTurnos.Name = "lblModificaTurnos";
			this.lblModificaTurnos.Size = new global::System.Drawing.Size(62, 7);
			this.lblModificaTurnos.TabIndex = 24;
			this.lblModificaTurnos.Text = "lblModificaTurnos";
			this.lblModificaTurnos.Visible = false;
			this.lblReportes.AutoSize = true;
			this.lblReportes.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblReportes.Location = new global::System.Drawing.Point(48, 51);
			this.lblReportes.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblReportes.Name = "lblReportes";
			this.lblReportes.Size = new global::System.Drawing.Size(41, 7);
			this.lblReportes.TabIndex = 25;
			this.lblReportes.Text = "lblReportes";
			this.lblReportes.Visible = false;
			this.lblSOS.AutoSize = true;
			this.lblSOS.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblSOS.Location = new global::System.Drawing.Point(48, 51);
			this.lblSOS.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblSOS.Name = "lblSOS";
			this.lblSOS.Size = new global::System.Drawing.Size(27, 7);
			this.lblSOS.TabIndex = 26;
			this.lblSOS.Text = "lblSOS";
			this.lblSOS.Visible = false;
			this.lblBitacora.AutoSize = true;
			this.lblBitacora.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblBitacora.Location = new global::System.Drawing.Point(54, 51);
			this.lblBitacora.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblBitacora.Name = "lblBitacora";
			this.lblBitacora.Size = new global::System.Drawing.Size(38, 7);
			this.lblBitacora.TabIndex = 27;
			this.lblBitacora.Text = "lblbitacora";
			this.lblBitacora.Visible = false;
			this.lblconfiguracion.AutoSize = true;
			this.lblconfiguracion.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblconfiguracion.Location = new global::System.Drawing.Point(48, 51);
			this.lblconfiguracion.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblconfiguracion.Name = "lblconfiguracion";
			this.lblconfiguracion.Size = new global::System.Drawing.Size(56, 7);
			this.lblconfiguracion.TabIndex = 28;
			this.lblconfiguracion.Text = "lblconfiguracion";
			this.lblconfiguracion.Visible = false;
			this.lblBasededatos.AutoSize = true;
			this.lblBasededatos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblBasededatos.Location = new global::System.Drawing.Point(48, 51);
			this.lblBasededatos.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblBasededatos.Name = "lblBasededatos";
			this.lblBasededatos.Size = new global::System.Drawing.Size(55, 7);
			this.lblBasededatos.TabIndex = 29;
			this.lblBasededatos.Text = "lblBasededatos";
			this.lblBasededatos.Visible = false;
			this.lblusuarioperfil.AutoSize = true;
			this.lblusuarioperfil.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblusuarioperfil.Location = new global::System.Drawing.Point(59, 77);
			this.lblusuarioperfil.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblusuarioperfil.Name = "lblusuarioperfil";
			this.lblusuarioperfil.Size = new global::System.Drawing.Size(52, 7);
			this.lblusuarioperfil.TabIndex = 30;
			this.lblusuarioperfil.Text = "lblusuarioperfil";
			this.lblusuarioperfil.Visible = false;
			this.lblparametros.AutoSize = true;
			this.lblparametros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblparametros.Location = new global::System.Drawing.Point(59, 77);
			this.lblparametros.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblparametros.Name = "lblparametros";
			this.lblparametros.Size = new global::System.Drawing.Size(48, 7);
			this.lblparametros.TabIndex = 31;
			this.lblparametros.Text = "lblparametros";
			this.lblparametros.Visible = false;
			this.lblconexiondbo.AutoSize = true;
			this.lblconexiondbo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblconexiondbo.Location = new global::System.Drawing.Point(59, 77);
			this.lblconexiondbo.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblconexiondbo.Name = "lblconexiondbo";
			this.lblconexiondbo.Size = new global::System.Drawing.Size(54, 7);
			this.lblconexiondbo.TabIndex = 32;
			this.lblconexiondbo.Text = "lblconexiondbo";
			this.lblconexiondbo.Visible = false;
			this.lblautofactura.AutoSize = true;
			this.lblautofactura.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblautofactura.Location = new global::System.Drawing.Point(53, 77);
			this.lblautofactura.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblautofactura.Name = "lblautofactura";
			this.lblautofactura.Size = new global::System.Drawing.Size(48, 7);
			this.lblautofactura.TabIndex = 33;
			this.lblautofactura.Text = "lblautofactura";
			this.lblautofactura.Visible = false;
			this.lblasignarproducto.AutoSize = true;
			this.lblasignarproducto.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblasignarproducto.Location = new global::System.Drawing.Point(59, 77);
			this.lblasignarproducto.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblasignarproducto.Name = "lblasignarproducto";
			this.lblasignarproducto.Size = new global::System.Drawing.Size(64, 7);
			this.lblasignarproducto.TabIndex = 34;
			this.lblasignarproducto.Text = "lblasignarproducto";
			this.lblasignarproducto.Visible = false;
			this.lblicencia.AutoSize = true;
			this.lblicencia.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblicencia.Location = new global::System.Drawing.Point(72, 77);
			this.lblicencia.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblicencia.Name = "lblicencia";
			this.lblicencia.Size = new global::System.Drawing.Size(36, 7);
			this.lblicencia.TabIndex = 35;
			this.lblicencia.Text = "lblicencia";
			this.lblicencia.Visible = false;
			this.lblcontador.AutoSize = true;
			this.lblcontador.Location = new global::System.Drawing.Point(118, 175);
			this.lblcontador.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblcontador.Name = "lblcontador";
			this.lblcontador.Size = new global::System.Drawing.Size(39, 13);
			this.lblcontador.TabIndex = 36;
			this.lblcontador.Text = "Label3";
			this.lblcontador.Visible = false;
			this.PictureBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox2.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(162, 0);
			this.PictureBox2.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(30, 29);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.PictureBox2.TabIndex = 129;
			this.PictureBox2.TabStop = false;
			this.lblEmail.AutoSize = true;
			this.lblEmail.Location = new global::System.Drawing.Point(70, 111);
			this.lblEmail.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblEmail.Name = "lblEmail";
			this.lblEmail.Size = new global::System.Drawing.Size(39, 13);
			this.lblEmail.TabIndex = 130;
			this.lblEmail.Text = "Label3";
			this.lblEmail.Visible = false;
			this.lblSustituirProd.AutoSize = true;
			this.lblSustituirProd.Location = new global::System.Drawing.Point(52, 91);
			this.lblSustituirProd.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblSustituirProd.Name = "lblSustituirProd";
			this.lblSustituirProd.Size = new global::System.Drawing.Size(76, 13);
			this.lblSustituirProd.TabIndex = 131;
			this.lblSustituirProd.Text = "lblSustituirProd";
			this.lblSustituirProd.Visible = false;
			this.lblEliminarReemplaza.AutoSize = true;
			this.lblEliminarReemplaza.Location = new global::System.Drawing.Point(58, 131);
			this.lblEliminarReemplaza.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblEliminarReemplaza.Name = "lblEliminarReemplaza";
			this.lblEliminarReemplaza.Size = new global::System.Drawing.Size(106, 13);
			this.lblEliminarReemplaza.TabIndex = 132;
			this.lblEliminarReemplaza.Text = "lblEliminarReemplaza";
			this.lblEliminarReemplaza.Visible = false;
			this.lblImprimeTicket.AutoSize = true;
			this.lblImprimeTicket.Location = new global::System.Drawing.Point(56, 41);
			this.lblImprimeTicket.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblImprimeTicket.Name = "lblImprimeTicket";
			this.lblImprimeTicket.Size = new global::System.Drawing.Size(39, 13);
			this.lblImprimeTicket.TabIndex = 133;
			this.lblImprimeTicket.Text = "Label3";
			this.lblImprimeTicket.Visible = false;
			this.lblEmpresa_Tickets.AutoSize = true;
			this.lblEmpresa_Tickets.Location = new global::System.Drawing.Point(81, 65);
			this.lblEmpresa_Tickets.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblEmpresa_Tickets.Name = "lblEmpresa_Tickets";
			this.lblEmpresa_Tickets.Size = new global::System.Drawing.Size(39, 13);
			this.lblEmpresa_Tickets.TabIndex = 134;
			this.lblEmpresa_Tickets.Text = "Label3";
			this.lblEmpresa_Tickets.Visible = false;
			this.btnVerPassword.Anchor = global::System.Windows.Forms.AnchorStyles.Right;
			this.btnVerPassword.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnVerPassword.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnVerPassword.Image");
			this.btnVerPassword.Location = new global::System.Drawing.Point(169, 237);
			this.btnVerPassword.Margin = new global::System.Windows.Forms.Padding(2);
			this.btnVerPassword.Name = "btnVerPassword";
			this.btnVerPassword.Size = new global::System.Drawing.Size(21, 19);
			this.btnVerPassword.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.btnVerPassword.TabIndex = 135;
			this.btnVerPassword.TabStop = false;
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.ForeColor = global::System.Drawing.Color.DimGray;
			this.Label3.Location = new global::System.Drawing.Point(171, 257);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(17, 9);
			this.Label3.TabIndex = 136;
			this.Label3.Text = "Ver";
			this.lblseconds.AutoSize = true;
			this.lblseconds.Location = new global::System.Drawing.Point(6, 176);
			this.lblseconds.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblseconds.Name = "lblseconds";
			this.lblseconds.Size = new global::System.Drawing.Size(57, 13);
			this.lblseconds.TabIndex = 137;
			this.lblseconds.Text = "lblseconds";
			this.lblseconds.Visible = false;
			this.lbl5segundos.AutoSize = true;
			this.lbl5segundos.Location = new global::System.Drawing.Point(171, 184);
			this.lbl5segundos.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lbl5segundos.Name = "lbl5segundos";
			this.lbl5segundos.Size = new global::System.Drawing.Size(13, 13);
			this.lbl5segundos.TabIndex = 138;
			this.lbl5segundos.Text = "3";
			this.lbl5segundos.Visible = false;
			this.Panel3.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel3.Controls.Add(this.PictureBox2);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel3.Location = new global::System.Drawing.Point(0, 0);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(192, 29);
			this.Panel3.TabIndex = 139;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.White;
			base.ClientSize = new global::System.Drawing.Size(192, 323);
			base.Controls.Add(this.Panel3);
			base.Controls.Add(this.lbl5segundos);
			base.Controls.Add(this.lblseconds);
			base.Controls.Add(this.Label3);
			base.Controls.Add(this.btnVerPassword);
			base.Controls.Add(this.lblEmpresa_Tickets);
			base.Controls.Add(this.lblImprimeTicket);
			base.Controls.Add(this.lblEliminarReemplaza);
			base.Controls.Add(this.lblSustituirProd);
			base.Controls.Add(this.lblEmail);
			base.Controls.Add(this.lblcontador);
			base.Controls.Add(this.lblicencia);
			base.Controls.Add(this.lblasignarproducto);
			base.Controls.Add(this.lblautofactura);
			base.Controls.Add(this.lblconexiondbo);
			base.Controls.Add(this.lblparametros);
			base.Controls.Add(this.lblusuarioperfil);
			base.Controls.Add(this.lblBasededatos);
			base.Controls.Add(this.lblconfiguracion);
			base.Controls.Add(this.lblBitacora);
			base.Controls.Add(this.lblSOS);
			base.Controls.Add(this.lblReportes);
			base.Controls.Add(this.lblModificaTurnos);
			base.Controls.Add(this.lblEliminarproductos);
			base.Controls.Add(this.lblidperfil);
			base.Controls.Add(this.lblEliminaFolios);
			base.Controls.Add(this.lblmodificaticket);
			base.Controls.Add(this.btnCrearUsuario);
			base.Controls.Add(this.datalistado);
			base.Controls.Add(this.Button1);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.txtcontraseña);
			base.Controls.Add(this.txtlogin);
			base.Controls.Add(this.Label1);
			base.Controls.Add(this.PictureBox1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "frmLogin";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "frmLogin";
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.datalistado).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.btnVerPassword).EndInit();
			this.Panel3.ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040004EB RID: 1259
		private global::System.ComponentModel.IContainer components;
	}
}
