namespace ModuloAdicional
{
	// Token: 0x02000019 RID: 25
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmLicencia : global::System.Windows.Forms.Form
	{
		// Token: 0x06000A49 RID: 2633 RVA: 0x000B421C File Offset: 0x000B241C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000A4A RID: 2634 RVA: 0x000B426C File Offset: 0x000B246C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmLicencia));
			this.txtLicencia = new global::System.Windows.Forms.TextBox();
			this.btnCancelar = new global::System.Windows.Forms.Button();
			this.btnAplicar = new global::System.Windows.Forms.Button();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.Panel2.SuspendLayout();
			base.SuspendLayout();
			this.txtLicencia.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtLicencia.Location = new global::System.Drawing.Point(34, 38);
			this.txtLicencia.Multiline = true;
			this.txtLicencia.Name = "txtLicencia";
			this.txtLicencia.Size = new global::System.Drawing.Size(513, 322);
			this.txtLicencia.TabIndex = 0;
			this.btnCancelar.BackColor = global::System.Drawing.Color.Red;
			this.btnCancelar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnCancelar.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.btnCancelar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnCancelar.ForeColor = global::System.Drawing.Color.White;
			this.btnCancelar.Location = new global::System.Drawing.Point(137, 0);
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.Size = new global::System.Drawing.Size(137, 57);
			this.btnCancelar.TabIndex = 144;
			this.btnCancelar.TabStop = false;
			this.btnCancelar.Text = "Cancelar";
			this.btnCancelar.UseVisualStyleBackColor = false;
			this.btnAplicar.BackColor = global::System.Drawing.Color.Green;
			this.btnAplicar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnAplicar.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.btnAplicar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnAplicar.ForeColor = global::System.Drawing.Color.White;
			this.btnAplicar.Location = new global::System.Drawing.Point(0, 0);
			this.btnAplicar.Name = "btnAplicar";
			this.btnAplicar.Size = new global::System.Drawing.Size(137, 57);
			this.btnAplicar.TabIndex = 143;
			this.btnAplicar.TabStop = false;
			this.btnAplicar.Text = "Aplicar";
			this.btnAplicar.UseVisualStyleBackColor = false;
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(2, 2, 2, 2);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(559, 26);
			this.Panel1.TabIndex = 145;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(6, 7);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(239, 13);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Ingresa las llaves para Activar el sistema";
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(529, 0);
			this.PictureBox1.Margin = new global::System.Windows.Forms.Padding(2, 2, 2, 2);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(30, 26);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 127;
			this.PictureBox1.TabStop = false;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.Location = new global::System.Drawing.Point(18, 38);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(14, 13);
			this.Label2.TabIndex = 146;
			this.Label2.Text = "1";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.Location = new global::System.Drawing.Point(18, 52);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(14, 13);
			this.Label3.TabIndex = 147;
			this.Label3.Text = "2";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.Location = new global::System.Drawing.Point(18, 79);
			this.Label4.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(14, 13);
			this.Label4.TabIndex = 149;
			this.Label4.Text = "4";
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.Location = new global::System.Drawing.Point(18, 66);
			this.Label5.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(14, 13);
			this.Label5.TabIndex = 148;
			this.Label5.Text = "3";
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.Location = new global::System.Drawing.Point(18, 132);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(14, 13);
			this.Label6.TabIndex = 153;
			this.Label6.Text = "8";
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.Location = new global::System.Drawing.Point(18, 119);
			this.Label7.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(14, 13);
			this.Label7.TabIndex = 152;
			this.Label7.Text = "7";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.Location = new global::System.Drawing.Point(18, 105);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(14, 13);
			this.Label8.TabIndex = 151;
			this.Label8.Text = "6";
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.Location = new global::System.Drawing.Point(18, 92);
			this.Label9.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(14, 13);
			this.Label9.TabIndex = 150;
			this.Label9.Text = "5";
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.Location = new global::System.Drawing.Point(12, 237);
			this.Label10.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(21, 13);
			this.Label10.TabIndex = 161;
			this.Label10.Text = "16";
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.Location = new global::System.Drawing.Point(12, 224);
			this.Label11.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(21, 13);
			this.Label11.TabIndex = 160;
			this.Label11.Text = "15";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.Location = new global::System.Drawing.Point(12, 210);
			this.Label12.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(21, 13);
			this.Label12.TabIndex = 159;
			this.Label12.Text = "14";
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.Location = new global::System.Drawing.Point(12, 197);
			this.Label13.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(21, 13);
			this.Label13.TabIndex = 158;
			this.Label13.Text = "13";
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label14.Location = new global::System.Drawing.Point(12, 184);
			this.Label14.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(21, 13);
			this.Label14.TabIndex = 157;
			this.Label14.Text = "12";
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label15.Location = new global::System.Drawing.Point(12, 171);
			this.Label15.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(21, 13);
			this.Label15.TabIndex = 156;
			this.Label15.Text = "11";
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label16.Location = new global::System.Drawing.Point(12, 159);
			this.Label16.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(21, 13);
			this.Label16.TabIndex = 155;
			this.Label16.Text = "10";
			this.Label17.AutoSize = true;
			this.Label17.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label17.Location = new global::System.Drawing.Point(18, 145);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(14, 13);
			this.Label17.TabIndex = 154;
			this.Label17.Text = "9";
			this.Label18.AutoSize = true;
			this.Label18.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label18.Location = new global::System.Drawing.Point(12, 329);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(21, 13);
			this.Label18.TabIndex = 168;
			this.Label18.Text = "23";
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.Location = new global::System.Drawing.Point(12, 315);
			this.Label19.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(21, 13);
			this.Label19.TabIndex = 167;
			this.Label19.Text = "22";
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label20.Location = new global::System.Drawing.Point(12, 302);
			this.Label20.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label20.Name = "Label20";
			this.Label20.Size = new global::System.Drawing.Size(21, 13);
			this.Label20.TabIndex = 166;
			this.Label20.Text = "21";
			this.Label21.AutoSize = true;
			this.Label21.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label21.Location = new global::System.Drawing.Point(12, 288);
			this.Label21.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label21.Name = "Label21";
			this.Label21.Size = new global::System.Drawing.Size(21, 13);
			this.Label21.TabIndex = 165;
			this.Label21.Text = "20";
			this.Label22.AutoSize = true;
			this.Label22.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label22.Location = new global::System.Drawing.Point(12, 276);
			this.Label22.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label22.Name = "Label22";
			this.Label22.Size = new global::System.Drawing.Size(21, 13);
			this.Label22.TabIndex = 164;
			this.Label22.Text = "19";
			this.Label23.AutoSize = true;
			this.Label23.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label23.Location = new global::System.Drawing.Point(12, 262);
			this.Label23.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label23.Name = "Label23";
			this.Label23.Size = new global::System.Drawing.Size(21, 13);
			this.Label23.TabIndex = 163;
			this.Label23.Text = "18";
			this.Label24.AutoSize = true;
			this.Label24.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label24.Location = new global::System.Drawing.Point(12, 250);
			this.Label24.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label24.Name = "Label24";
			this.Label24.Size = new global::System.Drawing.Size(21, 13);
			this.Label24.TabIndex = 162;
			this.Label24.Text = "17";
			this.Label25.AutoSize = true;
			this.Label25.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label25.Location = new global::System.Drawing.Point(12, 342);
			this.Label25.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label25.Name = "Label25";
			this.Label25.Size = new global::System.Drawing.Size(21, 13);
			this.Label25.TabIndex = 169;
			this.Label25.Text = "24";
			this.Panel2.Controls.Add(this.Label26);
			this.Panel2.Controls.Add(this.btnCancelar);
			this.Panel2.Controls.Add(this.btnAplicar);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel2.Location = new global::System.Drawing.Point(0, 366);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(559, 57);
			this.Panel2.TabIndex = 170;
			this.Label26.Anchor = global::System.Windows.Forms.AnchorStyles.Right;
			this.Label26.AutoSize = true;
			this.Label26.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label26.ForeColor = global::System.Drawing.Color.Red;
			this.Label26.Location = new global::System.Drawing.Point(403, 22);
			this.Label26.Name = "Label26";
			this.Label26.Size = new global::System.Drawing.Size(153, 26);
			this.Label26.TabIndex = 145;
			this.Label26.Text = "*Solicita las llaves a tu\r\n adminisrador del sistema.\r\n";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			base.ClientSize = new global::System.Drawing.Size(559, 423);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Label25);
			base.Controls.Add(this.Label18);
			base.Controls.Add(this.Label19);
			base.Controls.Add(this.Label20);
			base.Controls.Add(this.Label21);
			base.Controls.Add(this.Label22);
			base.Controls.Add(this.Label23);
			base.Controls.Add(this.Label24);
			base.Controls.Add(this.Label10);
			base.Controls.Add(this.Label11);
			base.Controls.Add(this.Label12);
			base.Controls.Add(this.Label13);
			base.Controls.Add(this.Label14);
			base.Controls.Add(this.Label15);
			base.Controls.Add(this.Label16);
			base.Controls.Add(this.Label17);
			base.Controls.Add(this.Label6);
			base.Controls.Add(this.Label7);
			base.Controls.Add(this.Label8);
			base.Controls.Add(this.Label9);
			base.Controls.Add(this.Label4);
			base.Controls.Add(this.Label5);
			base.Controls.Add(this.Label3);
			base.Controls.Add(this.Label2);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.txtLicencia);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "frmLicencia";
			base.ShowIcon = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Agregar Licencia";
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.Panel2.ResumeLayout(false);
			this.Panel2.PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040004BF RID: 1215
		private global::System.ComponentModel.IContainer components;
	}
}
