namespace ModuloAdicional
{
	// Token: 0x0200001C RID: 28
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class FrmModificarTicket : global::System.Windows.Forms.Form
	{
		// Token: 0x06000B0E RID: 2830 RVA: 0x000BAB0C File Offset: 0x000B8D0C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000B0F RID: 2831 RVA: 0x000BAB5C File Offset: 0x000B8D5C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.FrmModificarTicket));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.lblidturno_jc = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.cmbAnio = new global::System.Windows.Forms.ComboBox();
			this.dateFechaFin = new global::System.Windows.Forms.DateTimePicker();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.dateFechaIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.txtBuscarFolio = new global::System.Windows.Forms.TextBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.txtSerie = new global::System.Windows.Forms.TextBox();
			this.lblSerie = new global::System.Windows.Forms.Label();
			this.lblEmpresa = new global::System.Windows.Forms.Label();
			this.ComboBoxIdEmpresa = new global::System.Windows.Forms.ComboBox();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.Panel13 = new global::System.Windows.Forms.Panel();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.BtnVerTickets = new global::System.Windows.Forms.Button();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.Panel11 = new global::System.Windows.Forms.Panel();
			this.lblTotalDeFilasDGV = new global::System.Windows.Forms.Label();
			this.lblNuevoFOlioPropina = new global::System.Windows.Forms.Label();
			this.Label50 = new global::System.Windows.Forms.Label();
			this.Panel7 = new global::System.Windows.Forms.Panel();
			this.PanelVariables = new global::System.Windows.Forms.Panel();
			this.lblEfectivoTurno1 = new global::System.Windows.Forms.Label();
			this.dateHoraFin = new global::System.Windows.Forms.DateTimePicker();
			this.dateHoraIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.lblTotalOtrosSinDescuento = new global::System.Windows.Forms.Label();
			this.lblfoliopropinasincuenta = new global::System.Windows.Forms.Label();
			this.lblTotalOtros = new global::System.Windows.Forms.Label();
			this.lblContarFilasEliminar = new global::System.Windows.Forms.Label();
			this.lblditurnoformadepago = new global::System.Windows.Forms.Label();
			this.lblTotalBebidasDesc = new global::System.Windows.Forms.Label();
			this.lblTotalAlimentos = new global::System.Windows.Forms.Label();
			this.lblFolioIdentity = new global::System.Windows.Forms.Label();
			this.lblTotalAlimentosDescuento = new global::System.Windows.Forms.Label();
			this.lblTotalBebidas = new global::System.Windows.Forms.Label();
			this.lblFechadelProducto = new global::System.Windows.Forms.Label();
			this.lblidFoliodet = new global::System.Windows.Forms.Label();
			this.lblContarFilas = new global::System.Windows.Forms.Label();
			this.chkRenumerar = new global::System.Windows.Forms.CheckBox();
			this.lblIdEstacion = new global::System.Windows.Forms.Label();
			this.lblRefolear = new global::System.Windows.Forms.Label();
			this.lblMesero = new global::System.Windows.Forms.Label();
			this.BtnVolver = new global::System.Windows.Forms.PictureBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.lblFolioPagoPropina = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.txtTotal = new global::System.Windows.Forms.TextBox();
			this.txtSubtotal = new global::System.Windows.Forms.TextBox();
			this.txtPropina = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txtotros = new global::System.Windows.Forms.TextBox();
			this.txtDescuento = new global::System.Windows.Forms.TextBox();
			this.txtvales = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.lblPropina = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txtTarjeta = new global::System.Windows.Forms.TextBox();
			this.lblOtros = new global::System.Windows.Forms.Label();
			this.txtEfectivo = new global::System.Windows.Forms.TextBox();
			this.lblVales = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.lbltarjeta = new global::System.Windows.Forms.Label();
			this.lblefectivo = new global::System.Windows.Forms.Label();
			this.Panel4 = new global::System.Windows.Forms.Panel();
			this.btnEliminarProducto = new global::System.Windows.Forms.PictureBox();
			this.BtnAgregarProducto = new global::System.Windows.Forms.PictureBox();
			this.Panel16 = new global::System.Windows.Forms.Panel();
			this.DgvTicketsPeriodo = new global::System.Windows.Forms.DataGridView();
			this.Panel14 = new global::System.Windows.Forms.Panel();
			this.PanelDGW = new global::System.Windows.Forms.Panel();
			this.PanelBuscarProducto = new global::System.Windows.Forms.Panel();
			this.Panel17 = new global::System.Windows.Forms.Panel();
			this.dgwProductos = new global::System.Windows.Forms.DataGridView();
			this.Panel5 = new global::System.Windows.Forms.Panel();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.Panel6 = new global::System.Windows.Forms.Panel();
			this.lblContadorJC = new global::System.Windows.Forms.Label();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.txtBuscarProducto = new global::System.Windows.Forms.TextBox();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.PanelFormasdePago = new global::System.Windows.Forms.Panel();
			this.Panel10 = new global::System.Windows.Forms.Panel();
			this.txtFormasPago = new global::System.Windows.Forms.TextBox();
			this.txtTotaldelTicket = new global::System.Windows.Forms.TextBox();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.TxtPropinaEnOtros = new global::System.Windows.Forms.TextBox();
			this.txtPropinaEnVales = new global::System.Windows.Forms.TextBox();
			this.txtPropinaEnTarjeta = new global::System.Windows.Forms.TextBox();
			this.TxtPropinaEnEfectivo = new global::System.Windows.Forms.TextBox();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.txtPagoPropina = new global::System.Windows.Forms.TextBox();
			this.txtPagoOtros = new global::System.Windows.Forms.TextBox();
			this.txtPagoVales = new global::System.Windows.Forms.TextBox();
			this.txtPagoTarjeta = new global::System.Windows.Forms.TextBox();
			this.txtPagoEfectivo = new global::System.Windows.Forms.TextBox();
			this.Panel9 = new global::System.Windows.Forms.Panel();
			this.labeltotalformasdepago = new global::System.Windows.Forms.Label();
			this.lbltotalpropinasvalidacion = new global::System.Windows.Forms.Label();
			this.lbltotalvalidacion = new global::System.Windows.Forms.Label();
			this.PictureBox5 = new global::System.Windows.Forms.PictureBox();
			this.Panel8 = new global::System.Windows.Forms.Panel();
			this.lblTotalFormapagoconpropina = new global::System.Windows.Forms.Label();
			this.lbldiefectivotarjeta = new global::System.Windows.Forms.Label();
			this.lblidefectivo = new global::System.Windows.Forms.Label();
			this.lblPropinasSumar = new global::System.Windows.Forms.Label();
			this.lblOtrosSUmar = new global::System.Windows.Forms.Label();
			this.lblValesSumar = new global::System.Windows.Forms.Label();
			this.lblTarjetasumar = new global::System.Windows.Forms.Label();
			this.lblEfectivoSumar = new global::System.Windows.Forms.Label();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.dgvNotas = new global::System.Windows.Forms.DataGridView();
			this.Panel12 = new global::System.Windows.Forms.Panel();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.btnCambiarFormadePago = new global::System.Windows.Forms.Button();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.lblFolio = new global::System.Windows.Forms.Label();
			this.txtFechadelTicket = new global::System.Windows.Forms.TextBox();
			this.TxtFacturado = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txtPersonas = new global::System.Windows.Forms.TextBox();
			this.lblPersonas = new global::System.Windows.Forms.Label();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.Panel1.SuspendLayout();
			this.PanelVariables.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.BtnVolver).BeginInit();
			this.Panel2.SuspendLayout();
			this.Panel4.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnEliminarProducto).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnAgregarProducto).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DgvTicketsPeriodo).BeginInit();
			this.Panel14.SuspendLayout();
			this.PanelDGW.SuspendLayout();
			this.PanelBuscarProducto.SuspendLayout();
			this.Panel17.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.dgwProductos).BeginInit();
			this.Panel5.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			this.Panel6.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			this.PanelFormasdePago.SuspendLayout();
			this.Panel10.SuspendLayout();
			this.Panel9.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).BeginInit();
			this.Panel8.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).BeginInit();
			this.Panel12.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			base.SuspendLayout();
			this.GroupBox1.AutoSizeMode = global::System.Windows.Forms.AutoSizeMode.GrowAndShrink;
			this.GroupBox1.Controls.Add(this.lblidturno_jc);
			this.GroupBox1.Controls.Add(this.Label18);
			this.GroupBox1.Controls.Add(this.ComboBox1);
			this.GroupBox1.Controls.Add(this.Label17);
			this.GroupBox1.Controls.Add(this.cmbAnio);
			this.GroupBox1.Controls.Add(this.dateFechaFin);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.dateFechaIni);
			this.GroupBox1.Controls.Add(this.Label6);
			this.GroupBox1.Controls.Add(this.GroupBox2);
			this.GroupBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox1.Location = new global::System.Drawing.Point(4, 0);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(987, 207);
			this.GroupBox1.TabIndex = 91;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Periodo:";
			this.lblidturno_jc.AutoSize = true;
			this.lblidturno_jc.Location = new global::System.Drawing.Point(464, 138);
			this.lblidturno_jc.Name = "lblidturno_jc";
			this.lblidturno_jc.Size = new global::System.Drawing.Size(128, 25);
			this.lblidturno_jc.TabIndex = 162;
			this.lblidturno_jc.Text = "lblidturno_jc";
			this.lblidturno_jc.Visible = false;
			this.Label18.AutoSize = true;
			this.Label18.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label18.Location = new global::System.Drawing.Point(294, 39);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(59, 25);
			this.Label18.TabIndex = 97;
			this.Label18.Text = "Mes:";
			this.ComboBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(366, 31);
			this.ComboBox1.Margin = new global::System.Windows.Forms.Padding(6);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(234, 37);
			this.ComboBox1.TabIndex = 96;
			this.Label17.AutoSize = true;
			this.Label17.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label17.Location = new global::System.Drawing.Point(11, 39);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(62, 25);
			this.Label17.TabIndex = 95;
			this.Label17.Text = "Año: ";
			this.cmbAnio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbAnio.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAnio.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbAnio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.cmbAnio.FormattingEnabled = true;
			this.cmbAnio.Location = new global::System.Drawing.Point(87, 31);
			this.cmbAnio.Margin = new global::System.Windows.Forms.Padding(6);
			this.cmbAnio.Name = "cmbAnio";
			this.cmbAnio.Size = new global::System.Drawing.Size(194, 37);
			this.cmbAnio.Sorted = true;
			this.cmbAnio.TabIndex = 94;
			this.dateFechaFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaFin.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.dateFechaFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Custom;
			this.dateFechaFin.Location = new global::System.Drawing.Point(190, 137);
			this.dateFechaFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaFin.Name = "dateFechaFin";
			this.dateFechaFin.Size = new global::System.Drawing.Size(196, 35);
			this.dateFechaFin.TabIndex = 91;
			this.Label1.AutoSize = true;
			this.Label1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(22, 137);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(143, 25);
			this.Label1.TabIndex = 93;
			this.Label1.Text = "Fecha FInal : ";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dateFechaIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaIni.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.dateFechaIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.dateFechaIni.Location = new global::System.Drawing.Point(190, 87);
			this.dateFechaIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaIni.MaxDate = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.dateFechaIni.MinDate = new global::System.DateTime(2017, 1, 1, 0, 0, 0, 0);
			this.dateFechaIni.Name = "dateFechaIni";
			this.dateFechaIni.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dateFechaIni.Size = new global::System.Drawing.Size(196, 35);
			this.dateFechaIni.TabIndex = 90;
			this.dateFechaIni.Value = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.Label6.AutoSize = true;
			this.Label6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label6.Location = new global::System.Drawing.Point(14, 87);
			this.Label6.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(151, 25);
			this.Label6.TabIndex = 92;
			this.Label6.Text = "Fecha Inicial : ";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox2.Controls.Add(this.Label27);
			this.GroupBox2.Controls.Add(this.txtBuscarFolio);
			this.GroupBox2.Controls.Add(this.PictureBox1);
			this.GroupBox2.Controls.Add(this.txtSerie);
			this.GroupBox2.Controls.Add(this.lblSerie);
			this.GroupBox2.Controls.Add(this.lblEmpresa);
			this.GroupBox2.Controls.Add(this.ComboBoxIdEmpresa);
			this.GroupBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox2.Location = new global::System.Drawing.Point(609, 1);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(378, 206);
			this.GroupBox2.TabIndex = 161;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Buscar ticket";
			this.Label27.AutoSize = true;
			this.Label27.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label27.Location = new global::System.Drawing.Point(107, 118);
			this.Label27.Name = "Label27";
			this.Label27.Size = new global::System.Drawing.Size(65, 25);
			this.Label27.TabIndex = 155;
			this.Label27.Text = "Folio:";
			this.txtBuscarFolio.BackColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.txtBuscarFolio.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtBuscarFolio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBuscarFolio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtBuscarFolio.Location = new global::System.Drawing.Point(107, 153);
			this.txtBuscarFolio.Name = "txtBuscarFolio";
			this.txtBuscarFolio.Size = new global::System.Drawing.Size(196, 35);
			this.txtBuscarFolio.TabIndex = 152;
			this.txtBuscarFolio.Text = "000000000";
			this.PictureBox1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.InitialImage = null;
			this.PictureBox1.Location = new global::System.Drawing.Point(310, 148);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(45, 45);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 154;
			this.PictureBox1.TabStop = false;
			this.txtSerie.BackColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.txtSerie.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtSerie.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtSerie.Location = new global::System.Drawing.Point(19, 153);
			this.txtSerie.Name = "txtSerie";
			this.txtSerie.Size = new global::System.Drawing.Size(80, 35);
			this.txtSerie.TabIndex = 149;
			this.lblSerie.AutoSize = true;
			this.lblSerie.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblSerie.Location = new global::System.Drawing.Point(19, 118);
			this.lblSerie.Name = "lblSerie";
			this.lblSerie.Size = new global::System.Drawing.Size(68, 25);
			this.lblSerie.TabIndex = 150;
			this.lblSerie.Text = "Serie:";
			this.lblEmpresa.AutoSize = true;
			this.lblEmpresa.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblEmpresa.Location = new global::System.Drawing.Point(19, 34);
			this.lblEmpresa.Name = "lblEmpresa";
			this.lblEmpresa.Size = new global::System.Drawing.Size(103, 25);
			this.lblEmpresa.TabIndex = 148;
			this.lblEmpresa.Text = "Empresa:";
			this.ComboBoxIdEmpresa.BackColor = global::System.Drawing.SystemColors.Window;
			this.ComboBoxIdEmpresa.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBoxIdEmpresa.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBoxIdEmpresa.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.ComboBoxIdEmpresa.ForeColor = global::System.Drawing.SystemColors.Window;
			this.ComboBoxIdEmpresa.FormattingEnabled = true;
			this.ComboBoxIdEmpresa.Location = new global::System.Drawing.Point(20, 66);
			this.ComboBoxIdEmpresa.Name = "ComboBoxIdEmpresa";
			this.ComboBoxIdEmpresa.Size = new global::System.Drawing.Size(250, 37);
			this.ComboBoxIdEmpresa.TabIndex = 147;
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.Label32);
			this.Panel1.Controls.Add(this.Panel13);
			this.Panel1.Controls.Add(this.Label31);
			this.Panel1.Controls.Add(this.Panel3);
			this.Panel1.Controls.Add(this.BtnVerTickets);
			this.Panel1.Controls.Add(this.Label30);
			this.Panel1.Controls.Add(this.Panel11);
			this.Panel1.Controls.Add(this.lblTotalDeFilasDGV);
			this.Panel1.Controls.Add(this.lblNuevoFOlioPropina);
			this.Panel1.Controls.Add(this.Label50);
			this.Panel1.Controls.Add(this.Panel7);
			this.Panel1.Controls.Add(this.PanelVariables);
			this.Panel1.Controls.Add(this.BtnVolver);
			this.Panel1.Controls.Add(this.Label19);
			this.Panel1.Controls.Add(this.lblFolioPagoPropina);
			this.Panel1.Controls.Add(this.GroupBox1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(2622, 215);
			this.Panel1.TabIndex = 92;
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label32.Location = new global::System.Drawing.Point(1516, 129);
			this.Label32.Name = "Label32";
			this.Label32.Size = new global::System.Drawing.Size(282, 24);
			this.Label32.TabIndex = 178;
			this.Label32.Text = "Cuentas en Efectivo y Tarjeta";
			this.Panel13.BackColor = global::System.Drawing.Color.Black;
			this.Panel13.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel13.Location = new global::System.Drawing.Point(1438, 131);
			this.Panel13.Name = "Panel13";
			this.Panel13.Size = new global::System.Drawing.Size(60, 20);
			this.Panel13.TabIndex = 177;
			this.Label31.AutoSize = true;
			this.Label31.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label31.Location = new global::System.Drawing.Point(1516, 99);
			this.Label31.Name = "Label31";
			this.Label31.Size = new global::System.Drawing.Size(196, 24);
			this.Label31.TabIndex = 176;
			this.Label31.Text = "Cuentas en Efectivo";
			this.Panel3.BackColor = global::System.Drawing.Color.Green;
			this.Panel3.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel3.Location = new global::System.Drawing.Point(1438, 101);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(60, 20);
			this.Panel3.TabIndex = 175;
			this.BtnVerTickets.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.BtnVerTickets.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.BtnVerTickets.FlatAppearance.BorderSize = 2;
			this.BtnVerTickets.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.BtnVerTickets.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 13.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.BtnVerTickets.ForeColor = global::System.Drawing.Color.White;
			this.BtnVerTickets.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnVerTickets.Image");
			this.BtnVerTickets.Location = new global::System.Drawing.Point(1000, 99);
			this.BtnVerTickets.Name = "BtnVerTickets";
			this.BtnVerTickets.Size = new global::System.Drawing.Size(312, 99);
			this.BtnVerTickets.TabIndex = 99;
			this.BtnVerTickets.Text = "Ver Tickets";
			this.BtnVerTickets.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.BtnVerTickets.UseVisualStyleBackColor = false;
			this.Label30.AutoSize = true;
			this.Label30.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label30.Location = new global::System.Drawing.Point(1516, 43);
			this.Label30.Name = "Label30";
			this.Label30.Size = new global::System.Drawing.Size(251, 48);
			this.Label30.TabIndex = 174;
			this.Label30.Text = "Productos con Descuento\r\no Precio $ 0";
			this.Panel11.BackColor = global::System.Drawing.Color.LightBlue;
			this.Panel11.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel11.Location = new global::System.Drawing.Point(1438, 43);
			this.Panel11.Name = "Panel11";
			this.Panel11.Size = new global::System.Drawing.Size(60, 20);
			this.Panel11.TabIndex = 173;
			this.lblTotalDeFilasDGV.AutoSize = true;
			this.lblTotalDeFilasDGV.Location = new global::System.Drawing.Point(2256, 146);
			this.lblTotalDeFilasDGV.Name = "lblTotalDeFilasDGV";
			this.lblTotalDeFilasDGV.Size = new global::System.Drawing.Size(200, 25);
			this.lblTotalDeFilasDGV.TabIndex = 172;
			this.lblTotalDeFilasDGV.Text = "lblTotalDeFilasDGV";
			this.lblTotalDeFilasDGV.Visible = false;
			this.lblNuevoFOlioPropina.AutoSize = true;
			this.lblNuevoFOlioPropina.Location = new global::System.Drawing.Point(2297, 199);
			this.lblNuevoFOlioPropina.Name = "lblNuevoFOlioPropina";
			this.lblNuevoFOlioPropina.Size = new global::System.Drawing.Size(89, 25);
			this.lblNuevoFOlioPropina.TabIndex = 160;
			this.lblNuevoFOlioPropina.Text = "Label27";
			this.lblNuevoFOlioPropina.Visible = false;
			this.Label50.AutoSize = true;
			this.Label50.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label50.Location = new global::System.Drawing.Point(1516, 10);
			this.Label50.Name = "Label50";
			this.Label50.Size = new global::System.Drawing.Size(212, 24);
			this.Label50.TabIndex = 170;
			this.Label50.Text = "Productos a modificar";
			this.Panel7.BackColor = global::System.Drawing.Color.Red;
			this.Panel7.BorderStyle = global::System.Windows.Forms.BorderStyle.Fixed3D;
			this.Panel7.Location = new global::System.Drawing.Point(1438, 14);
			this.Panel7.Name = "Panel7";
			this.Panel7.Size = new global::System.Drawing.Size(60, 20);
			this.Panel7.TabIndex = 169;
			this.PanelVariables.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.PanelVariables.Controls.Add(this.lblEfectivoTurno1);
			this.PanelVariables.Controls.Add(this.dateHoraFin);
			this.PanelVariables.Controls.Add(this.dateHoraIni);
			this.PanelVariables.Controls.Add(this.Label10);
			this.PanelVariables.Controls.Add(this.Label11);
			this.PanelVariables.Controls.Add(this.lblTotalOtrosSinDescuento);
			this.PanelVariables.Controls.Add(this.lblfoliopropinasincuenta);
			this.PanelVariables.Controls.Add(this.lblTotalOtros);
			this.PanelVariables.Controls.Add(this.lblContarFilasEliminar);
			this.PanelVariables.Controls.Add(this.lblditurnoformadepago);
			this.PanelVariables.Controls.Add(this.lblTotalBebidasDesc);
			this.PanelVariables.Controls.Add(this.lblTotalAlimentos);
			this.PanelVariables.Controls.Add(this.lblFolioIdentity);
			this.PanelVariables.Controls.Add(this.lblTotalAlimentosDescuento);
			this.PanelVariables.Controls.Add(this.lblTotalBebidas);
			this.PanelVariables.Controls.Add(this.lblFechadelProducto);
			this.PanelVariables.Controls.Add(this.lblidFoliodet);
			this.PanelVariables.Controls.Add(this.lblContarFilas);
			this.PanelVariables.Controls.Add(this.chkRenumerar);
			this.PanelVariables.Controls.Add(this.lblIdEstacion);
			this.PanelVariables.Controls.Add(this.lblRefolear);
			this.PanelVariables.Controls.Add(this.lblMesero);
			this.PanelVariables.Location = new global::System.Drawing.Point(1908, 18);
			this.PanelVariables.Name = "PanelVariables";
			this.PanelVariables.Size = new global::System.Drawing.Size(611, 217);
			this.PanelVariables.TabIndex = 163;
			this.lblEfectivoTurno1.AutoSize = true;
			this.lblEfectivoTurno1.Location = new global::System.Drawing.Point(489, 73);
			this.lblEfectivoTurno1.Name = "lblEfectivoTurno1";
			this.lblEfectivoTurno1.Size = new global::System.Drawing.Size(167, 25);
			this.lblEfectivoTurno1.TabIndex = 91;
			this.lblEfectivoTurno1.Text = "lblEfectivoTurno";
			this.lblEfectivoTurno1.Visible = false;
			this.dateHoraFin.Enabled = false;
			this.dateHoraFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraFin.Location = new global::System.Drawing.Point(424, 249);
			this.dateHoraFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraFin.Name = "dateHoraFin";
			this.dateHoraFin.ShowUpDown = true;
			this.dateHoraFin.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraFin.TabIndex = 86;
			this.dateHoraFin.TabStop = false;
			this.dateHoraFin.Value = new global::System.DateTime(2022, 6, 15, 5, 59, 59, 0);
			this.dateHoraIni.Enabled = false;
			this.dateHoraIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraIni.Location = new global::System.Drawing.Point(424, 199);
			this.dateHoraIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraIni.Name = "dateHoraIni";
			this.dateHoraIni.ShowUpDown = true;
			this.dateHoraIni.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraIni.TabIndex = 84;
			this.dateHoraIni.TabStop = false;
			this.dateHoraIni.Value = new global::System.DateTime(2022, 6, 15, 6, 0, 0, 0);
			this.Label10.AutoSize = true;
			this.Label10.Location = new global::System.Drawing.Point(30, 247);
			this.Label10.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(143, 25);
			this.Label10.TabIndex = 88;
			this.Label10.Text = "Fecha FInal : ";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label11.AutoSize = true;
			this.Label11.Location = new global::System.Drawing.Point(22, 197);
			this.Label11.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(151, 25);
			this.Label11.TabIndex = 87;
			this.Label11.Text = "Fecha Inicial : ";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lblTotalOtrosSinDescuento.AutoSize = true;
			this.lblTotalOtrosSinDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalOtrosSinDescuento.Location = new global::System.Drawing.Point(205, 73);
			this.lblTotalOtrosSinDescuento.Name = "lblTotalOtrosSinDescuento";
			this.lblTotalOtrosSinDescuento.Size = new global::System.Drawing.Size(177, 17);
			this.lblTotalOtrosSinDescuento.TabIndex = 47;
			this.lblTotalOtrosSinDescuento.Text = "lblTotalOtrosSinDescuento";
			this.lblTotalOtrosSinDescuento.Visible = false;
			this.lblfoliopropinasincuenta.AutoSize = true;
			this.lblfoliopropinasincuenta.Location = new global::System.Drawing.Point(9, 52);
			this.lblfoliopropinasincuenta.Name = "lblfoliopropinasincuenta";
			this.lblfoliopropinasincuenta.Size = new global::System.Drawing.Size(89, 25);
			this.lblfoliopropinasincuenta.TabIndex = 168;
			this.lblfoliopropinasincuenta.Text = "Label27";
			this.lblfoliopropinasincuenta.Visible = false;
			this.lblTotalOtros.AutoSize = true;
			this.lblTotalOtros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalOtros.Location = new global::System.Drawing.Point(237, 36);
			this.lblTotalOtros.Name = "lblTotalOtros";
			this.lblTotalOtros.Size = new global::System.Drawing.Size(89, 17);
			this.lblTotalOtros.TabIndex = 22;
			this.lblTotalOtros.Text = "lblTotalOtros";
			this.lblTotalOtros.Visible = false;
			this.lblContarFilasEliminar.AutoSize = true;
			this.lblContarFilasEliminar.Location = new global::System.Drawing.Point(440, 20);
			this.lblContarFilasEliminar.Name = "lblContarFilasEliminar";
			this.lblContarFilasEliminar.Size = new global::System.Drawing.Size(89, 25);
			this.lblContarFilasEliminar.TabIndex = 171;
			this.lblContarFilasEliminar.Text = "Label30";
			this.lblContarFilasEliminar.Visible = false;
			this.lblditurnoformadepago.AutoSize = true;
			this.lblditurnoformadepago.Location = new global::System.Drawing.Point(9, 56);
			this.lblditurnoformadepago.Name = "lblditurnoformadepago";
			this.lblditurnoformadepago.Size = new global::System.Drawing.Size(89, 25);
			this.lblditurnoformadepago.TabIndex = 167;
			this.lblditurnoformadepago.Text = "Label27";
			this.lblditurnoformadepago.Visible = false;
			this.lblTotalBebidasDesc.AutoSize = true;
			this.lblTotalBebidasDesc.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalBebidasDesc.Location = new global::System.Drawing.Point(13, 91);
			this.lblTotalBebidasDesc.Name = "lblTotalBebidasDesc";
			this.lblTotalBebidasDesc.Size = new global::System.Drawing.Size(137, 17);
			this.lblTotalBebidasDesc.TabIndex = 46;
			this.lblTotalBebidasDesc.Text = "lblTotalBebidasDesc";
			this.lblTotalBebidasDesc.Visible = false;
			this.lblTotalAlimentos.AutoSize = true;
			this.lblTotalAlimentos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalAlimentos.Location = new global::System.Drawing.Point(13, 34);
			this.lblTotalAlimentos.Name = "lblTotalAlimentos";
			this.lblTotalAlimentos.Size = new global::System.Drawing.Size(115, 17);
			this.lblTotalAlimentos.TabIndex = 20;
			this.lblTotalAlimentos.Text = "lblTotalAlimentos";
			this.lblTotalAlimentos.Visible = false;
			this.lblFolioIdentity.AutoSize = true;
			this.lblFolioIdentity.Location = new global::System.Drawing.Point(-22, 2);
			this.lblFolioIdentity.Name = "lblFolioIdentity";
			this.lblFolioIdentity.Size = new global::System.Drawing.Size(150, 25);
			this.lblFolioIdentity.TabIndex = 165;
			this.lblFolioIdentity.Text = "lblFolioIdentity";
			this.lblFolioIdentity.Visible = false;
			this.lblTotalAlimentosDescuento.AutoSize = true;
			this.lblTotalAlimentosDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalAlimentosDescuento.Location = new global::System.Drawing.Point(13, 69);
			this.lblTotalAlimentosDescuento.Name = "lblTotalAlimentosDescuento";
			this.lblTotalAlimentosDescuento.Size = new global::System.Drawing.Size(183, 17);
			this.lblTotalAlimentosDescuento.TabIndex = 45;
			this.lblTotalAlimentosDescuento.Text = "lblTotalAlimentosDescuento";
			this.lblTotalAlimentosDescuento.Visible = false;
			this.lblTotalBebidas.AutoSize = true;
			this.lblTotalBebidas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTotalBebidas.Location = new global::System.Drawing.Point(133, 36);
			this.lblTotalBebidas.Name = "lblTotalBebidas";
			this.lblTotalBebidas.Size = new global::System.Drawing.Size(105, 17);
			this.lblTotalBebidas.TabIndex = 21;
			this.lblTotalBebidas.Text = "lblTotalBebidas";
			this.lblTotalBebidas.Visible = false;
			this.lblFechadelProducto.AutoSize = true;
			this.lblFechadelProducto.Location = new global::System.Drawing.Point(360, 88);
			this.lblFechadelProducto.Name = "lblFechadelProducto";
			this.lblFechadelProducto.Size = new global::System.Drawing.Size(77, 25);
			this.lblFechadelProducto.TabIndex = 6;
			this.lblFechadelProducto.Text = "Label3";
			this.lblFechadelProducto.Visible = false;
			this.lblidFoliodet.AutoSize = true;
			this.lblidFoliodet.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblidFoliodet.Location = new global::System.Drawing.Point(56, 20);
			this.lblidFoliodet.Name = "lblidFoliodet";
			this.lblidFoliodet.Size = new global::System.Drawing.Size(72, 17);
			this.lblidFoliodet.TabIndex = 18;
			this.lblidFoliodet.Text = "lblFoliodet";
			this.lblidFoliodet.Visible = false;
			this.lblContarFilas.AutoSize = true;
			this.lblContarFilas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblContarFilas.Location = new global::System.Drawing.Point(134, 20);
			this.lblContarFilas.Name = "lblContarFilas";
			this.lblContarFilas.Size = new global::System.Drawing.Size(93, 17);
			this.lblContarFilas.TabIndex = 19;
			this.lblContarFilas.Text = "lblContarFilas";
			this.lblContarFilas.Visible = false;
			this.chkRenumerar.AutoSize = true;
			this.chkRenumerar.Checked = true;
			this.chkRenumerar.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.chkRenumerar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 5f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.chkRenumerar.Location = new global::System.Drawing.Point(258, 83);
			this.chkRenumerar.Name = "chkRenumerar";
			this.chkRenumerar.Size = new global::System.Drawing.Size(111, 27);
			this.chkRenumerar.TabIndex = 1;
			this.chkRenumerar.Text = "Renumerar";
			this.chkRenumerar.UseVisualStyleBackColor = true;
			this.chkRenumerar.Visible = false;
			this.lblIdEstacion.AutoSize = true;
			this.lblIdEstacion.Location = new global::System.Drawing.Point(220, 80);
			this.lblIdEstacion.Name = "lblIdEstacion";
			this.lblIdEstacion.Size = new global::System.Drawing.Size(134, 25);
			this.lblIdEstacion.TabIndex = 4;
			this.lblIdEstacion.Text = "lblIdEstacion";
			this.lblIdEstacion.Visible = false;
			this.lblRefolear.AutoSize = true;
			this.lblRefolear.Location = new global::System.Drawing.Point(200, 96);
			this.lblRefolear.Name = "lblRefolear";
			this.lblRefolear.Size = new global::System.Drawing.Size(132, 25);
			this.lblRefolear.TabIndex = 2;
			this.lblRefolear.Text = "lblrenumerar";
			this.lblRefolear.Visible = false;
			this.lblMesero.AutoSize = true;
			this.lblMesero.Location = new global::System.Drawing.Point(254, 85);
			this.lblMesero.Name = "lblMesero";
			this.lblMesero.Size = new global::System.Drawing.Size(106, 25);
			this.lblMesero.TabIndex = 3;
			this.lblMesero.Text = "lblMesero";
			this.lblMesero.Visible = false;
			this.BtnVolver.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.BtnVolver.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.BtnVolver.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.BtnVolver.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnVolver.Image");
			this.BtnVolver.Location = new global::System.Drawing.Point(2558, 3);
			this.BtnVolver.Name = "BtnVolver";
			this.BtnVolver.Size = new global::System.Drawing.Size(50, 50);
			this.BtnVolver.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.BtnVolver.TabIndex = 7;
			this.BtnVolver.TabStop = false;
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.Red;
			this.Label19.Location = new global::System.Drawing.Point(1003, 18);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(394, 60);
			this.Label19.TabIndex = 160;
			this.Label19.Text = "*Nota\r\nGenera un respaldo antes de aplicar el proceso,\r\nesta accion es irreversible.\r\n";
			this.lblFolioPagoPropina.AutoSize = true;
			this.lblFolioPagoPropina.Location = new global::System.Drawing.Point(2201, 184);
			this.lblFolioPagoPropina.Name = "lblFolioPagoPropina";
			this.lblFolioPagoPropina.Size = new global::System.Drawing.Size(89, 25);
			this.lblFolioPagoPropina.TabIndex = 166;
			this.lblFolioPagoPropina.Text = "Label20";
			this.lblFolioPagoPropina.Visible = false;
			this.Panel2.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel2.Controls.Add(this.txtTotal);
			this.Panel2.Controls.Add(this.txtSubtotal);
			this.Panel2.Controls.Add(this.txtPropina);
			this.Panel2.Controls.Add(this.Label5);
			this.Panel2.Controls.Add(this.txtotros);
			this.Panel2.Controls.Add(this.txtDescuento);
			this.Panel2.Controls.Add(this.txtvales);
			this.Panel2.Controls.Add(this.Label3);
			this.Panel2.Controls.Add(this.Label4);
			this.Panel2.Controls.Add(this.lblPropina);
			this.Panel2.Controls.Add(this.Label2);
			this.Panel2.Controls.Add(this.txtTarjeta);
			this.Panel2.Controls.Add(this.lblOtros);
			this.Panel2.Controls.Add(this.txtEfectivo);
			this.Panel2.Controls.Add(this.lblVales);
			this.Panel2.Controls.Add(this.Label8);
			this.Panel2.Controls.Add(this.lbltarjeta);
			this.Panel2.Controls.Add(this.lblefectivo);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel2.Location = new global::System.Drawing.Point(0, 111);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(1692, 86);
			this.Panel2.TabIndex = 93;
			this.txtTotal.BackColor = global::System.Drawing.Color.White;
			this.txtTotal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtTotal.Location = new global::System.Drawing.Point(898, 47);
			this.txtTotal.Name = "txtTotal";
			this.txtTotal.ReadOnly = true;
			this.txtTotal.Size = new global::System.Drawing.Size(160, 26);
			this.txtTotal.TabIndex = 6;
			this.txtSubtotal.BackColor = global::System.Drawing.Color.White;
			this.txtSubtotal.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtSubtotal.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtSubtotal.Location = new global::System.Drawing.Point(644, 47);
			this.txtSubtotal.Name = "txtSubtotal";
			this.txtSubtotal.ReadOnly = true;
			this.txtSubtotal.Size = new global::System.Drawing.Size(160, 26);
			this.txtSubtotal.TabIndex = 4;
			this.txtPropina.BackColor = global::System.Drawing.Color.White;
			this.txtPropina.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPropina.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtPropina.Location = new global::System.Drawing.Point(1373, 8);
			this.txtPropina.Name = "txtPropina";
			this.txtPropina.ReadOnly = true;
			this.txtPropina.Size = new global::System.Drawing.Size(160, 26);
			this.txtPropina.TabIndex = 38;
			this.Label5.AutoSize = true;
			this.Label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label5.ForeColor = global::System.Drawing.Color.Black;
			this.Label5.Location = new global::System.Drawing.Point(816, 50);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(66, 25);
			this.Label5.TabIndex = 7;
			this.Label5.Text = "Total:";
			this.txtotros.BackColor = global::System.Drawing.Color.White;
			this.txtotros.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtotros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtotros.Location = new global::System.Drawing.Point(1091, 8);
			this.txtotros.Name = "txtotros";
			this.txtotros.ReadOnly = true;
			this.txtotros.Size = new global::System.Drawing.Size(160, 26);
			this.txtotros.TabIndex = 34;
			this.txtDescuento.BackColor = global::System.Drawing.Color.White;
			this.txtDescuento.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtDescuento.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtDescuento.Location = new global::System.Drawing.Point(360, 47);
			this.txtDescuento.Name = "txtDescuento";
			this.txtDescuento.ReadOnly = true;
			this.txtDescuento.Size = new global::System.Drawing.Size(160, 26);
			this.txtDescuento.TabIndex = 0;
			this.txtvales.BackColor = global::System.Drawing.Color.White;
			this.txtvales.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtvales.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtvales.Location = new global::System.Drawing.Point(837, 8);
			this.txtvales.Name = "txtvales";
			this.txtvales.ReadOnly = true;
			this.txtvales.Size = new global::System.Drawing.Size(160, 26);
			this.txtvales.TabIndex = 32;
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label3.Location = new global::System.Drawing.Point(8, 50);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(187, 25);
			this.Label3.TabIndex = 29;
			this.Label3.Text = "Totales del ticket :";
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label4.ForeColor = global::System.Drawing.Color.Black;
			this.Label4.Location = new global::System.Drawing.Point(531, 50);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(97, 25);
			this.Label4.TabIndex = 5;
			this.Label4.Text = "Subtotal:";
			this.lblPropina.AutoSize = true;
			this.lblPropina.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblPropina.Location = new global::System.Drawing.Point(1262, 11);
			this.lblPropina.Name = "lblPropina";
			this.lblPropina.Size = new global::System.Drawing.Size(92, 25);
			this.lblPropina.TabIndex = 37;
			this.lblPropina.Text = "Propina:";
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.Black;
			this.Label2.Location = new global::System.Drawing.Point(224, 50);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(113, 25);
			this.Label2.TabIndex = 1;
			this.Label2.Text = "Desc.Gral:";
			this.txtTarjeta.BackColor = global::System.Drawing.Color.White;
			this.txtTarjeta.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTarjeta.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtTarjeta.Location = new global::System.Drawing.Point(584, 8);
			this.txtTarjeta.Name = "txtTarjeta";
			this.txtTarjeta.ReadOnly = true;
			this.txtTarjeta.Size = new global::System.Drawing.Size(160, 26);
			this.txtTarjeta.TabIndex = 30;
			this.lblOtros.AutoSize = true;
			this.lblOtros.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblOtros.Location = new global::System.Drawing.Point(1007, 11);
			this.lblOtros.Name = "lblOtros";
			this.lblOtros.Size = new global::System.Drawing.Size(70, 25);
			this.lblOtros.TabIndex = 35;
			this.lblOtros.Text = "Otros:";
			this.txtEfectivo.BackColor = global::System.Drawing.Color.White;
			this.txtEfectivo.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtEfectivo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.5f);
			this.txtEfectivo.Location = new global::System.Drawing.Point(314, 8);
			this.txtEfectivo.Name = "txtEfectivo";
			this.txtEfectivo.ReadOnly = true;
			this.txtEfectivo.Size = new global::System.Drawing.Size(160, 26);
			this.txtEfectivo.TabIndex = 28;
			this.lblVales.AutoSize = true;
			this.lblVales.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblVales.Location = new global::System.Drawing.Point(755, 11);
			this.lblVales.Name = "lblVales";
			this.lblVales.Size = new global::System.Drawing.Size(72, 25);
			this.lblVales.TabIndex = 33;
			this.lblVales.Text = "Vales:";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label8.Location = new global::System.Drawing.Point(13, 11);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(182, 25);
			this.Label8.TabIndex = 28;
			this.Label8.Text = "Formas de Pago :";
			this.lbltarjeta.AutoSize = true;
			this.lbltarjeta.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbltarjeta.Location = new global::System.Drawing.Point(484, 11);
			this.lbltarjeta.Name = "lbltarjeta";
			this.lbltarjeta.Size = new global::System.Drawing.Size(85, 25);
			this.lbltarjeta.TabIndex = 31;
			this.lbltarjeta.Text = "Tarjeta:";
			this.lblefectivo.AutoSize = true;
			this.lblefectivo.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblefectivo.Location = new global::System.Drawing.Point(203, 11);
			this.lblefectivo.Name = "lblefectivo";
			this.lblefectivo.Size = new global::System.Drawing.Size(95, 25);
			this.lblefectivo.TabIndex = 29;
			this.lblefectivo.Text = "Efectivo:";
			this.Panel4.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel4.Controls.Add(this.btnEliminarProducto);
			this.Panel4.Controls.Add(this.BtnAgregarProducto);
			this.Panel4.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel4.Location = new global::System.Drawing.Point(0, 197);
			this.Panel4.Name = "Panel4";
			this.Panel4.Size = new global::System.Drawing.Size(1692, 60);
			this.Panel4.TabIndex = 95;
			this.btnEliminarProducto.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.btnEliminarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnEliminarProducto.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.btnEliminarProducto.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnEliminarProducto.Image");
			this.btnEliminarProducto.Location = new global::System.Drawing.Point(57, 0);
			this.btnEliminarProducto.Name = "btnEliminarProducto";
			this.btnEliminarProducto.Size = new global::System.Drawing.Size(57, 60);
			this.btnEliminarProducto.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.btnEliminarProducto.TabIndex = 5;
			this.btnEliminarProducto.TabStop = false;
			this.BtnAgregarProducto.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.BtnAgregarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.BtnAgregarProducto.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.BtnAgregarProducto.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnAgregarProducto.Image");
			this.BtnAgregarProducto.Location = new global::System.Drawing.Point(0, 0);
			this.BtnAgregarProducto.Name = "BtnAgregarProducto";
			this.BtnAgregarProducto.Size = new global::System.Drawing.Size(57, 60);
			this.BtnAgregarProducto.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.BtnAgregarProducto.TabIndex = 4;
			this.BtnAgregarProducto.TabStop = false;
			this.Panel16.BackColor = global::System.Drawing.SystemColors.Control;
			this.Panel16.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel16.Location = new global::System.Drawing.Point(0, 1299);
			this.Panel16.Name = "Panel16";
			this.Panel16.Size = new global::System.Drawing.Size(2622, 28);
			this.Panel16.TabIndex = 96;
			this.DgvTicketsPeriodo.AllowUserToAddRows = false;
			this.DgvTicketsPeriodo.AllowUserToDeleteRows = false;
			this.DgvTicketsPeriodo.AllowUserToResizeColumns = false;
			this.DgvTicketsPeriodo.AllowUserToResizeRows = false;
			this.DgvTicketsPeriodo.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.DgvTicketsPeriodo.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.DgvTicketsPeriodo.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DgvTicketsPeriodo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.DgvTicketsPeriodo.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.DgvTicketsPeriodo.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.DgvTicketsPeriodo.Location = new global::System.Drawing.Point(0, 0);
			this.DgvTicketsPeriodo.Margin = new global::System.Windows.Forms.Padding(4);
			this.DgvTicketsPeriodo.MultiSelect = false;
			this.DgvTicketsPeriodo.Name = "DgvTicketsPeriodo";
			this.DgvTicketsPeriodo.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.DgvTicketsPeriodo.RowHeadersVisible = false;
			this.DgvTicketsPeriodo.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.DgvTicketsPeriodo.RowTemplate.Height = 24;
			this.DgvTicketsPeriodo.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.DgvTicketsPeriodo.Size = new global::System.Drawing.Size(930, 1084);
			this.DgvTicketsPeriodo.TabIndex = 27;
			this.Panel14.Controls.Add(this.DgvTicketsPeriodo);
			this.Panel14.Dock = global::System.Windows.Forms.DockStyle.Left;
			this.Panel14.Location = new global::System.Drawing.Point(0, 215);
			this.Panel14.Name = "Panel14";
			this.Panel14.Size = new global::System.Drawing.Size(930, 1084);
			this.Panel14.TabIndex = 99;
			this.PanelDGW.Controls.Add(this.PanelBuscarProducto);
			this.PanelDGW.Controls.Add(this.PanelFormasdePago);
			this.PanelDGW.Controls.Add(this.dgvNotas);
			this.PanelDGW.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.PanelDGW.Location = new global::System.Drawing.Point(0, 257);
			this.PanelDGW.Name = "PanelDGW";
			this.PanelDGW.Size = new global::System.Drawing.Size(1692, 827);
			this.PanelDGW.TabIndex = 97;
			this.PanelBuscarProducto.Anchor = global::System.Windows.Forms.AnchorStyles.Top;
			this.PanelBuscarProducto.AutoSize = true;
			this.PanelBuscarProducto.BackColor = global::System.Drawing.SystemColors.Control;
			this.PanelBuscarProducto.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.PanelBuscarProducto.Controls.Add(this.Panel17);
			this.PanelBuscarProducto.Controls.Add(this.Panel6);
			this.PanelBuscarProducto.Location = new global::System.Drawing.Point(104, 70);
			this.PanelBuscarProducto.Name = "PanelBuscarProducto";
			this.PanelBuscarProducto.Size = new global::System.Drawing.Size(1485, 687);
			this.PanelBuscarProducto.TabIndex = 27;
			this.Panel17.Controls.Add(this.dgwProductos);
			this.Panel17.Controls.Add(this.Panel5);
			this.Panel17.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel17.Location = new global::System.Drawing.Point(0, 53);
			this.Panel17.Name = "Panel17";
			this.Panel17.Size = new global::System.Drawing.Size(1483, 632);
			this.Panel17.TabIndex = 3;
			this.dgwProductos.AllowUserToAddRows = false;
			this.dgwProductos.AllowUserToDeleteRows = false;
			this.dgwProductos.AllowUserToResizeColumns = false;
			this.dgwProductos.AllowUserToResizeRows = false;
			this.dgwProductos.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgwProductos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgwProductos.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgwProductos.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgwProductos.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgwProductos.Location = new global::System.Drawing.Point(0, 0);
			this.dgwProductos.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgwProductos.MultiSelect = false;
			this.dgwProductos.Name = "dgwProductos";
			this.dgwProductos.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dgwProductos.RowHeadersVisible = false;
			this.dgwProductos.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgwProductos.RowTemplate.Height = 24;
			this.dgwProductos.Size = new global::System.Drawing.Size(1483, 573);
			this.dgwProductos.TabIndex = 26;
			this.Panel5.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel5.Controls.Add(this.PictureBox2);
			this.Panel5.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel5.Location = new global::System.Drawing.Point(0, 573);
			this.Panel5.Name = "Panel5";
			this.Panel5.Size = new global::System.Drawing.Size(1483, 59);
			this.Panel5.TabIndex = 27;
			this.PictureBox2.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(1423, 2);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(57, 57);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 1;
			this.PictureBox2.TabStop = false;
			this.Panel6.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel6.Controls.Add(this.lblContadorJC);
			this.Panel6.Controls.Add(this.Label29);
			this.Panel6.Controls.Add(this.txtBuscarProducto);
			this.Panel6.Controls.Add(this.PictureBox4);
			this.Panel6.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel6.Location = new global::System.Drawing.Point(0, 0);
			this.Panel6.Name = "Panel6";
			this.Panel6.Size = new global::System.Drawing.Size(1483, 53);
			this.Panel6.TabIndex = 0;
			this.lblContadorJC.AutoSize = true;
			this.lblContadorJC.Location = new global::System.Drawing.Point(1245, 22);
			this.lblContadorJC.Name = "lblContadorJC";
			this.lblContadorJC.Size = new global::System.Drawing.Size(89, 25);
			this.lblContadorJC.TabIndex = 42;
			this.lblContadorJC.Text = "Label31";
			this.lblContadorJC.Visible = false;
			this.Label29.Anchor = global::System.Windows.Forms.AnchorStyles.Left;
			this.Label29.AutoSize = true;
			this.Label29.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label29.Location = new global::System.Drawing.Point(13, 13);
			this.Label29.Name = "Label29";
			this.Label29.Size = new global::System.Drawing.Size(221, 25);
			this.Label29.TabIndex = 41;
			this.Label29.Text = "Buscar Producto.....";
			this.txtBuscarProducto.Anchor = global::System.Windows.Forms.AnchorStyles.Left;
			this.txtBuscarProducto.BackColor = global::System.Drawing.Color.White;
			this.txtBuscarProducto.CharacterCasing = global::System.Windows.Forms.CharacterCasing.Upper;
			this.txtBuscarProducto.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBuscarProducto.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.txtBuscarProducto.Location = new global::System.Drawing.Point(262, 10);
			this.txtBuscarProducto.Name = "txtBuscarProducto";
			this.txtBuscarProducto.Size = new global::System.Drawing.Size(323, 31);
			this.txtBuscarProducto.TabIndex = 8;
			this.PictureBox4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox4.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			this.PictureBox4.Location = new global::System.Drawing.Point(1426, 0);
			this.PictureBox4.Name = "PictureBox4";
			this.PictureBox4.Size = new global::System.Drawing.Size(57, 53);
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox4.TabIndex = 6;
			this.PictureBox4.TabStop = false;
			this.PanelFormasdePago.Anchor = global::System.Windows.Forms.AnchorStyles.Top;
			this.PanelFormasdePago.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.PanelFormasdePago.Controls.Add(this.Panel10);
			this.PanelFormasdePago.Controls.Add(this.Panel9);
			this.PanelFormasdePago.Controls.Add(this.Panel8);
			this.PanelFormasdePago.Location = new global::System.Drawing.Point(392, 205);
			this.PanelFormasdePago.Name = "PanelFormasdePago";
			this.PanelFormasdePago.Size = new global::System.Drawing.Size(909, 364);
			this.PanelFormasdePago.TabIndex = 28;
			this.Panel10.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel10.Controls.Add(this.txtFormasPago);
			this.Panel10.Controls.Add(this.txtTotaldelTicket);
			this.Panel10.Controls.Add(this.Label26);
			this.Panel10.Controls.Add(this.Label22);
			this.Panel10.Controls.Add(this.Label23);
			this.Panel10.Controls.Add(this.Label24);
			this.Panel10.Controls.Add(this.Label25);
			this.Panel10.Controls.Add(this.TxtPropinaEnOtros);
			this.Panel10.Controls.Add(this.txtPropinaEnVales);
			this.Panel10.Controls.Add(this.txtPropinaEnTarjeta);
			this.Panel10.Controls.Add(this.TxtPropinaEnEfectivo);
			this.Panel10.Controls.Add(this.Label20);
			this.Panel10.Controls.Add(this.Label21);
			this.Panel10.Controls.Add(this.Label16);
			this.Panel10.Controls.Add(this.Label15);
			this.Panel10.Controls.Add(this.Label14);
			this.Panel10.Controls.Add(this.Label13);
			this.Panel10.Controls.Add(this.Label12);
			this.Panel10.Controls.Add(this.txtPagoPropina);
			this.Panel10.Controls.Add(this.txtPagoOtros);
			this.Panel10.Controls.Add(this.txtPagoVales);
			this.Panel10.Controls.Add(this.txtPagoTarjeta);
			this.Panel10.Controls.Add(this.txtPagoEfectivo);
			this.Panel10.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel10.Location = new global::System.Drawing.Point(0, 50);
			this.Panel10.Name = "Panel10";
			this.Panel10.Size = new global::System.Drawing.Size(907, 262);
			this.Panel10.TabIndex = 2;
			this.txtFormasPago.BackColor = global::System.Drawing.SystemColors.Info;
			this.txtFormasPago.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtFormasPago.Location = new global::System.Drawing.Point(664, 19);
			this.txtFormasPago.Name = "txtFormasPago";
			this.txtFormasPago.ReadOnly = true;
			this.txtFormasPago.Size = new global::System.Drawing.Size(200, 24);
			this.txtFormasPago.TabIndex = 53;
			this.txtTotaldelTicket.BackColor = global::System.Drawing.SystemColors.Info;
			this.txtTotaldelTicket.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotaldelTicket.Location = new global::System.Drawing.Point(178, 18);
			this.txtTotaldelTicket.Name = "txtTotaldelTicket";
			this.txtTotaldelTicket.ReadOnly = true;
			this.txtTotaldelTicket.Size = new global::System.Drawing.Size(200, 24);
			this.txtTotaldelTicket.TabIndex = 52;
			this.Label26.AutoSize = true;
			this.Label26.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label26.ForeColor = global::System.Drawing.Color.Red;
			this.Label26.Location = new global::System.Drawing.Point(429, 47);
			this.Label26.Name = "Label26";
			this.Label26.Size = new global::System.Drawing.Size(155, 24);
			this.Label26.TabIndex = 51;
			this.Label26.Text = "*Incluye propinas";
			this.Label22.AutoSize = true;
			this.Label22.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label22.Location = new global::System.Drawing.Point(384, 177);
			this.Label22.Name = "Label22";
			this.Label22.Size = new global::System.Drawing.Size(148, 25);
			this.Label22.TabIndex = 50;
			this.Label22.Text = "Otros propina:";
			this.Label23.AutoSize = true;
			this.Label23.Location = new global::System.Drawing.Point(382, 145);
			this.Label23.Name = "Label23";
			this.Label23.Size = new global::System.Drawing.Size(150, 25);
			this.Label23.TabIndex = 49;
			this.Label23.Text = "Vales propina:\r\n";
			this.Label24.AutoSize = true;
			this.Label24.Location = new global::System.Drawing.Point(369, 112);
			this.Label24.Name = "Label24";
			this.Label24.Size = new global::System.Drawing.Size(163, 25);
			this.Label24.TabIndex = 48;
			this.Label24.Text = "Tarjeta propina:";
			this.Label25.AutoSize = true;
			this.Label25.Location = new global::System.Drawing.Point(359, 81);
			this.Label25.Name = "Label25";
			this.Label25.Size = new global::System.Drawing.Size(173, 25);
			this.Label25.TabIndex = 47;
			this.Label25.Text = "Efectivo propina:";
			this.TxtPropinaEnOtros.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TxtPropinaEnOtros.Location = new global::System.Drawing.Point(544, 177);
			this.TxtPropinaEnOtros.Name = "TxtPropinaEnOtros";
			this.TxtPropinaEnOtros.Size = new global::System.Drawing.Size(186, 24);
			this.TxtPropinaEnOtros.TabIndex = 46;
			this.txtPropinaEnVales.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPropinaEnVales.Location = new global::System.Drawing.Point(544, 145);
			this.txtPropinaEnVales.Name = "txtPropinaEnVales";
			this.txtPropinaEnVales.Size = new global::System.Drawing.Size(186, 24);
			this.txtPropinaEnVales.TabIndex = 45;
			this.txtPropinaEnTarjeta.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPropinaEnTarjeta.Location = new global::System.Drawing.Point(544, 112);
			this.txtPropinaEnTarjeta.Name = "txtPropinaEnTarjeta";
			this.txtPropinaEnTarjeta.Size = new global::System.Drawing.Size(186, 24);
			this.txtPropinaEnTarjeta.TabIndex = 44;
			this.TxtPropinaEnEfectivo.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TxtPropinaEnEfectivo.Location = new global::System.Drawing.Point(544, 81);
			this.TxtPropinaEnEfectivo.Name = "TxtPropinaEnEfectivo";
			this.TxtPropinaEnEfectivo.Size = new global::System.Drawing.Size(186, 24);
			this.TxtPropinaEnEfectivo.TabIndex = 43;
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label20.Location = new global::System.Drawing.Point(420, 18);
			this.Label20.Name = "Label20";
			this.Label20.Size = new global::System.Drawing.Size(227, 25);
			this.Label20.TabIndex = 42;
			this.Label20.Text = "Total formas de pago :";
			this.Label21.AutoSize = true;
			this.Label21.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label21.Location = new global::System.Drawing.Point(8, 18);
			this.Label21.Name = "Label21";
			this.Label21.Size = new global::System.Drawing.Size(164, 25);
			this.Label21.TabIndex = 40;
			this.Label21.Text = "Total del ticket :";
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label16.Location = new global::System.Drawing.Point(17, 222);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(146, 25);
			this.Label16.TabIndex = 38;
			this.Label16.Text = "Total Propina:";
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f);
			this.Label15.Location = new global::System.Drawing.Point(32, 177);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(70, 25);
			this.Label15.TabIndex = 36;
			this.Label15.Text = "Otros:";
			this.Label14.AutoSize = true;
			this.Label14.Location = new global::System.Drawing.Point(30, 145);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(72, 25);
			this.Label14.TabIndex = 7;
			this.Label14.Text = "Vales:";
			this.Label13.AutoSize = true;
			this.Label13.Location = new global::System.Drawing.Point(17, 112);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(85, 25);
			this.Label13.TabIndex = 6;
			this.Label13.Text = "Tarjeta:";
			this.Label12.AutoSize = true;
			this.Label12.Location = new global::System.Drawing.Point(7, 81);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(95, 25);
			this.Label12.TabIndex = 5;
			this.Label12.Text = "Efectivo:";
			this.txtPagoPropina.BackColor = global::System.Drawing.SystemColors.Info;
			this.txtPagoPropina.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPagoPropina.Location = new global::System.Drawing.Point(174, 222);
			this.txtPagoPropina.Name = "txtPagoPropina";
			this.txtPagoPropina.ReadOnly = true;
			this.txtPagoPropina.Size = new global::System.Drawing.Size(186, 24);
			this.txtPagoPropina.TabIndex = 4;
			this.txtPagoOtros.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPagoOtros.Location = new global::System.Drawing.Point(116, 177);
			this.txtPagoOtros.Name = "txtPagoOtros";
			this.txtPagoOtros.Size = new global::System.Drawing.Size(186, 24);
			this.txtPagoOtros.TabIndex = 3;
			this.txtPagoVales.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPagoVales.Location = new global::System.Drawing.Point(116, 145);
			this.txtPagoVales.Name = "txtPagoVales";
			this.txtPagoVales.Size = new global::System.Drawing.Size(186, 24);
			this.txtPagoVales.TabIndex = 2;
			this.txtPagoTarjeta.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPagoTarjeta.Location = new global::System.Drawing.Point(116, 112);
			this.txtPagoTarjeta.Name = "txtPagoTarjeta";
			this.txtPagoTarjeta.Size = new global::System.Drawing.Size(186, 24);
			this.txtPagoTarjeta.TabIndex = 1;
			this.txtPagoEfectivo.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPagoEfectivo.Location = new global::System.Drawing.Point(116, 81);
			this.txtPagoEfectivo.Name = "txtPagoEfectivo";
			this.txtPagoEfectivo.Size = new global::System.Drawing.Size(186, 24);
			this.txtPagoEfectivo.TabIndex = 0;
			this.Panel9.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel9.Controls.Add(this.labeltotalformasdepago);
			this.Panel9.Controls.Add(this.lbltotalpropinasvalidacion);
			this.Panel9.Controls.Add(this.lbltotalvalidacion);
			this.Panel9.Controls.Add(this.PictureBox5);
			this.Panel9.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel9.Location = new global::System.Drawing.Point(0, 312);
			this.Panel9.Name = "Panel9";
			this.Panel9.Size = new global::System.Drawing.Size(907, 50);
			this.Panel9.TabIndex = 1;
			this.labeltotalformasdepago.AutoSize = true;
			this.labeltotalformasdepago.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.labeltotalformasdepago.Location = new global::System.Drawing.Point(6, 35);
			this.labeltotalformasdepago.Name = "labeltotalformasdepago";
			this.labeltotalformasdepago.Size = new global::System.Drawing.Size(136, 16);
			this.labeltotalformasdepago.TabIndex = 5;
			this.labeltotalformasdepago.Text = "lbltotalformasdepago";
			this.labeltotalformasdepago.Visible = false;
			this.lbltotalpropinasvalidacion.AutoSize = true;
			this.lbltotalpropinasvalidacion.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbltotalpropinasvalidacion.Location = new global::System.Drawing.Point(6, 19);
			this.lbltotalpropinasvalidacion.Name = "lbltotalpropinasvalidacion";
			this.lbltotalpropinasvalidacion.Size = new global::System.Drawing.Size(162, 16);
			this.lbltotalpropinasvalidacion.TabIndex = 4;
			this.lbltotalpropinasvalidacion.Text = "lbltotalpropinasvalidacion";
			this.lbltotalpropinasvalidacion.Visible = false;
			this.lbltotalvalidacion.AutoSize = true;
			this.lbltotalvalidacion.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lbltotalvalidacion.Location = new global::System.Drawing.Point(6, 3);
			this.lbltotalvalidacion.Name = "lbltotalvalidacion";
			this.lbltotalvalidacion.Size = new global::System.Drawing.Size(109, 16);
			this.lbltotalvalidacion.TabIndex = 3;
			this.lbltotalvalidacion.Text = "lbltotalvalidacion";
			this.lbltotalvalidacion.Visible = false;
			this.PictureBox5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox5.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox5.Image");
			this.PictureBox5.Location = new global::System.Drawing.Point(849, 0);
			this.PictureBox5.Name = "PictureBox5";
			this.PictureBox5.Size = new global::System.Drawing.Size(58, 50);
			this.PictureBox5.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox5.TabIndex = 2;
			this.PictureBox5.TabStop = false;
			this.Panel8.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel8.Controls.Add(this.lblTotalFormapagoconpropina);
			this.Panel8.Controls.Add(this.lbldiefectivotarjeta);
			this.Panel8.Controls.Add(this.lblidefectivo);
			this.Panel8.Controls.Add(this.lblPropinasSumar);
			this.Panel8.Controls.Add(this.lblOtrosSUmar);
			this.Panel8.Controls.Add(this.lblValesSumar);
			this.Panel8.Controls.Add(this.lblTarjetasumar);
			this.Panel8.Controls.Add(this.lblEfectivoSumar);
			this.Panel8.Controls.Add(this.PictureBox3);
			this.Panel8.Controls.Add(this.Label9);
			this.Panel8.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel8.Location = new global::System.Drawing.Point(0, 0);
			this.Panel8.Name = "Panel8";
			this.Panel8.Size = new global::System.Drawing.Size(907, 50);
			this.Panel8.TabIndex = 0;
			this.lblTotalFormapagoconpropina.AutoSize = true;
			this.lblTotalFormapagoconpropina.Location = new global::System.Drawing.Point(1144, 31);
			this.lblTotalFormapagoconpropina.Name = "lblTotalFormapagoconpropina";
			this.lblTotalFormapagoconpropina.Size = new global::System.Drawing.Size(298, 25);
			this.lblTotalFormapagoconpropina.TabIndex = 15;
			this.lblTotalFormapagoconpropina.Text = "lblTotalFormapagoconpropina";
			this.lblTotalFormapagoconpropina.Visible = false;
			this.lbldiefectivotarjeta.AutoSize = true;
			this.lbldiefectivotarjeta.Location = new global::System.Drawing.Point(933, 11);
			this.lbldiefectivotarjeta.Name = "lbldiefectivotarjeta";
			this.lbldiefectivotarjeta.Size = new global::System.Drawing.Size(89, 25);
			this.lbldiefectivotarjeta.TabIndex = 14;
			this.lbldiefectivotarjeta.Text = "Label26";
			this.lbldiefectivotarjeta.Visible = false;
			this.lblidefectivo.AutoSize = true;
			this.lblidefectivo.Location = new global::System.Drawing.Point(773, 7);
			this.lblidefectivo.Name = "lblidefectivo";
			this.lblidefectivo.Size = new global::System.Drawing.Size(126, 25);
			this.lblidefectivo.TabIndex = 13;
			this.lblidefectivo.Text = "lblidefectivo";
			this.lblidefectivo.Visible = false;
			this.lblPropinasSumar.AutoSize = true;
			this.lblPropinasSumar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblPropinasSumar.Location = new global::System.Drawing.Point(1065, 23);
			this.lblPropinasSumar.Name = "lblPropinasSumar";
			this.lblPropinasSumar.Size = new global::System.Drawing.Size(115, 16);
			this.lblPropinasSumar.TabIndex = 12;
			this.lblPropinasSumar.Text = "lblPropinasSumar";
			this.lblPropinasSumar.Visible = false;
			this.lblOtrosSUmar.AutoSize = true;
			this.lblOtrosSUmar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblOtrosSUmar.Location = new global::System.Drawing.Point(1146, 20);
			this.lblOtrosSUmar.Name = "lblOtrosSUmar";
			this.lblOtrosSUmar.Size = new global::System.Drawing.Size(96, 16);
			this.lblOtrosSUmar.TabIndex = 11;
			this.lblOtrosSUmar.Text = "lblOtrosSUmar";
			this.lblOtrosSUmar.Visible = false;
			this.lblValesSumar.AutoSize = true;
			this.lblValesSumar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblValesSumar.Location = new global::System.Drawing.Point(872, 18);
			this.lblValesSumar.Name = "lblValesSumar";
			this.lblValesSumar.Size = new global::System.Drawing.Size(96, 16);
			this.lblValesSumar.TabIndex = 10;
			this.lblValesSumar.Text = "lblValesSumar";
			this.lblValesSumar.Visible = false;
			this.lblTarjetasumar.AutoSize = true;
			this.lblTarjetasumar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblTarjetasumar.Location = new global::System.Drawing.Point(1048, 18);
			this.lblTarjetasumar.Name = "lblTarjetasumar";
			this.lblTarjetasumar.Size = new global::System.Drawing.Size(102, 16);
			this.lblTarjetasumar.TabIndex = 9;
			this.lblTarjetasumar.Text = "lblTarjetasumar";
			this.lblTarjetasumar.Visible = false;
			this.lblEfectivoSumar.AutoSize = true;
			this.lblEfectivoSumar.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 4.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblEfectivoSumar.Location = new global::System.Drawing.Point(1041, 23);
			this.lblEfectivoSumar.Name = "lblEfectivoSumar";
			this.lblEfectivoSumar.Size = new global::System.Drawing.Size(109, 16);
			this.lblEfectivoSumar.TabIndex = 8;
			this.lblEfectivoSumar.Text = "lblEfectivoSumar";
			this.lblEfectivoSumar.Visible = false;
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(849, 0);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(58, 50);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 7;
			this.PictureBox3.TabStop = false;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.Location = new global::System.Drawing.Point(3, 10);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(518, 29);
			this.Label9.TabIndex = 0;
			this.Label9.Text = "Elige la nueva forma de pago para el ticket:";
			this.dgvNotas.AllowUserToAddRows = false;
			this.dgvNotas.AllowUserToDeleteRows = false;
			this.dgvNotas.AllowUserToResizeColumns = false;
			this.dgvNotas.AllowUserToResizeRows = false;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.dgvNotas.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle;
			this.dgvNotas.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgvNotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvNotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvNotas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dgvNotas.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgvNotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvNotas.Location = new global::System.Drawing.Point(0, 0);
			this.dgvNotas.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgvNotas.MultiSelect = false;
			this.dgvNotas.Name = "dgvNotas";
			this.dgvNotas.ReadOnly = true;
			this.dgvNotas.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dgvNotas.RowHeadersVisible = false;
			this.dgvNotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvNotas.RowTemplate.Height = 24;
			this.dgvNotas.SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dgvNotas.Size = new global::System.Drawing.Size(1692, 827);
			this.dgvNotas.TabIndex = 25;
			this.Panel12.Controls.Add(this.PanelDGW);
			this.Panel12.Controls.Add(this.Panel4);
			this.Panel12.Controls.Add(this.Panel2);
			this.Panel12.Controls.Add(this.GroupBox3);
			this.Panel12.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel12.Location = new global::System.Drawing.Point(930, 215);
			this.Panel12.Name = "Panel12";
			this.Panel12.Size = new global::System.Drawing.Size(1692, 1084);
			this.Panel12.TabIndex = 100;
			this.GroupBox3.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.GroupBox3.Controls.Add(this.btnCambiarFormadePago);
			this.GroupBox3.Controls.Add(this.Label28);
			this.GroupBox3.Controls.Add(this.lblFolio);
			this.GroupBox3.Controls.Add(this.txtFechadelTicket);
			this.GroupBox3.Controls.Add(this.TxtFacturado);
			this.GroupBox3.Controls.Add(this.Label7);
			this.GroupBox3.Controls.Add(this.txtPersonas);
			this.GroupBox3.Controls.Add(this.lblPersonas);
			this.GroupBox3.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.GroupBox3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.GroupBox3.Location = new global::System.Drawing.Point(0, 0);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.Size = new global::System.Drawing.Size(1692, 111);
			this.GroupBox3.TabIndex = 163;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Informacion del ticket";
			this.btnCambiarFormadePago.BackColor = global::System.Drawing.Color.White;
			this.btnCambiarFormadePago.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnCambiarFormadePago.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnCambiarFormadePago.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnCambiarFormadePago.Image");
			this.btnCambiarFormadePago.Location = new global::System.Drawing.Point(1082, 21);
			this.btnCambiarFormadePago.Name = "btnCambiarFormadePago";
			this.btnCambiarFormadePago.Size = new global::System.Drawing.Size(373, 84);
			this.btnCambiarFormadePago.TabIndex = 175;
			this.btnCambiarFormadePago.Text = "Cambiar forma de Pago";
			this.btnCambiarFormadePago.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.btnCambiarFormadePago.UseVisualStyleBackColor = false;
			this.Label28.AutoSize = true;
			this.Label28.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 6f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label28.ForeColor = global::System.Drawing.Color.Red;
			this.Label28.Location = new global::System.Drawing.Point(876, 69);
			this.Label28.Name = "Label28";
			this.Label28.Size = new global::System.Drawing.Size(190, 40);
			this.Label28.TabIndex = 161;
			this.Label28.Text = "*Nota\r\nEdita el # de Personas\r\n";
			this.lblFolio.AutoSize = true;
			this.lblFolio.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblFolio.Location = new global::System.Drawing.Point(7, 41);
			this.lblFolio.Name = "lblFolio";
			this.lblFolio.Size = new global::System.Drawing.Size(170, 25);
			this.lblFolio.TabIndex = 155;
			this.lblFolio.Text = "Fecha del ticket:";
			this.txtFechadelTicket.BackColor = global::System.Drawing.Color.White;
			this.txtFechadelTicket.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtFechadelTicket.Enabled = false;
			this.txtFechadelTicket.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtFechadelTicket.Location = new global::System.Drawing.Point(190, 39);
			this.txtFechadelTicket.Name = "txtFechadelTicket";
			this.txtFechadelTicket.ReadOnly = true;
			this.txtFechadelTicket.Size = new global::System.Drawing.Size(305, 24);
			this.txtFechadelTicket.TabIndex = 153;
			this.TxtFacturado.BackColor = global::System.Drawing.Color.White;
			this.TxtFacturado.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TxtFacturado.Enabled = false;
			this.TxtFacturado.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.TxtFacturado.Location = new global::System.Drawing.Point(631, 39);
			this.TxtFacturado.Name = "TxtFacturado";
			this.TxtFacturado.ReadOnly = true;
			this.TxtFacturado.Size = new global::System.Drawing.Size(229, 24);
			this.TxtFacturado.TabIndex = 159;
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label7.Location = new global::System.Drawing.Point(503, 41);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(115, 25);
			this.Label7.TabIndex = 158;
			this.Label7.Text = "Facturado:";
			this.txtPersonas.BackColor = global::System.Drawing.Color.White;
			this.txtPersonas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPersonas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtPersonas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtPersonas.Location = new global::System.Drawing.Point(991, 39);
			this.txtPersonas.Name = "txtPersonas";
			this.txtPersonas.ReadOnly = true;
			this.txtPersonas.Size = new global::System.Drawing.Size(75, 24);
			this.txtPersonas.TabIndex = 156;
			this.txtPersonas.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.lblPersonas.AutoSize = true;
			this.lblPersonas.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblPersonas.Location = new global::System.Drawing.Point(869, 41);
			this.lblPersonas.Name = "lblPersonas";
			this.lblPersonas.Size = new global::System.Drawing.Size(109, 25);
			this.lblPersonas.TabIndex = 157;
			this.lblPersonas.Text = "Personas:";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(2622, 1327);
			base.Controls.Add(this.Panel12);
			base.Controls.Add(this.Panel14);
			base.Controls.Add(this.Panel16);
			base.Controls.Add(this.Panel1);
			this.DoubleBuffered = true;
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "FrmModificarTicket";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "FrmModificarTicket";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.PanelVariables.ResumeLayout(false);
			this.PanelVariables.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.BtnVolver).EndInit();
			this.Panel2.ResumeLayout(false);
			this.Panel2.PerformLayout();
			this.Panel4.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.btnEliminarProducto).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnAgregarProducto).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DgvTicketsPeriodo).EndInit();
			this.Panel14.ResumeLayout(false);
			this.PanelDGW.ResumeLayout(false);
			this.PanelDGW.PerformLayout();
			this.PanelBuscarProducto.ResumeLayout(false);
			this.Panel17.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.dgwProductos).EndInit();
			this.Panel5.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			this.Panel6.ResumeLayout(false);
			this.Panel6.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			this.PanelFormasdePago.ResumeLayout(false);
			this.Panel10.ResumeLayout(false);
			this.Panel10.PerformLayout();
			this.Panel9.ResumeLayout(false);
			this.Panel9.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).EndInit();
			this.Panel8.ResumeLayout(false);
			this.Panel8.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvNotas).EndInit();
			this.Panel12.ResumeLayout(false);
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x04000519 RID: 1305
		private global::System.ComponentModel.IContainer components;
	}
}
