namespace ModuloAdicional
{
	// Token: 0x0200001D RID: 29
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmParametros : global::System.Windows.Forms.Form
	{
		// Token: 0x06000C71 RID: 3185 RVA: 0x000CC3CC File Offset: 0x000CA5CC
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000C72 RID: 3186 RVA: 0x000CC41C File Offset: 0x000CA61C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmParametros));
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.lblBitacoraActiva = new global::System.Windows.Forms.Label();
			this.lblBitacoraDesactivada = new global::System.Windows.Forms.Label();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.lblventasnoalmacenadas = new global::System.Windows.Forms.Label();
			this.lblAlmacenaVentasAcrivo = new global::System.Windows.Forms.Label();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.BackgroundWorker1 = new global::System.ComponentModel.BackgroundWorker();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.lblidformapago = new global::System.Windows.Forms.Label();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.PictureBox2formas = new global::System.Windows.Forms.PictureBox();
			this.lblidOtros = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.lblidVales = new global::System.Windows.Forms.Label();
			this.ComboBox2Formas = new global::System.Windows.Forms.ComboBox();
			this.lblidTarjeta = new global::System.Windows.Forms.Label();
			this.PictureOtros = new global::System.Windows.Forms.PictureBox();
			this.lbldiEfectivo = new global::System.Windows.Forms.Label();
			this.PictureBoxVales = new global::System.Windows.Forms.PictureBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox4 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox5 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox6 = new global::System.Windows.Forms.PictureBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.ComboBoxOtrosTicket = new global::System.Windows.Forms.ComboBox();
			this.ComboBoxValesTicket = new global::System.Windows.Forms.ComboBox();
			this.ComboBoxEfectivoTicket = new global::System.Windows.Forms.ComboBox();
			this.ComboBoxTarjetaTicket = new global::System.Windows.Forms.ComboBox();
			this.PictureBoxTarjeta = new global::System.Windows.Forms.PictureBox();
			this.PictureBoxEfectivo = new global::System.Windows.Forms.PictureBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.ComboBoxOtros = new global::System.Windows.Forms.ComboBox();
			this.ComboBoxVales = new global::System.Windows.Forms.ComboBox();
			this.ComboBoxEfectivo = new global::System.Windows.Forms.ComboBox();
			this.ComboBoxTarjeta = new global::System.Windows.Forms.ComboBox();
			this.BackgroundWorker2 = new global::System.ComponentModel.BackgroundWorker();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.lblNoalmacenaInv = new global::System.Windows.Forms.Label();
			this.lblAlmacenaInv = new global::System.Windows.Forms.Label();
			this.CheckBoxInventarios = new global::System.Windows.Forms.CheckBox();
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.CheckBox_SepararProductos = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxAleatorio = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxContinuo = new global::System.Windows.Forms.CheckBox();
			this.GroupBox1.SuspendLayout();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.GroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2formas).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureOtros).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxVales).BeginInit();
			this.GroupBox4.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxTarjeta).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxEfectivo).BeginInit();
			this.GroupBox3.SuspendLayout();
			this.GroupBox5.SuspendLayout();
			base.SuspendLayout();
			this.GroupBox1.Controls.Add(this.lblBitacoraActiva);
			this.GroupBox1.Controls.Add(this.lblBitacoraDesactivada);
			this.GroupBox1.Controls.Add(this.CheckBox2);
			this.GroupBox1.Controls.Add(this.lblventasnoalmacenadas);
			this.GroupBox1.Controls.Add(this.lblAlmacenaVentasAcrivo);
			this.GroupBox1.Controls.Add(this.CheckBox1);
			this.GroupBox1.Location = new global::System.Drawing.Point(0, 37);
			this.GroupBox1.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Padding = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox1.Size = new global::System.Drawing.Size(364, 121);
			this.GroupBox1.TabIndex = 0;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Reportes";
			this.lblBitacoraActiva.AutoSize = true;
			this.lblBitacoraActiva.ForeColor = global::System.Drawing.Color.Green;
			this.lblBitacoraActiva.Location = new global::System.Drawing.Point(4, 92);
			this.lblBitacoraActiva.Name = "lblBitacoraActiva";
			this.lblBitacoraActiva.Size = new global::System.Drawing.Size(153, 17);
			this.lblBitacoraActiva.TabIndex = 5;
			this.lblBitacoraActiva.Text = "Almacenando bitacora ";
			this.lblBitacoraDesactivada.AccessibleRole = global::System.Windows.Forms.AccessibleRole.None;
			this.lblBitacoraDesactivada.AutoSize = true;
			this.lblBitacoraDesactivada.ForeColor = global::System.Drawing.Color.Red;
			this.lblBitacoraDesactivada.Location = new global::System.Drawing.Point(4, 92);
			this.lblBitacoraDesactivada.Name = "lblBitacoraDesactivada";
			this.lblBitacoraDesactivada.Size = new global::System.Drawing.Size(161, 17);
			this.lblBitacoraDesactivada.TabIndex = 4;
			this.lblBitacoraDesactivada.Text = "Bitacora no almacenada";
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox2.Location = new global::System.Drawing.Point(4, 66);
			this.CheckBox2.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(234, 21);
			this.CheckBox2.TabIndex = 3;
			this.CheckBox2.Text = "Almacenar bitacora de procesos";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.lblventasnoalmacenadas.AutoSize = true;
			this.lblventasnoalmacenadas.ForeColor = global::System.Drawing.Color.Red;
			this.lblventasnoalmacenadas.Location = new global::System.Drawing.Point(4, 46);
			this.lblventasnoalmacenadas.Name = "lblventasnoalmacenadas";
			this.lblventasnoalmacenadas.Size = new global::System.Drawing.Size(174, 17);
			this.lblventasnoalmacenadas.TabIndex = 2;
			this.lblventasnoalmacenadas.Text = "Reportes no almacenados";
			this.lblAlmacenaVentasAcrivo.AutoSize = true;
			this.lblAlmacenaVentasAcrivo.ForeColor = global::System.Drawing.Color.Green;
			this.lblAlmacenaVentasAcrivo.Location = new global::System.Drawing.Point(4, 46);
			this.lblAlmacenaVentasAcrivo.Name = "lblAlmacenaVentasAcrivo";
			this.lblAlmacenaVentasAcrivo.Size = new global::System.Drawing.Size(154, 17);
			this.lblAlmacenaVentasAcrivo.TabIndex = 1;
			this.lblAlmacenaVentasAcrivo.Text = "Reportes almacenados";
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.CheckBox1.Location = new global::System.Drawing.Point(4, 26);
			this.CheckBox1.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(159, 21);
			this.CheckBox1.TabIndex = 0;
			this.CheckBox1.Text = "Almacenar Reportes";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.Panel1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel1.Controls.Add(this.lblidformapago);
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Controls.Add(this.Label1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(689, 33);
			this.Panel1.TabIndex = 1;
			this.lblidformapago.AutoSize = true;
			this.lblidformapago.Location = new global::System.Drawing.Point(411, 12);
			this.lblidformapago.Name = "lblidformapago";
			this.lblidformapago.Size = new global::System.Drawing.Size(101, 17);
			this.lblidformapago.TabIndex = 8;
			this.lblidformapago.Text = "lblIdformapago";
			this.lblidformapago.Visible = false;
			this.PictureBox1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(657, 2);
			this.PictureBox1.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(29, 28);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 128;
			this.PictureBox1.TabStop = false;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label1.Location = new global::System.Drawing.Point(8, 9);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(106, 20);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "Parametros";
			this.GroupBox2.Controls.Add(this.PictureBox2formas);
			this.GroupBox2.Controls.Add(this.lblidOtros);
			this.GroupBox2.Controls.Add(this.Label6);
			this.GroupBox2.Controls.Add(this.lblidVales);
			this.GroupBox2.Controls.Add(this.ComboBox2Formas);
			this.GroupBox2.Controls.Add(this.lblidTarjeta);
			this.GroupBox2.Controls.Add(this.PictureOtros);
			this.GroupBox2.Controls.Add(this.lbldiEfectivo);
			this.GroupBox2.Controls.Add(this.PictureBoxVales);
			this.GroupBox2.Controls.Add(this.GroupBox4);
			this.GroupBox2.Controls.Add(this.PictureBoxTarjeta);
			this.GroupBox2.Controls.Add(this.PictureBoxEfectivo);
			this.GroupBox2.Controls.Add(this.Label5);
			this.GroupBox2.Controls.Add(this.Label4);
			this.GroupBox2.Controls.Add(this.Label3);
			this.GroupBox2.Controls.Add(this.Label2);
			this.GroupBox2.Controls.Add(this.ComboBoxOtros);
			this.GroupBox2.Controls.Add(this.ComboBoxVales);
			this.GroupBox2.Controls.Add(this.ComboBoxEfectivo);
			this.GroupBox2.Controls.Add(this.ComboBoxTarjeta);
			this.GroupBox2.Location = new global::System.Drawing.Point(4, 172);
			this.GroupBox2.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Padding = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox2.Size = new global::System.Drawing.Size(357, 276);
			this.GroupBox2.TabIndex = 2;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Formas de pago - Procesos por producto";
			this.PictureBox2formas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox2formas.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2formas.Image");
			this.PictureBox2formas.Location = new global::System.Drawing.Point(259, 230);
			this.PictureBox2formas.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBox2formas.Name = "PictureBox2formas";
			this.PictureBox2formas.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBox2formas.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2formas.TabIndex = 14;
			this.PictureBox2formas.TabStop = false;
			this.lblidOtros.AutoSize = true;
			this.lblidOtros.Location = new global::System.Drawing.Point(568, 190);
			this.lblidOtros.Name = "lblidOtros";
			this.lblidOtros.Size = new global::System.Drawing.Size(68, 17);
			this.lblidOtros.TabIndex = 116;
			this.lblidOtros.Text = "lblidOtros";
			this.lblidOtros.Visible = false;
			this.Label6.AutoSize = true;
			this.Label6.Location = new global::System.Drawing.Point(3, 212);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(343, 17);
			this.Label6.TabIndex = 13;
			this.Label6.Text = "Forma de pago - Para cuentas con 2 formas de pago";
			this.lblidVales.AutoSize = true;
			this.lblidVales.Location = new global::System.Drawing.Point(635, 190);
			this.lblidVales.Name = "lblidVales";
			this.lblidVales.Size = new global::System.Drawing.Size(66, 17);
			this.lblidVales.TabIndex = 115;
			this.lblidVales.Text = "lblidvales";
			this.lblidVales.Visible = false;
			this.ComboBox2Formas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBox2Formas.FormattingEnabled = true;
			this.ComboBox2Formas.Location = new global::System.Drawing.Point(3, 230);
			this.ComboBox2Formas.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBox2Formas.Name = "ComboBox2Formas";
			this.ComboBox2Formas.Size = new global::System.Drawing.Size(248, 24);
			this.ComboBox2Formas.TabIndex = 12;
			this.lblidTarjeta.AutoSize = true;
			this.lblidTarjeta.Location = new global::System.Drawing.Point(496, 190);
			this.lblidTarjeta.Name = "lblidTarjeta";
			this.lblidTarjeta.Size = new global::System.Drawing.Size(73, 17);
			this.lblidTarjeta.TabIndex = 114;
			this.lblidTarjeta.Text = "lblidtarjeta";
			this.lblidTarjeta.Visible = false;
			this.PictureOtros.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureOtros.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureOtros.Image");
			this.PictureOtros.Location = new global::System.Drawing.Point(259, 178);
			this.PictureOtros.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureOtros.Name = "PictureOtros";
			this.PictureOtros.Size = new global::System.Drawing.Size(27, 21);
			this.PictureOtros.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureOtros.TabIndex = 11;
			this.PictureOtros.TabStop = false;
			this.lbldiEfectivo.AutoSize = true;
			this.lbldiEfectivo.Location = new global::System.Drawing.Point(411, 190);
			this.lbldiEfectivo.Name = "lbldiEfectivo";
			this.lbldiEfectivo.Size = new global::System.Drawing.Size(83, 17);
			this.lbldiEfectivo.TabIndex = 113;
			this.lbldiEfectivo.Text = "lbldiEfectivo";
			this.lbldiEfectivo.Visible = false;
			this.PictureBoxVales.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBoxVales.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxVales.Image");
			this.PictureBoxVales.Location = new global::System.Drawing.Point(259, 132);
			this.PictureBoxVales.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBoxVales.Name = "PictureBoxVales";
			this.PictureBoxVales.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBoxVales.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxVales.TabIndex = 10;
			this.PictureBoxVales.TabStop = false;
			this.GroupBox4.Controls.Add(this.PictureBox3);
			this.GroupBox4.Controls.Add(this.PictureBox4);
			this.GroupBox4.Controls.Add(this.PictureBox5);
			this.GroupBox4.Controls.Add(this.PictureBox6);
			this.GroupBox4.Controls.Add(this.Label8);
			this.GroupBox4.Controls.Add(this.Label9);
			this.GroupBox4.Controls.Add(this.Label10);
			this.GroupBox4.Controls.Add(this.Label11);
			this.GroupBox4.Controls.Add(this.ComboBoxOtrosTicket);
			this.GroupBox4.Controls.Add(this.ComboBoxValesTicket);
			this.GroupBox4.Controls.Add(this.ComboBoxEfectivoTicket);
			this.GroupBox4.Controls.Add(this.ComboBoxTarjetaTicket);
			this.GroupBox4.Location = new global::System.Drawing.Point(104, 261);
			this.GroupBox4.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox4.Name = "GroupBox4";
			this.GroupBox4.Padding = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox4.Size = new global::System.Drawing.Size(307, 46);
			this.GroupBox4.TabIndex = 4;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "Formas de pago - Editar 1 Ticket";
			this.GroupBox4.Visible = false;
			this.PictureBox3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(259, 178);
			this.PictureBox3.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 11;
			this.PictureBox3.TabStop = false;
			this.PictureBox4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox4.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox4.Image");
			this.PictureBox4.Location = new global::System.Drawing.Point(259, 132);
			this.PictureBox4.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBox4.Name = "PictureBox4";
			this.PictureBox4.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBox4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox4.TabIndex = 10;
			this.PictureBox4.TabStop = false;
			this.PictureBox5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox5.Image");
			this.PictureBox5.Location = new global::System.Drawing.Point(259, 84);
			this.PictureBox5.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBox5.Name = "PictureBox5";
			this.PictureBox5.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBox5.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox5.TabIndex = 9;
			this.PictureBox5.TabStop = false;
			this.PictureBox6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox6.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox6.Image");
			this.PictureBox6.Location = new global::System.Drawing.Point(259, 36);
			this.PictureBox6.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBox6.Name = "PictureBox6";
			this.PictureBox6.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBox6.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox6.TabIndex = 8;
			this.PictureBox6.TabStop = false;
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(3, 161);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(43, 17);
			this.Label8.TabIndex = 7;
			this.Label8.Text = "Otros";
			this.Label9.AutoSize = true;
			this.Label9.Location = new global::System.Drawing.Point(3, 114);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(43, 17);
			this.Label9.TabIndex = 6;
			this.Label9.Text = "Vales";
			this.Label10.AutoSize = true;
			this.Label10.Location = new global::System.Drawing.Point(3, 66);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(53, 17);
			this.Label10.TabIndex = 5;
			this.Label10.Text = "Tarjeta";
			this.Label11.AutoSize = true;
			this.Label11.Location = new global::System.Drawing.Point(3, 20);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(58, 17);
			this.Label11.TabIndex = 4;
			this.Label11.Text = "Efectivo";
			this.ComboBoxOtrosTicket.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxOtrosTicket.FormattingEnabled = true;
			this.ComboBoxOtrosTicket.Location = new global::System.Drawing.Point(3, 178);
			this.ComboBoxOtrosTicket.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxOtrosTicket.Name = "ComboBoxOtrosTicket";
			this.ComboBoxOtrosTicket.Size = new global::System.Drawing.Size(248, 24);
			this.ComboBoxOtrosTicket.TabIndex = 3;
			this.ComboBoxValesTicket.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxValesTicket.FormattingEnabled = true;
			this.ComboBoxValesTicket.Location = new global::System.Drawing.Point(3, 132);
			this.ComboBoxValesTicket.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxValesTicket.Name = "ComboBoxValesTicket";
			this.ComboBoxValesTicket.Size = new global::System.Drawing.Size(249, 24);
			this.ComboBoxValesTicket.TabIndex = 2;
			this.ComboBoxEfectivoTicket.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxEfectivoTicket.FormattingEnabled = true;
			this.ComboBoxEfectivoTicket.Location = new global::System.Drawing.Point(3, 37);
			this.ComboBoxEfectivoTicket.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxEfectivoTicket.Name = "ComboBoxEfectivoTicket";
			this.ComboBoxEfectivoTicket.Size = new global::System.Drawing.Size(249, 24);
			this.ComboBoxEfectivoTicket.TabIndex = 1;
			this.ComboBoxTarjetaTicket.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxTarjetaTicket.FormattingEnabled = true;
			this.ComboBoxTarjetaTicket.Location = new global::System.Drawing.Point(3, 85);
			this.ComboBoxTarjetaTicket.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxTarjetaTicket.Name = "ComboBoxTarjetaTicket";
			this.ComboBoxTarjetaTicket.Size = new global::System.Drawing.Size(249, 24);
			this.ComboBoxTarjetaTicket.TabIndex = 0;
			this.PictureBoxTarjeta.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBoxTarjeta.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxTarjeta.Image");
			this.PictureBoxTarjeta.Location = new global::System.Drawing.Point(259, 84);
			this.PictureBoxTarjeta.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBoxTarjeta.Name = "PictureBoxTarjeta";
			this.PictureBoxTarjeta.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBoxTarjeta.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxTarjeta.TabIndex = 9;
			this.PictureBoxTarjeta.TabStop = false;
			this.PictureBoxEfectivo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBoxEfectivo.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxEfectivo.Image");
			this.PictureBoxEfectivo.Location = new global::System.Drawing.Point(259, 36);
			this.PictureBoxEfectivo.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.PictureBoxEfectivo.Name = "PictureBoxEfectivo";
			this.PictureBoxEfectivo.Size = new global::System.Drawing.Size(27, 21);
			this.PictureBoxEfectivo.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxEfectivo.TabIndex = 8;
			this.PictureBoxEfectivo.TabStop = false;
			this.Label5.AutoSize = true;
			this.Label5.Location = new global::System.Drawing.Point(3, 160);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(43, 17);
			this.Label5.TabIndex = 7;
			this.Label5.Text = "Otros";
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(3, 113);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(43, 17);
			this.Label4.TabIndex = 6;
			this.Label4.Text = "Vales";
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(3, 66);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(53, 17);
			this.Label3.TabIndex = 5;
			this.Label3.Text = "Tarjeta";
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(3, 18);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(58, 17);
			this.Label2.TabIndex = 4;
			this.Label2.Text = "Efectivo";
			this.ComboBoxOtros.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxOtros.FormattingEnabled = true;
			this.ComboBoxOtros.Location = new global::System.Drawing.Point(3, 178);
			this.ComboBoxOtros.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxOtros.Name = "ComboBoxOtros";
			this.ComboBoxOtros.Size = new global::System.Drawing.Size(248, 24);
			this.ComboBoxOtros.TabIndex = 3;
			this.ComboBoxVales.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxVales.FormattingEnabled = true;
			this.ComboBoxVales.Location = new global::System.Drawing.Point(3, 132);
			this.ComboBoxVales.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxVales.Name = "ComboBoxVales";
			this.ComboBoxVales.Size = new global::System.Drawing.Size(249, 24);
			this.ComboBoxVales.TabIndex = 2;
			this.ComboBoxEfectivo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxEfectivo.FormattingEnabled = true;
			this.ComboBoxEfectivo.Location = new global::System.Drawing.Point(3, 37);
			this.ComboBoxEfectivo.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxEfectivo.Name = "ComboBoxEfectivo";
			this.ComboBoxEfectivo.Size = new global::System.Drawing.Size(249, 24);
			this.ComboBoxEfectivo.TabIndex = 1;
			this.ComboBoxTarjeta.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBoxTarjeta.FormattingEnabled = true;
			this.ComboBoxTarjeta.Location = new global::System.Drawing.Point(3, 84);
			this.ComboBoxTarjeta.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.ComboBoxTarjeta.Name = "ComboBoxTarjeta";
			this.ComboBoxTarjeta.Size = new global::System.Drawing.Size(249, 24);
			this.ComboBoxTarjeta.TabIndex = 0;
			this.GroupBox3.Controls.Add(this.lblNoalmacenaInv);
			this.GroupBox3.Controls.Add(this.lblAlmacenaInv);
			this.GroupBox3.Controls.Add(this.CheckBoxInventarios);
			this.GroupBox3.Location = new global::System.Drawing.Point(375, 37);
			this.GroupBox3.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.Padding = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox3.Size = new global::System.Drawing.Size(307, 69);
			this.GroupBox3.TabIndex = 3;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Inventarios";
			this.lblNoalmacenaInv.AutoSize = true;
			this.lblNoalmacenaInv.ForeColor = global::System.Drawing.Color.Red;
			this.lblNoalmacenaInv.Location = new global::System.Drawing.Point(5, 44);
			this.lblNoalmacenaInv.Name = "lblNoalmacenaInv";
			this.lblNoalmacenaInv.Size = new global::System.Drawing.Size(176, 17);
			this.lblNoalmacenaInv.TabIndex = 6;
			this.lblNoalmacenaInv.Text = "Inventarios no modificados";
			this.lblAlmacenaInv.AutoSize = true;
			this.lblAlmacenaInv.ForeColor = global::System.Drawing.Color.Green;
			this.lblAlmacenaInv.Location = new global::System.Drawing.Point(5, 44);
			this.lblAlmacenaInv.Name = "lblAlmacenaInv";
			this.lblAlmacenaInv.Size = new global::System.Drawing.Size(133, 17);
			this.lblAlmacenaInv.TabIndex = 6;
			this.lblAlmacenaInv.Text = "Modifica inventarios";
			this.CheckBoxInventarios.AutoSize = true;
			this.CheckBoxInventarios.Location = new global::System.Drawing.Point(8, 20);
			this.CheckBoxInventarios.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.CheckBoxInventarios.Name = "CheckBoxInventarios";
			this.CheckBoxInventarios.Size = new global::System.Drawing.Size(155, 21);
			this.CheckBoxInventarios.TabIndex = 0;
			this.CheckBoxInventarios.Text = "Modifica inventarios";
			this.CheckBoxInventarios.UseVisualStyleBackColor = true;
			this.GroupBox5.Controls.Add(this.CheckBox_SepararProductos);
			this.GroupBox5.Controls.Add(this.CheckBoxAleatorio);
			this.GroupBox5.Controls.Add(this.CheckBoxContinuo);
			this.GroupBox5.Location = new global::System.Drawing.Point(375, 110);
			this.GroupBox5.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox5.Name = "GroupBox5";
			this.GroupBox5.Padding = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.GroupBox5.Size = new global::System.Drawing.Size(307, 108);
			this.GroupBox5.TabIndex = 7;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Cuentas";
			this.CheckBox_SepararProductos.AutoSize = true;
			this.CheckBox_SepararProductos.Location = new global::System.Drawing.Point(8, 79);
			this.CheckBox_SepararProductos.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.CheckBox_SepararProductos.Name = "CheckBox_SepararProductos";
			this.CheckBox_SepararProductos.Size = new global::System.Drawing.Size(172, 21);
			this.CheckBox_SepararProductos.TabIndex = 2;
			this.CheckBox_SepararProductos.Text = "Separar productos > 1";
			this.CheckBox_SepararProductos.UseVisualStyleBackColor = true;
			this.CheckBoxAleatorio.AutoSize = true;
			this.CheckBoxAleatorio.Location = new global::System.Drawing.Point(8, 53);
			this.CheckBoxAleatorio.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.CheckBoxAleatorio.Name = "CheckBoxAleatorio";
			this.CheckBoxAleatorio.Size = new global::System.Drawing.Size(126, 21);
			this.CheckBoxAleatorio.TabIndex = 1;
			this.CheckBoxAleatorio.Text = "Elegir Aleatorio";
			this.CheckBoxAleatorio.UseVisualStyleBackColor = true;
			this.CheckBoxContinuo.AutoSize = true;
			this.CheckBoxContinuo.Location = new global::System.Drawing.Point(8, 26);
			this.CheckBoxContinuo.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.CheckBoxContinuo.Name = "CheckBoxContinuo";
			this.CheckBoxContinuo.Size = new global::System.Drawing.Size(126, 21);
			this.CheckBoxContinuo.TabIndex = 0;
			this.CheckBoxContinuo.Text = "Elegir Continuo";
			this.CheckBoxContinuo.UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(689, 470);
			base.Controls.Add(this.GroupBox5);
			base.Controls.Add(this.GroupBox3);
			base.Controls.Add(this.GroupBox2);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.GroupBox1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			base.Name = "frmParametros";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "frmParametros";
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2formas).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureOtros).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxVales).EndInit();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox4.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxTarjeta).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxEfectivo).EndInit();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			this.GroupBox5.ResumeLayout(false);
			this.GroupBox5.PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x040005AD RID: 1453
		private global::System.ComponentModel.IContainer components;
	}
}
