namespace ModuloAdicional
{
	// Token: 0x02000020 RID: 32
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmReportes : global::System.Windows.Forms.Form
	{
		// Token: 0x06000F09 RID: 3849 RVA: 0x000F7634 File Offset: 0x000F5834
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000F0A RID: 3850 RVA: 0x000F7684 File Offset: 0x000F5884
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmReportes));
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.progBar = new global::System.Windows.Forms.ProgressBar();
			this.lblcounter = new global::System.Windows.Forms.Label();
			this.groupPeriodo = new global::System.Windows.Forms.GroupBox();
			this.lblexportar = new global::System.Windows.Forms.Label();
			this.btnExportar = new global::System.Windows.Forms.PictureBox();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.BtnHorario = new global::System.Windows.Forms.PictureBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.ComboBox1 = new global::System.Windows.Forms.ComboBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.cmbAnio = new global::System.Windows.Forms.ComboBox();
			this.dateHoraFin = new global::System.Windows.Forms.DateTimePicker();
			this.dateHoraIni = new global::System.Windows.Forms.DateTimePicker();
			this.dateFechaFin = new global::System.Windows.Forms.DateTimePicker();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.dateFechaIni = new global::System.Windows.Forms.DateTimePicker();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.CheckBoxProductosVendidos = new global::System.Windows.Forms.CheckBox();
			this.CheckBoxVentasDia = new global::System.Windows.Forms.CheckBox();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txtTotalVentaProductos = new global::System.Windows.Forms.TextBox();
			this.txtTotalCantidadProductos = new global::System.Windows.Forms.Label();
			this.lblTotalCantidad = new global::System.Windows.Forms.TextBox();
			this.lblpromoo0 = new global::System.Windows.Forms.Label();
			this.Pictureboxindicador1 = new global::System.Windows.Forms.PictureBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.lblTotalcuentas = new global::System.Windows.Forms.Label();
			this.txtTotalcuentas = new global::System.Windows.Forms.TextBox();
			this.lblpersonas = new global::System.Windows.Forms.Label();
			this.txtPersonas = new global::System.Windows.Forms.TextBox();
			this.lblpropinas = new global::System.Windows.Forms.Label();
			this.txtTotalPRopinas = new global::System.Windows.Forms.TextBox();
			this.lbltotalconimpuesto = new global::System.Windows.Forms.Label();
			this.txttotalconimpuesto = new global::System.Windows.Forms.TextBox();
			this.lblTotalIMpuestos = new global::System.Windows.Forms.Label();
			this.txtTotalImpuestos = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TxtTotalventabruta = new global::System.Windows.Forms.TextBox();
			this.lbltotaldescuentos = new global::System.Windows.Forms.Label();
			this.txttotaldescuentos = new global::System.Windows.Forms.TextBox();
			this.lbltotalbebidas = new global::System.Windows.Forms.Label();
			this.Txttotalbebidas = new global::System.Windows.Forms.TextBox();
			this.lbltotalcortesias = new global::System.Windows.Forms.Label();
			this.txtTotalCortesias = new global::System.Windows.Forms.TextBox();
			this.lbltotalalimentos = new global::System.Windows.Forms.Label();
			this.txttotalalimentos = new global::System.Windows.Forms.TextBox();
			this.lblTotalOtros = new global::System.Windows.Forms.Label();
			this.txtTotalOtros = new global::System.Windows.Forms.TextBox();
			this.btnVistaPrevia = new global::System.Windows.Forms.Button();
			this.Panel3 = new global::System.Windows.Forms.Panel();
			this.DgvDesencriptar = new global::System.Windows.Forms.DataGridView();
			this.dgvnotas = new global::System.Windows.Forms.DataGridView();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.groupPeriodo.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnExportar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnHorario).BeginInit();
			this.GroupBox1.SuspendLayout();
			this.Panel2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Pictureboxindicador1).BeginInit();
			this.GroupBox2.SuspendLayout();
			this.Panel3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DgvDesencriptar).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvnotas).BeginInit();
			base.SuspendLayout();
			this.Panel1.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Controls.Add(this.progBar);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(2102, 40);
			this.Panel1.TabIndex = 0;
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(2052, 0);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(50, 40);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 144;
			this.PictureBox1.TabStop = false;
			this.progBar.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.progBar.Location = new global::System.Drawing.Point(0, 0);
			this.progBar.Margin = new global::System.Windows.Forms.Padding(6);
			this.progBar.Name = "progBar";
			this.progBar.Size = new global::System.Drawing.Size(2102, 40);
			this.progBar.TabIndex = 145;
			this.progBar.Visible = false;
			this.lblcounter.AutoSize = true;
			this.lblcounter.Location = new global::System.Drawing.Point(1634, 246);
			this.lblcounter.Name = "lblcounter";
			this.lblcounter.Size = new global::System.Drawing.Size(77, 25);
			this.lblcounter.TabIndex = 145;
			this.lblcounter.Text = "Label4";
			this.lblcounter.Visible = false;
			this.groupPeriodo.Controls.Add(this.lblexportar);
			this.groupPeriodo.Controls.Add(this.btnExportar);
			this.groupPeriodo.Controls.Add(this.Label27);
			this.groupPeriodo.Controls.Add(this.BtnHorario);
			this.groupPeriodo.Controls.Add(this.Label18);
			this.groupPeriodo.Controls.Add(this.ComboBox1);
			this.groupPeriodo.Controls.Add(this.Label17);
			this.groupPeriodo.Controls.Add(this.cmbAnio);
			this.groupPeriodo.Controls.Add(this.dateHoraFin);
			this.groupPeriodo.Controls.Add(this.dateHoraIni);
			this.groupPeriodo.Controls.Add(this.dateFechaFin);
			this.groupPeriodo.Controls.Add(this.Label3);
			this.groupPeriodo.Controls.Add(this.dateFechaIni);
			this.groupPeriodo.Controls.Add(this.Label8);
			this.groupPeriodo.Location = new global::System.Drawing.Point(15, 3);
			this.groupPeriodo.Margin = new global::System.Windows.Forms.Padding(6);
			this.groupPeriodo.Name = "groupPeriodo";
			this.groupPeriodo.Padding = new global::System.Windows.Forms.Padding(6);
			this.groupPeriodo.Size = new global::System.Drawing.Size(676, 242);
			this.groupPeriodo.TabIndex = 2;
			this.groupPeriodo.TabStop = false;
			this.groupPeriodo.Text = "Periodo";
			this.lblexportar.AutoSize = true;
			this.lblexportar.Location = new global::System.Drawing.Point(191, 191);
			this.lblexportar.Name = "lblexportar";
			this.lblexportar.Size = new global::System.Drawing.Size(129, 25);
			this.lblexportar.TabIndex = 96;
			this.lblexportar.Text = "Exportar a : ";
			this.btnExportar.BackColor = global::System.Drawing.Color.Transparent;
			this.btnExportar.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnExportar.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnExportar.Image");
			this.btnExportar.Location = new global::System.Drawing.Point(324, 183);
			this.btnExportar.Name = "btnExportar";
			this.btnExportar.Size = new global::System.Drawing.Size(40, 40);
			this.btnExportar.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.btnExportar.TabIndex = 95;
			this.btnExportar.TabStop = false;
			this.Label27.AutoSize = true;
			this.Label27.Location = new global::System.Drawing.Point(388, 191);
			this.Label27.Name = "Label27";
			this.Label27.Size = new global::System.Drawing.Size(147, 25);
			this.Label27.TabIndex = 94;
			this.Label27.Text = "Editar horario:";
			this.BtnHorario.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.BtnHorario.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("BtnHorario.Image");
			this.BtnHorario.Location = new global::System.Drawing.Point(533, 182);
			this.BtnHorario.Name = "BtnHorario";
			this.BtnHorario.Size = new global::System.Drawing.Size(42, 42);
			this.BtnHorario.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.BtnHorario.TabIndex = 93;
			this.BtnHorario.TabStop = false;
			this.Label18.AutoSize = true;
			this.Label18.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label18.Location = new global::System.Drawing.Point(344, 40);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(59, 25);
			this.Label18.TabIndex = 89;
			this.Label18.Text = "Mes:";
			this.ComboBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ComboBox1.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.ComboBox1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.ComboBox1.FormattingEnabled = true;
			this.ComboBox1.Location = new global::System.Drawing.Point(416, 32);
			this.ComboBox1.Margin = new global::System.Windows.Forms.Padding(6);
			this.ComboBox1.Name = "ComboBox1";
			this.ComboBox1.Size = new global::System.Drawing.Size(234, 33);
			this.ComboBox1.TabIndex = 88;
			this.Label17.AutoSize = true;
			this.Label17.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label17.Location = new global::System.Drawing.Point(32, 40);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(6, 0, 6, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(62, 25);
			this.Label17.TabIndex = 87;
			this.Label17.Text = "Año: ";
			this.cmbAnio.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cmbAnio.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbAnio.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cmbAnio.FormattingEnabled = true;
			this.cmbAnio.Location = new global::System.Drawing.Point(108, 32);
			this.cmbAnio.Margin = new global::System.Windows.Forms.Padding(6);
			this.cmbAnio.Name = "cmbAnio";
			this.cmbAnio.Size = new global::System.Drawing.Size(194, 33);
			this.cmbAnio.Sorted = true;
			this.cmbAnio.TabIndex = 86;
			this.dateHoraFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateHoraFin.Enabled = false;
			this.dateHoraFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraFin.Location = new global::System.Drawing.Point(393, 135);
			this.dateHoraFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraFin.Name = "dateHoraFin";
			this.dateHoraFin.ShowUpDown = true;
			this.dateHoraFin.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraFin.TabIndex = 3;
			this.dateHoraFin.TabStop = false;
			this.dateHoraFin.Value = new global::System.DateTime(2022, 6, 15, 5, 59, 59, 0);
			this.dateHoraIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateHoraIni.Enabled = false;
			this.dateHoraIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.dateHoraIni.Location = new global::System.Drawing.Point(393, 85);
			this.dateHoraIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateHoraIni.Name = "dateHoraIni";
			this.dateHoraIni.ShowUpDown = true;
			this.dateHoraIni.Size = new global::System.Drawing.Size(182, 31);
			this.dateHoraIni.TabIndex = 1;
			this.dateHoraIni.TabStop = false;
			this.dateHoraIni.Value = new global::System.DateTime(2022, 6, 15, 6, 0, 0, 0);
			this.dateFechaFin.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaFin.Format = global::System.Windows.Forms.DateTimePickerFormat.Custom;
			this.dateFechaFin.Location = new global::System.Drawing.Point(180, 133);
			this.dateFechaFin.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaFin.Name = "dateFechaFin";
			this.dateFechaFin.Size = new global::System.Drawing.Size(196, 31);
			this.dateFechaFin.TabIndex = 1;
			this.Label3.AutoSize = true;
			this.Label3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label3.Location = new global::System.Drawing.Point(28, 133);
			this.Label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(143, 25);
			this.Label3.TabIndex = 82;
			this.Label3.Text = "Fecha FInal : ";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.dateFechaIni.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dateFechaIni.Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.dateFechaIni.Location = new global::System.Drawing.Point(180, 83);
			this.dateFechaIni.Margin = new global::System.Windows.Forms.Padding(4);
			this.dateFechaIni.MaxDate = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.dateFechaIni.MinDate = new global::System.DateTime(2017, 1, 1, 0, 0, 0, 0);
			this.dateFechaIni.Name = "dateFechaIni";
			this.dateFechaIni.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.dateFechaIni.Size = new global::System.Drawing.Size(196, 31);
			this.dateFechaIni.TabIndex = 0;
			this.dateFechaIni.Value = new global::System.DateTime(2021, 2, 28, 0, 0, 0, 0);
			this.Label8.AutoSize = true;
			this.Label8.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Label8.Location = new global::System.Drawing.Point(20, 83);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(151, 25);
			this.Label8.TabIndex = 80;
			this.Label8.Text = "Fecha Inicial : ";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox1.Controls.Add(this.CheckBoxProductosVendidos);
			this.GroupBox1.Controls.Add(this.CheckBoxVentasDia);
			this.GroupBox1.Location = new global::System.Drawing.Point(700, 5);
			this.GroupBox1.Name = "GroupBox1";
			this.GroupBox1.Size = new global::System.Drawing.Size(266, 114);
			this.GroupBox1.TabIndex = 3;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Reportes";
			this.CheckBoxProductosVendidos.AutoSize = true;
			this.CheckBoxProductosVendidos.Location = new global::System.Drawing.Point(18, 73);
			this.CheckBoxProductosVendidos.Name = "CheckBoxProductosVendidos";
			this.CheckBoxProductosVendidos.Size = new global::System.Drawing.Size(237, 29);
			this.CheckBoxProductosVendidos.TabIndex = 1;
			this.CheckBoxProductosVendidos.Text = "Productos Vendidos";
			this.CheckBoxProductosVendidos.UseVisualStyleBackColor = true;
			this.CheckBoxVentasDia.AutoSize = true;
			this.CheckBoxVentasDia.Checked = true;
			this.CheckBoxVentasDia.CheckState = global::System.Windows.Forms.CheckState.Checked;
			this.CheckBoxVentasDia.Location = new global::System.Drawing.Point(18, 33);
			this.CheckBoxVentasDia.Name = "CheckBoxVentasDia";
			this.CheckBoxVentasDia.Size = new global::System.Drawing.Size(183, 29);
			this.CheckBoxVentasDia.TabIndex = 0;
			this.CheckBoxVentasDia.Text = "Ventas por dia";
			this.CheckBoxVentasDia.UseVisualStyleBackColor = true;
			this.Panel2.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.Panel2.Controls.Add(this.lblcounter);
			this.Panel2.Controls.Add(this.GroupBox3);
			this.Panel2.Controls.Add(this.lblpromoo0);
			this.Panel2.Controls.Add(this.Pictureboxindicador1);
			this.Panel2.Controls.Add(this.GroupBox2);
			this.Panel2.Controls.Add(this.btnVistaPrevia);
			this.Panel2.Controls.Add(this.GroupBox1);
			this.Panel2.Controls.Add(this.groupPeriodo);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel2.Location = new global::System.Drawing.Point(0, 40);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(2102, 254);
			this.Panel2.TabIndex = 4;
			this.GroupBox3.Controls.Add(this.Label2);
			this.GroupBox3.Controls.Add(this.txtTotalVentaProductos);
			this.GroupBox3.Controls.Add(this.txtTotalCantidadProductos);
			this.GroupBox3.Controls.Add(this.lblTotalCantidad);
			this.GroupBox3.Location = new global::System.Drawing.Point(1022, 11);
			this.GroupBox3.Name = "GroupBox3";
			this.GroupBox3.Size = new global::System.Drawing.Size(354, 146);
			this.GroupBox3.TabIndex = 20;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Totales";
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(10, 84);
			this.Label2.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(131, 25);
			this.Label2.TabIndex = 152;
			this.Label2.Text = "Total venta :";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtTotalVentaProductos.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtTotalVentaProductos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalVentaProductos.Location = new global::System.Drawing.Point(159, 84);
			this.txtTotalVentaProductos.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtTotalVentaProductos.Name = "txtTotalVentaProductos";
			this.txtTotalVentaProductos.ReadOnly = true;
			this.txtTotalVentaProductos.Size = new global::System.Drawing.Size(176, 24);
			this.txtTotalVentaProductos.TabIndex = 151;
			this.txtTotalCantidadProductos.AutoSize = true;
			this.txtTotalCantidadProductos.Location = new global::System.Drawing.Point(30, 39);
			this.txtTotalCantidadProductos.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.txtTotalCantidadProductos.Name = "txtTotalCantidadProductos";
			this.txtTotalCantidadProductos.Size = new global::System.Drawing.Size(110, 25);
			this.txtTotalCantidadProductos.TabIndex = 150;
			this.txtTotalCantidadProductos.Text = "Cantidad :";
			this.txtTotalCantidadProductos.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lblTotalCantidad.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.lblTotalCantidad.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.lblTotalCantidad.Location = new global::System.Drawing.Point(159, 37);
			this.lblTotalCantidad.Margin = new global::System.Windows.Forms.Padding(4);
			this.lblTotalCantidad.Name = "lblTotalCantidad";
			this.lblTotalCantidad.ReadOnly = true;
			this.lblTotalCantidad.Size = new global::System.Drawing.Size(176, 24);
			this.lblTotalCantidad.TabIndex = 149;
			this.lblpromoo0.AutoSize = true;
			this.lblpromoo0.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.125f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblpromoo0.Location = new global::System.Drawing.Point(1081, 190);
			this.lblpromoo0.Name = "lblpromoo0";
			this.lblpromoo0.Size = new global::System.Drawing.Size(234, 24);
			this.lblpromoo0.TabIndex = 147;
			this.lblpromoo0.Text = "Precio en $ 0 o Promocion";
			this.Pictureboxindicador1.BackColor = global::System.Drawing.Color.LightBlue;
			this.Pictureboxindicador1.Location = new global::System.Drawing.Point(1031, 194);
			this.Pictureboxindicador1.Name = "Pictureboxindicador1";
			this.Pictureboxindicador1.Size = new global::System.Drawing.Size(40, 20);
			this.Pictureboxindicador1.TabIndex = 146;
			this.Pictureboxindicador1.TabStop = false;
			this.GroupBox2.Controls.Add(this.lblTotalcuentas);
			this.GroupBox2.Controls.Add(this.txtTotalcuentas);
			this.GroupBox2.Controls.Add(this.lblpersonas);
			this.GroupBox2.Controls.Add(this.txtPersonas);
			this.GroupBox2.Controls.Add(this.lblpropinas);
			this.GroupBox2.Controls.Add(this.txtTotalPRopinas);
			this.GroupBox2.Controls.Add(this.lbltotalconimpuesto);
			this.GroupBox2.Controls.Add(this.txttotalconimpuesto);
			this.GroupBox2.Controls.Add(this.lblTotalIMpuestos);
			this.GroupBox2.Controls.Add(this.txtTotalImpuestos);
			this.GroupBox2.Controls.Add(this.Label1);
			this.GroupBox2.Controls.Add(this.TxtTotalventabruta);
			this.GroupBox2.Controls.Add(this.lbltotaldescuentos);
			this.GroupBox2.Controls.Add(this.txttotaldescuentos);
			this.GroupBox2.Controls.Add(this.lbltotalbebidas);
			this.GroupBox2.Controls.Add(this.Txttotalbebidas);
			this.GroupBox2.Controls.Add(this.lbltotalcortesias);
			this.GroupBox2.Controls.Add(this.txtTotalCortesias);
			this.GroupBox2.Controls.Add(this.lbltotalalimentos);
			this.GroupBox2.Controls.Add(this.txttotalalimentos);
			this.GroupBox2.Controls.Add(this.lblTotalOtros);
			this.GroupBox2.Controls.Add(this.txtTotalOtros);
			this.GroupBox2.Location = new global::System.Drawing.Point(1038, 8);
			this.GroupBox2.Name = "GroupBox2";
			this.GroupBox2.Size = new global::System.Drawing.Size(984, 168);
			this.GroupBox2.TabIndex = 19;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Totales";
			this.lblTotalcuentas.AutoSize = true;
			this.lblTotalcuentas.Location = new global::System.Drawing.Point(666, 94);
			this.lblTotalcuentas.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lblTotalcuentas.Name = "lblTotalcuentas";
			this.lblTotalcuentas.Size = new global::System.Drawing.Size(104, 25);
			this.lblTotalcuentas.TabIndex = 152;
			this.lblTotalcuentas.Text = "Cuentas :";
			this.lblTotalcuentas.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtTotalcuentas.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtTotalcuentas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalcuentas.Location = new global::System.Drawing.Point(778, 94);
			this.txtTotalcuentas.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtTotalcuentas.Name = "txtTotalcuentas";
			this.txtTotalcuentas.ReadOnly = true;
			this.txtTotalcuentas.Size = new global::System.Drawing.Size(176, 24);
			this.txtTotalcuentas.TabIndex = 151;
			this.lblpersonas.AutoSize = true;
			this.lblpersonas.Location = new global::System.Drawing.Point(655, 61);
			this.lblpersonas.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lblpersonas.Name = "lblpersonas";
			this.lblpersonas.Size = new global::System.Drawing.Size(115, 25);
			this.lblpersonas.TabIndex = 150;
			this.lblpersonas.Text = "Personas :";
			this.lblpersonas.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtPersonas.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtPersonas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtPersonas.Location = new global::System.Drawing.Point(778, 61);
			this.txtPersonas.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtPersonas.Name = "txtPersonas";
			this.txtPersonas.ReadOnly = true;
			this.txtPersonas.Size = new global::System.Drawing.Size(176, 24);
			this.txtPersonas.TabIndex = 149;
			this.lblpropinas.AutoSize = true;
			this.lblpropinas.Location = new global::System.Drawing.Point(662, 28);
			this.lblpropinas.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lblpropinas.Name = "lblpropinas";
			this.lblpropinas.Size = new global::System.Drawing.Size(109, 25);
			this.lblpropinas.TabIndex = 148;
			this.lblpropinas.Text = "Propinas :";
			this.lblpropinas.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtTotalPRopinas.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtTotalPRopinas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalPRopinas.Location = new global::System.Drawing.Point(778, 28);
			this.txtTotalPRopinas.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtTotalPRopinas.Name = "txtTotalPRopinas";
			this.txtTotalPRopinas.ReadOnly = true;
			this.txtTotalPRopinas.Size = new global::System.Drawing.Size(176, 24);
			this.txtTotalPRopinas.TabIndex = 147;
			this.lbltotalconimpuesto.AutoSize = true;
			this.lbltotalconimpuesto.Location = new global::System.Drawing.Point(345, 127);
			this.lbltotalconimpuesto.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lbltotalconimpuesto.Name = "lbltotalconimpuesto";
			this.lbltotalconimpuesto.Size = new global::System.Drawing.Size(182, 25);
			this.lbltotalconimpuesto.TabIndex = 146;
			this.lbltotalconimpuesto.Text = "Total c/impuesto :";
			this.lbltotalconimpuesto.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txttotalconimpuesto.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txttotalconimpuesto.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txttotalconimpuesto.Location = new global::System.Drawing.Point(535, 127);
			this.txttotalconimpuesto.Margin = new global::System.Windows.Forms.Padding(4);
			this.txttotalconimpuesto.Name = "txttotalconimpuesto";
			this.txttotalconimpuesto.ReadOnly = true;
			this.txttotalconimpuesto.Size = new global::System.Drawing.Size(178, 24);
			this.txttotalconimpuesto.TabIndex = 145;
			this.lblTotalIMpuestos.AutoSize = true;
			this.lblTotalIMpuestos.Location = new global::System.Drawing.Point(338, 94);
			this.lblTotalIMpuestos.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lblTotalIMpuestos.Name = "lblTotalIMpuestos";
			this.lblTotalIMpuestos.Size = new global::System.Drawing.Size(122, 25);
			this.lblTotalIMpuestos.TabIndex = 144;
			this.lblTotalIMpuestos.Text = "Impuestos :";
			this.lblTotalIMpuestos.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtTotalImpuestos.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtTotalImpuestos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalImpuestos.Location = new global::System.Drawing.Point(468, 94);
			this.txtTotalImpuestos.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtTotalImpuestos.Name = "txtTotalImpuestos";
			this.txtTotalImpuestos.ReadOnly = true;
			this.txtTotalImpuestos.Size = new global::System.Drawing.Size(178, 24);
			this.txtTotalImpuestos.TabIndex = 143;
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(6, 127);
			this.Label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(137, 25);
			this.Label1.TabIndex = 142;
			this.Label1.Text = "Venta Bruta :";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.TxtTotalventabruta.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.TxtTotalventabruta.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.TxtTotalventabruta.Location = new global::System.Drawing.Point(151, 127);
			this.TxtTotalventabruta.Margin = new global::System.Windows.Forms.Padding(4);
			this.TxtTotalventabruta.Name = "TxtTotalventabruta";
			this.TxtTotalventabruta.ReadOnly = true;
			this.TxtTotalventabruta.Size = new global::System.Drawing.Size(178, 24);
			this.TxtTotalventabruta.TabIndex = 141;
			this.lbltotaldescuentos.AutoSize = true;
			this.lbltotaldescuentos.Location = new global::System.Drawing.Point(322, 61);
			this.lbltotaldescuentos.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lbltotaldescuentos.Name = "lbltotaldescuentos";
			this.lbltotaldescuentos.Size = new global::System.Drawing.Size(138, 25);
			this.lbltotaldescuentos.TabIndex = 140;
			this.lbltotaldescuentos.Text = "Descuentos :";
			this.lbltotaldescuentos.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txttotaldescuentos.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txttotaldescuentos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txttotaldescuentos.Location = new global::System.Drawing.Point(468, 61);
			this.txttotaldescuentos.Margin = new global::System.Windows.Forms.Padding(4);
			this.txttotaldescuentos.Name = "txttotaldescuentos";
			this.txttotaldescuentos.ReadOnly = true;
			this.txttotaldescuentos.Size = new global::System.Drawing.Size(178, 24);
			this.txttotaldescuentos.TabIndex = 139;
			this.lbltotalbebidas.AutoSize = true;
			this.lbltotalbebidas.Location = new global::System.Drawing.Point(22, 61);
			this.lbltotalbebidas.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lbltotalbebidas.Name = "lbltotalbebidas";
			this.lbltotalbebidas.Size = new global::System.Drawing.Size(102, 25);
			this.lbltotalbebidas.TabIndex = 136;
			this.lbltotalbebidas.Text = "Bebidas :";
			this.lbltotalbebidas.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Txttotalbebidas.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.Txttotalbebidas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.Txttotalbebidas.Location = new global::System.Drawing.Point(139, 61);
			this.Txttotalbebidas.Margin = new global::System.Windows.Forms.Padding(4);
			this.Txttotalbebidas.Name = "Txttotalbebidas";
			this.Txttotalbebidas.ReadOnly = true;
			this.Txttotalbebidas.Size = new global::System.Drawing.Size(176, 24);
			this.Txttotalbebidas.TabIndex = 135;
			this.lbltotalcortesias.AutoSize = true;
			this.lbltotalcortesias.Location = new global::System.Drawing.Point(345, 28);
			this.lbltotalcortesias.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lbltotalcortesias.Name = "lbltotalcortesias";
			this.lbltotalcortesias.Size = new global::System.Drawing.Size(115, 25);
			this.lbltotalcortesias.TabIndex = 138;
			this.lbltotalcortesias.Text = "Cortesias :";
			this.lbltotalcortesias.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtTotalCortesias.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtTotalCortesias.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalCortesias.Location = new global::System.Drawing.Point(468, 28);
			this.txtTotalCortesias.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtTotalCortesias.Name = "txtTotalCortesias";
			this.txtTotalCortesias.ReadOnly = true;
			this.txtTotalCortesias.Size = new global::System.Drawing.Size(178, 24);
			this.txtTotalCortesias.TabIndex = 137;
			this.lbltotalalimentos.AutoSize = true;
			this.lbltotalalimentos.Location = new global::System.Drawing.Point(6, 28);
			this.lbltotalalimentos.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lbltotalalimentos.Name = "lbltotalalimentos";
			this.lbltotalalimentos.Size = new global::System.Drawing.Size(118, 25);
			this.lbltotalalimentos.TabIndex = 132;
			this.lbltotalalimentos.Text = "Alimentos :";
			this.lbltotalalimentos.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txttotalalimentos.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txttotalalimentos.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txttotalalimentos.Location = new global::System.Drawing.Point(139, 28);
			this.txttotalalimentos.Margin = new global::System.Windows.Forms.Padding(4);
			this.txttotalalimentos.Name = "txttotalalimentos";
			this.txttotalalimentos.ReadOnly = true;
			this.txttotalalimentos.Size = new global::System.Drawing.Size(176, 24);
			this.txttotalalimentos.TabIndex = 131;
			this.lblTotalOtros.AutoSize = true;
			this.lblTotalOtros.Location = new global::System.Drawing.Point(48, 94);
			this.lblTotalOtros.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.lblTotalOtros.Name = "lblTotalOtros";
			this.lblTotalOtros.Size = new global::System.Drawing.Size(76, 25);
			this.lblTotalOtros.TabIndex = 136;
			this.lblTotalOtros.Text = "Otros :";
			this.lblTotalOtros.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtTotalOtros.BackColor = global::System.Drawing.SystemColors.InactiveBorder;
			this.txtTotalOtros.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.txtTotalOtros.Location = new global::System.Drawing.Point(139, 94);
			this.txtTotalOtros.Margin = new global::System.Windows.Forms.Padding(4);
			this.txtTotalOtros.Name = "txtTotalOtros";
			this.txtTotalOtros.ReadOnly = true;
			this.txtTotalOtros.Size = new global::System.Drawing.Size(176, 24);
			this.txtTotalOtros.TabIndex = 135;
			this.btnVistaPrevia.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.btnVistaPrevia.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnVistaPrevia.FlatAppearance.BorderColor = global::System.Drawing.Color.Black;
			this.btnVistaPrevia.FlatAppearance.BorderSize = 2;
			this.btnVistaPrevia.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnVistaPrevia.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 13.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnVistaPrevia.ForeColor = global::System.Drawing.Color.White;
			this.btnVistaPrevia.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnVistaPrevia.Image");
			this.btnVistaPrevia.ImageAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnVistaPrevia.Location = new global::System.Drawing.Point(700, 145);
			this.btnVistaPrevia.Margin = new global::System.Windows.Forms.Padding(6);
			this.btnVistaPrevia.Name = "btnVistaPrevia";
			this.btnVistaPrevia.Size = new global::System.Drawing.Size(312, 99);
			this.btnVistaPrevia.TabIndex = 18;
			this.btnVistaPrevia.Text = "Vista Previa";
			this.btnVistaPrevia.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			this.btnVistaPrevia.UseVisualStyleBackColor = false;
			this.Panel3.BackColor = global::System.Drawing.SystemColors.Control;
			this.Panel3.Controls.Add(this.DgvDesencriptar);
			this.Panel3.Controls.Add(this.dgvnotas);
			this.Panel3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.Panel3.Location = new global::System.Drawing.Point(0, 294);
			this.Panel3.Name = "Panel3";
			this.Panel3.Size = new global::System.Drawing.Size(2102, 905);
			this.Panel3.TabIndex = 5;
			this.DgvDesencriptar.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.DgvDesencriptar.Location = new global::System.Drawing.Point(1788, 36);
			this.DgvDesencriptar.Name = "DgvDesencriptar";
			this.DgvDesencriptar.RowTemplate.Height = 33;
			this.DgvDesencriptar.Size = new global::System.Drawing.Size(250, 348);
			this.DgvDesencriptar.TabIndex = 26;
			this.DgvDesencriptar.Visible = false;
			this.dgvnotas.AllowUserToAddRows = false;
			this.dgvnotas.AllowUserToDeleteRows = false;
			this.dgvnotas.AllowUserToResizeColumns = false;
			this.dgvnotas.AllowUserToResizeRows = false;
			this.dgvnotas.BackgroundColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.dgvnotas.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.dgvnotas.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dgvnotas.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.dgvnotas.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.dgvnotas.GridColor = global::System.Drawing.SystemColors.AppWorkspace;
			this.dgvnotas.Location = new global::System.Drawing.Point(0, 0);
			this.dgvnotas.Margin = new global::System.Windows.Forms.Padding(4);
			this.dgvnotas.MultiSelect = false;
			this.dgvnotas.Name = "dgvnotas";
			this.dgvnotas.ReadOnly = true;
			this.dgvnotas.RowHeadersVisible = false;
			this.dgvnotas.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.dgvnotas.RowTemplate.Height = 24;
			this.dgvnotas.Size = new global::System.Drawing.Size(2102, 905);
			this.dgvnotas.TabIndex = 25;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(12f, 25f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(2102, 1199);
			base.Controls.Add(this.Panel3);
			base.Controls.Add(this.Panel2);
			base.Controls.Add(this.Panel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Name = "frmReportes";
			this.Text = "frmReportes";
			this.Panel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.groupPeriodo.ResumeLayout(false);
			this.groupPeriodo.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.btnExportar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.BtnHorario).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.Panel2.ResumeLayout(false);
			this.Panel2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.GroupBox3.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Pictureboxindicador1).EndInit();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.Panel3.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.DgvDesencriptar).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.dgvnotas).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x040006C7 RID: 1735
		private global::System.ComponentModel.IContainer components;
	}
}
