namespace ModuloAdicional
{
	// Token: 0x02000021 RID: 33
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmServConfig : global::System.Windows.Forms.Form
	{
		// Token: 0x06000F90 RID: 3984 RVA: 0x000FD0B0 File Offset: 0x000FB2B0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06000F91 RID: 3985 RVA: 0x000FD100 File Offset: 0x000FB300
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::ModuloAdicional.frmServConfig));
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txtNomServ = new global::System.Windows.Forms.TextBox();
			this.btnGuardarConexion = new global::System.Windows.Forms.Button();
			this.btnProbarConexion = new global::System.Windows.Forms.Button();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txtBaseDatos = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.txtContrasena = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.txtInicioSesion = new global::System.Windows.Forms.TextBox();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.txtCte = new global::System.Windows.Forms.TextBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.txtInstancia = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txtID = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.btnCrearDBO = new global::System.Windows.Forms.Button();
			this.GroupBoxBase_Modulo = new global::System.Windows.Forms.GroupBox();
			this.PictureBoxModOK = new global::System.Windows.Forms.PictureBox();
			this.PictureBoxModCancelar = new global::System.Windows.Forms.PictureBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txtbaseDatos_Modulo = new global::System.Windows.Forms.TextBox();
			this.GroupBox_ConexionSQL = new global::System.Windows.Forms.GroupBox();
			this.PictureBoxError = new global::System.Windows.Forms.PictureBox();
			this.PictureBoxCorrecto = new global::System.Windows.Forms.PictureBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.lblid_licenciajc = new global::System.Windows.Forms.Label();
			this.BackgroundWorker1 = new global::System.ComponentModel.BackgroundWorker();
			this.GroupBox_Adicionales = new global::System.Windows.Forms.GroupBox();
			this.txtNombreArchivo = new global::System.Windows.Forms.TextBox();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.lblcodigoEmpresa = new global::System.Windows.Forms.Label();
			this.lblfechaRegistro = new global::System.Windows.Forms.Label();
			this.lblbombresr = new global::System.Windows.Forms.Label();
			this.lblrfc = new global::System.Windows.Forms.Label();
			this.PanelDatosLicencia = new global::System.Windows.Forms.Panel();
			this.txtLicenciaID = new global::System.Windows.Forms.TextBox();
			this.txtLicenciaCliente = new global::System.Windows.Forms.TextBox();
			this.txtLicenciaServidor = new global::System.Windows.Forms.TextBox();
			this.txtCodigoEmpresa = new global::System.Windows.Forms.TextBox();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.CheckBox1 = new global::System.Windows.Forms.CheckBox();
			this.CheckBox2 = new global::System.Windows.Forms.CheckBox();
			this.GroupBoxEstacion = new global::System.Windows.Forms.GroupBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox3 = new global::System.Windows.Forms.PictureBox();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.cboBaseDatos = new global::System.Windows.Forms.ComboBox();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.GroupBoxBase_Modulo.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxModOK).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxModCancelar).BeginInit();
			this.GroupBox_ConexionSQL.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxError).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxCorrecto).BeginInit();
			this.Panel1.SuspendLayout();
			this.GroupBox_Adicionales.SuspendLayout();
			this.PanelDatosLicencia.SuspendLayout();
			this.Panel2.SuspendLayout();
			this.GroupBoxEstacion.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).BeginInit();
			base.SuspendLayout();
			this.Label3.AutoSize = true;
			this.Label3.Location = new global::System.Drawing.Point(51, 23);
			this.Label3.Name = "Label3";
			this.Label3.Size = new global::System.Drawing.Size(97, 17);
			this.Label3.TabIndex = 115;
			this.Label3.Text = "Servidor o IP :";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtNomServ.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtNomServ.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtNomServ.Location = new global::System.Drawing.Point(155, 21);
			this.txtNomServ.Name = "txtNomServ";
			this.txtNomServ.Size = new global::System.Drawing.Size(380, 22);
			this.txtNomServ.TabIndex = 110;
			this.txtNomServ.Text = "SERVIDOR";
			this.btnGuardarConexion.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom;
			this.btnGuardarConexion.BackColor = global::System.Drawing.Color.FromArgb(82, 135, 235);
			this.btnGuardarConexion.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.btnGuardarConexion.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnGuardarConexion.FlatAppearance.BorderSize = 0;
			this.btnGuardarConexion.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.btnGuardarConexion.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnGuardarConexion.ForeColor = global::System.Drawing.Color.White;
			this.btnGuardarConexion.ImageAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.btnGuardarConexion.Location = new global::System.Drawing.Point(443, 373);
			this.btnGuardarConexion.Name = "btnGuardarConexion";
			this.btnGuardarConexion.Size = new global::System.Drawing.Size(321, 56);
			this.btnGuardarConexion.TabIndex = 113;
			this.btnGuardarConexion.TabStop = false;
			this.btnGuardarConexion.Text = "Guardar Conexión";
			this.btnGuardarConexion.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageAboveText;
			this.btnGuardarConexion.UseVisualStyleBackColor = false;
			this.btnProbarConexion.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.btnProbarConexion.BackColor = global::System.Drawing.SystemColors.GradientActiveCaption;
			this.btnProbarConexion.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.btnProbarConexion.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.btnProbarConexion.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnProbarConexion.Location = new global::System.Drawing.Point(617, 106);
			this.btnProbarConexion.Name = "btnProbarConexion";
			this.btnProbarConexion.Size = new global::System.Drawing.Size(117, 56);
			this.btnProbarConexion.TabIndex = 112;
			this.btnProbarConexion.TabStop = false;
			this.btnProbarConexion.Text = "Probar Conexión";
			this.btnProbarConexion.UseVisualStyleBackColor = false;
			this.Label1.AutoSize = true;
			this.Label1.Location = new global::System.Drawing.Point(18, 81);
			this.Label1.Name = "Label1";
			this.Label1.Size = new global::System.Drawing.Size(130, 17);
			this.Label1.TabIndex = 117;
			this.Label1.Text = "Base de datos SR :";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtBaseDatos.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtBaseDatos.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtBaseDatos.Location = new global::System.Drawing.Point(155, 79);
			this.txtBaseDatos.Name = "txtBaseDatos";
			this.txtBaseDatos.Size = new global::System.Drawing.Size(380, 22);
			this.txtBaseDatos.TabIndex = 116;
			this.Label2.AutoSize = true;
			this.Label2.Location = new global::System.Drawing.Point(59, 141);
			this.Label2.Name = "Label2";
			this.Label2.Size = new global::System.Drawing.Size(89, 17);
			this.Label2.TabIndex = 121;
			this.Label2.Text = "Contraseña :";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtContrasena.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtContrasena.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtContrasena.Location = new global::System.Drawing.Point(155, 138);
			this.txtContrasena.Name = "txtContrasena";
			this.txtContrasena.PasswordChar = '*';
			this.txtContrasena.Size = new global::System.Drawing.Size(171, 22);
			this.txtContrasena.TabIndex = 120;
			this.txtContrasena.Text = "National09";
			this.Label4.AutoSize = true;
			this.Label4.Location = new global::System.Drawing.Point(34, 111);
			this.Label4.Name = "Label4";
			this.Label4.Size = new global::System.Drawing.Size(113, 17);
			this.Label4.TabIndex = 119;
			this.Label4.Text = "Inicio de sesión :";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtInicioSesion.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtInicioSesion.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtInicioSesion.Location = new global::System.Drawing.Point(155, 108);
			this.txtInicioSesion.Name = "txtInicioSesion";
			this.txtInicioSesion.Size = new global::System.Drawing.Size(171, 22);
			this.txtInicioSesion.TabIndex = 118;
			this.txtInicioSesion.Text = "sa";
			this.Button1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Button1.BackColor = global::System.Drawing.Color.Green;
			this.Button1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.Button1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Bold);
			this.Button1.ForeColor = global::System.Drawing.SystemColors.ControlLightLight;
			this.Button1.Location = new global::System.Drawing.Point(617, 20);
			this.Button1.Name = "Button1";
			this.Button1.Size = new global::System.Drawing.Size(111, 56);
			this.Button1.TabIndex = 122;
			this.Button1.TabStop = false;
			this.Button1.Text = "Buscar Servidor";
			this.Button1.UseVisualStyleBackColor = false;
			this.Label5.AutoSize = true;
			this.Label5.Location = new global::System.Drawing.Point(7, 25);
			this.Label5.Name = "Label5";
			this.Label5.Size = new global::System.Drawing.Size(59, 17);
			this.Label5.TabIndex = 124;
			this.Label5.Text = "Cliente :";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtCte.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtCte.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtCte.Location = new global::System.Drawing.Point(74, 23);
			this.txtCte.Name = "txtCte";
			this.txtCte.Size = new global::System.Drawing.Size(198, 22);
			this.txtCte.TabIndex = 123;
			this.PictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.PictureBox1.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.PictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new global::System.Drawing.Point(742, 0);
			this.PictureBox1.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new global::System.Drawing.Size(30, 32);
			this.PictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox1.TabIndex = 125;
			this.PictureBox1.TabStop = false;
			this.Label6.AutoSize = true;
			this.Label6.Location = new global::System.Drawing.Point(76, 51);
			this.Label6.Name = "Label6";
			this.Label6.Size = new global::System.Drawing.Size(72, 17);
			this.Label6.TabIndex = 127;
			this.Label6.Text = "Instancia :";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtInstancia.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtInstancia.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtInstancia.Location = new global::System.Drawing.Point(155, 49);
			this.txtInstancia.Name = "txtInstancia";
			this.txtInstancia.Size = new global::System.Drawing.Size(380, 22);
			this.txtInstancia.TabIndex = 126;
			this.txtInstancia.Text = "NATIONALSOFT";
			this.Label7.AutoSize = true;
			this.Label7.Location = new global::System.Drawing.Point(41, 56);
			this.Label7.Name = "Label7";
			this.Label7.Size = new global::System.Drawing.Size(27, 17);
			this.Label7.TabIndex = 129;
			this.Label7.Text = "Id :";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtID.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtID.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtID.Location = new global::System.Drawing.Point(74, 52);
			this.txtID.Name = "txtID";
			this.txtID.ReadOnly = true;
			this.txtID.Size = new global::System.Drawing.Size(199, 22);
			this.txtID.TabIndex = 128;
			this.Label8.AutoSize = true;
			this.Label8.Location = new global::System.Drawing.Point(192, 499);
			this.Label8.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label8.Name = "Label8";
			this.Label8.Size = new global::System.Drawing.Size(51, 17);
			this.Label8.TabIndex = 130;
			this.Label8.Text = "Label8";
			this.Label8.Visible = false;
			this.btnCrearDBO.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.btnCrearDBO.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnCrearDBO.Location = new global::System.Drawing.Point(148, 47);
			this.btnCrearDBO.Margin = new global::System.Windows.Forms.Padding(2);
			this.btnCrearDBO.Name = "btnCrearDBO";
			this.btnCrearDBO.Size = new global::System.Drawing.Size(107, 35);
			this.btnCrearDBO.TabIndex = 131;
			this.btnCrearDBO.Text = "Crear DBO";
			this.btnCrearDBO.UseVisualStyleBackColor = true;
			this.GroupBoxBase_Modulo.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.GroupBoxBase_Modulo.Controls.Add(this.PictureBoxModOK);
			this.GroupBoxBase_Modulo.Controls.Add(this.PictureBoxModCancelar);
			this.GroupBoxBase_Modulo.Controls.Add(this.Label15);
			this.GroupBoxBase_Modulo.Controls.Add(this.txtbaseDatos_Modulo);
			this.GroupBoxBase_Modulo.Controls.Add(this.btnCrearDBO);
			this.GroupBoxBase_Modulo.Location = new global::System.Drawing.Point(8, 263);
			this.GroupBoxBase_Modulo.Margin = new global::System.Windows.Forms.Padding(2);
			this.GroupBoxBase_Modulo.Name = "GroupBoxBase_Modulo";
			this.GroupBoxBase_Modulo.Padding = new global::System.Windows.Forms.Padding(2);
			this.GroupBoxBase_Modulo.Size = new global::System.Drawing.Size(259, 86);
			this.GroupBoxBase_Modulo.TabIndex = 132;
			this.GroupBoxBase_Modulo.TabStop = false;
			this.GroupBoxBase_Modulo.Text = "Base de datos Modulo Servidor";
			this.PictureBoxModOK.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxModOK.Image");
			this.PictureBoxModOK.Location = new global::System.Drawing.Point(104, 47);
			this.PictureBoxModOK.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBoxModOK.Name = "PictureBoxModOK";
			this.PictureBoxModOK.Size = new global::System.Drawing.Size(37, 35);
			this.PictureBoxModOK.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxModOK.TabIndex = 138;
			this.PictureBoxModOK.TabStop = false;
			this.PictureBoxModOK.Visible = false;
			this.PictureBoxModCancelar.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxModCancelar.Image");
			this.PictureBoxModCancelar.Location = new global::System.Drawing.Point(104, 47);
			this.PictureBoxModCancelar.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBoxModCancelar.Name = "PictureBoxModCancelar";
			this.PictureBoxModCancelar.Size = new global::System.Drawing.Size(37, 35);
			this.PictureBoxModCancelar.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxModCancelar.TabIndex = 138;
			this.PictureBoxModCancelar.TabStop = false;
			this.PictureBoxModCancelar.Visible = false;
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label15.ForeColor = global::System.Drawing.Color.Red;
			this.Label15.Location = new global::System.Drawing.Point(191, 23);
			this.Label15.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label15.Name = "Label15";
			this.Label15.Size = new global::System.Drawing.Size(26, 17);
			this.Label15.TabIndex = 136;
			this.Label15.Text = "(*)";
			this.txtbaseDatos_Modulo.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtbaseDatos_Modulo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtbaseDatos_Modulo.Location = new global::System.Drawing.Point(10, 22);
			this.txtbaseDatos_Modulo.Name = "txtbaseDatos_Modulo";
			this.txtbaseDatos_Modulo.Size = new global::System.Drawing.Size(178, 22);
			this.txtbaseDatos_Modulo.TabIndex = 129;
			this.txtbaseDatos_Modulo.Text = "AppConfig";
			this.GroupBox_ConexionSQL.Controls.Add(this.PictureBoxError);
			this.GroupBox_ConexionSQL.Controls.Add(this.PictureBoxCorrecto);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label14);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label13);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label12);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label11);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label10);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label3);
			this.GroupBox_ConexionSQL.Controls.Add(this.txtNomServ);
			this.GroupBox_ConexionSQL.Controls.Add(this.txtBaseDatos);
			this.GroupBox_ConexionSQL.Controls.Add(this.Button1);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label1);
			this.GroupBox_ConexionSQL.Controls.Add(this.txtInicioSesion);
			this.GroupBox_ConexionSQL.Controls.Add(this.btnProbarConexion);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label4);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label6);
			this.GroupBox_ConexionSQL.Controls.Add(this.txtContrasena);
			this.GroupBox_ConexionSQL.Controls.Add(this.txtInstancia);
			this.GroupBox_ConexionSQL.Controls.Add(this.Label2);
			this.GroupBox_ConexionSQL.Location = new global::System.Drawing.Point(9, 52);
			this.GroupBox_ConexionSQL.Margin = new global::System.Windows.Forms.Padding(2);
			this.GroupBox_ConexionSQL.Name = "GroupBox_ConexionSQL";
			this.GroupBox_ConexionSQL.Padding = new global::System.Windows.Forms.Padding(2);
			this.GroupBox_ConexionSQL.Size = new global::System.Drawing.Size(743, 168);
			this.GroupBox_ConexionSQL.TabIndex = 133;
			this.GroupBox_ConexionSQL.TabStop = false;
			this.GroupBox_ConexionSQL.Text = "Parametros Conexión SQL";
			this.PictureBoxError.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxError.Image");
			this.PictureBoxError.Location = new global::System.Drawing.Point(374, 108);
			this.PictureBoxError.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBoxError.Name = "PictureBoxError";
			this.PictureBoxError.Size = new global::System.Drawing.Size(67, 54);
			this.PictureBoxError.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxError.TabIndex = 137;
			this.PictureBoxError.TabStop = false;
			this.PictureBoxError.Visible = false;
			this.PictureBoxCorrecto.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBoxCorrecto.Image");
			this.PictureBoxCorrecto.Location = new global::System.Drawing.Point(374, 108);
			this.PictureBoxCorrecto.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBoxCorrecto.Name = "PictureBoxCorrecto";
			this.PictureBoxCorrecto.Size = new global::System.Drawing.Size(67, 54);
			this.PictureBoxCorrecto.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBoxCorrecto.TabIndex = 136;
			this.PictureBoxCorrecto.TabStop = false;
			this.PictureBoxCorrecto.Visible = false;
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label14.ForeColor = global::System.Drawing.Color.Red;
			this.Label14.Location = new global::System.Drawing.Point(329, 140);
			this.Label14.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label14.Name = "Label14";
			this.Label14.Size = new global::System.Drawing.Size(26, 17);
			this.Label14.TabIndex = 135;
			this.Label14.Text = "(*)";
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label13.ForeColor = global::System.Drawing.Color.Red;
			this.Label13.Location = new global::System.Drawing.Point(329, 109);
			this.Label13.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label13.Name = "Label13";
			this.Label13.Size = new global::System.Drawing.Size(26, 17);
			this.Label13.TabIndex = 134;
			this.Label13.Text = "(*)";
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label12.ForeColor = global::System.Drawing.Color.Red;
			this.Label12.Location = new global::System.Drawing.Point(537, 81);
			this.Label12.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label12.Name = "Label12";
			this.Label12.Size = new global::System.Drawing.Size(26, 17);
			this.Label12.TabIndex = 133;
			this.Label12.Text = "(*)";
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label11.ForeColor = global::System.Drawing.Color.Red;
			this.Label11.Location = new global::System.Drawing.Point(538, 51);
			this.Label11.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label11.Name = "Label11";
			this.Label11.Size = new global::System.Drawing.Size(26, 17);
			this.Label11.TabIndex = 132;
			this.Label11.Text = "(*)";
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label10.ForeColor = global::System.Drawing.Color.Red;
			this.Label10.Location = new global::System.Drawing.Point(538, 23);
			this.Label10.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new global::System.Drawing.Size(26, 17);
			this.Label10.TabIndex = 131;
			this.Label10.Text = "(*)";
			this.Panel1.BackColor = global::System.Drawing.SystemColors.ActiveCaption;
			this.Panel1.Controls.Add(this.Label9);
			this.Panel1.Controls.Add(this.PictureBox1);
			this.Panel1.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.Panel1.Location = new global::System.Drawing.Point(0, 0);
			this.Panel1.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new global::System.Drawing.Size(772, 32);
			this.Panel1.TabIndex = 134;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label9.Location = new global::System.Drawing.Point(5, 7);
			this.Label9.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label9.Name = "Label9";
			this.Label9.Size = new global::System.Drawing.Size(212, 18);
			this.Label9.TabIndex = 126;
			this.Label9.Text = "Configuracion de Conexión";
			this.lblid_licenciajc.AutoSize = true;
			this.lblid_licenciajc.Location = new global::System.Drawing.Point(263, 481);
			this.lblid_licenciajc.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblid_licenciajc.Name = "lblid_licenciajc";
			this.lblid_licenciajc.Size = new global::System.Drawing.Size(59, 17);
			this.lblid_licenciajc.TabIndex = 127;
			this.lblid_licenciajc.Text = "Label18";
			this.lblid_licenciajc.Visible = false;
			this.GroupBox_Adicionales.Controls.Add(this.txtNombreArchivo);
			this.GroupBox_Adicionales.Controls.Add(this.Label24);
			this.GroupBox_Adicionales.Controls.Add(this.Label16);
			this.GroupBox_Adicionales.Controls.Add(this.Label5);
			this.GroupBox_Adicionales.Controls.Add(this.txtCte);
			this.GroupBox_Adicionales.Controls.Add(this.txtID);
			this.GroupBox_Adicionales.Controls.Add(this.Label7);
			this.GroupBox_Adicionales.Location = new global::System.Drawing.Point(443, 228);
			this.GroupBox_Adicionales.Margin = new global::System.Windows.Forms.Padding(2);
			this.GroupBox_Adicionales.Name = "GroupBox_Adicionales";
			this.GroupBox_Adicionales.Padding = new global::System.Windows.Forms.Padding(2);
			this.GroupBox_Adicionales.Size = new global::System.Drawing.Size(309, 121);
			this.GroupBox_Adicionales.TabIndex = 135;
			this.GroupBox_Adicionales.TabStop = false;
			this.GroupBox_Adicionales.Text = "Adicionales";
			this.txtNombreArchivo.BackColor = global::System.Drawing.SystemColors.Window;
			this.txtNombreArchivo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.txtNombreArchivo.Location = new global::System.Drawing.Point(113, 87);
			this.txtNombreArchivo.Name = "txtNombreArchivo";
			this.txtNombreArchivo.ReadOnly = true;
			this.txtNombreArchivo.Size = new global::System.Drawing.Size(160, 22);
			this.txtNombreArchivo.TabIndex = 138;
			this.Label24.AutoSize = true;
			this.Label24.Location = new global::System.Drawing.Point(7, 90);
			this.Label24.Name = "Label24";
			this.Label24.Size = new global::System.Drawing.Size(100, 17);
			this.Label24.TabIndex = 139;
			this.Label24.Text = "Nomb. Archivo";
			this.Label24.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label16.ForeColor = global::System.Drawing.Color.Red;
			this.Label16.Location = new global::System.Drawing.Point(275, 25);
			this.Label16.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label16.Name = "Label16";
			this.Label16.Size = new global::System.Drawing.Size(26, 17);
			this.Label16.TabIndex = 137;
			this.Label16.Text = "(*)";
			this.lblcodigoEmpresa.AutoSize = true;
			this.lblcodigoEmpresa.Location = new global::System.Drawing.Point(157, 499);
			this.lblcodigoEmpresa.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblcodigoEmpresa.Name = "lblcodigoEmpresa";
			this.lblcodigoEmpresa.Size = new global::System.Drawing.Size(119, 17);
			this.lblcodigoEmpresa.TabIndex = 136;
			this.lblcodigoEmpresa.Text = "lblcodigoempresa";
			this.lblcodigoEmpresa.Visible = false;
			this.lblfechaRegistro.AutoSize = true;
			this.lblfechaRegistro.Location = new global::System.Drawing.Point(363, 481);
			this.lblfechaRegistro.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblfechaRegistro.Name = "lblfechaRegistro";
			this.lblfechaRegistro.Size = new global::System.Drawing.Size(59, 17);
			this.lblfechaRegistro.TabIndex = 137;
			this.lblfechaRegistro.Text = "Label18";
			this.lblfechaRegistro.Visible = false;
			this.lblbombresr.AutoSize = true;
			this.lblbombresr.Location = new global::System.Drawing.Point(154, 481);
			this.lblbombresr.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblbombresr.Name = "lblbombresr";
			this.lblbombresr.Size = new global::System.Drawing.Size(82, 17);
			this.lblbombresr.TabIndex = 138;
			this.lblbombresr.Text = "lnlbombresr";
			this.lblbombresr.Visible = false;
			this.lblrfc.AutoSize = true;
			this.lblrfc.Location = new global::System.Drawing.Point(313, 501);
			this.lblrfc.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.lblrfc.Name = "lblrfc";
			this.lblrfc.Size = new global::System.Drawing.Size(38, 17);
			this.lblrfc.TabIndex = 139;
			this.lblrfc.Text = "lblrfc";
			this.lblrfc.Visible = false;
			this.PanelDatosLicencia.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			this.PanelDatosLicencia.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.PanelDatosLicencia.Controls.Add(this.txtLicenciaID);
			this.PanelDatosLicencia.Controls.Add(this.txtLicenciaCliente);
			this.PanelDatosLicencia.Controls.Add(this.txtLicenciaServidor);
			this.PanelDatosLicencia.Controls.Add(this.txtCodigoEmpresa);
			this.PanelDatosLicencia.Controls.Add(this.Label22);
			this.PanelDatosLicencia.Controls.Add(this.Label21);
			this.PanelDatosLicencia.Controls.Add(this.Label20);
			this.PanelDatosLicencia.Controls.Add(this.Label19);
			this.PanelDatosLicencia.Controls.Add(this.Label18);
			this.PanelDatosLicencia.Controls.Add(this.Label17);
			this.PanelDatosLicencia.Controls.Add(this.Panel2);
			this.PanelDatosLicencia.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.PanelDatosLicencia.Location = new global::System.Drawing.Point(0, 32);
			this.PanelDatosLicencia.Margin = new global::System.Windows.Forms.Padding(2);
			this.PanelDatosLicencia.Name = "PanelDatosLicencia";
			this.PanelDatosLicencia.Size = new global::System.Drawing.Size(772, 409);
			this.PanelDatosLicencia.TabIndex = 140;
			this.txtLicenciaID.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtLicenciaID.Location = new global::System.Drawing.Point(292, 213);
			this.txtLicenciaID.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtLicenciaID.Name = "txtLicenciaID";
			this.txtLicenciaID.ReadOnly = true;
			this.txtLicenciaID.Size = new global::System.Drawing.Size(247, 22);
			this.txtLicenciaID.TabIndex = 123;
			this.txtLicenciaCliente.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtLicenciaCliente.Location = new global::System.Drawing.Point(292, 173);
			this.txtLicenciaCliente.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtLicenciaCliente.Name = "txtLicenciaCliente";
			this.txtLicenciaCliente.ReadOnly = true;
			this.txtLicenciaCliente.Size = new global::System.Drawing.Size(247, 22);
			this.txtLicenciaCliente.TabIndex = 122;
			this.txtLicenciaServidor.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtLicenciaServidor.Location = new global::System.Drawing.Point(292, 134);
			this.txtLicenciaServidor.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtLicenciaServidor.Name = "txtLicenciaServidor";
			this.txtLicenciaServidor.ReadOnly = true;
			this.txtLicenciaServidor.Size = new global::System.Drawing.Size(247, 22);
			this.txtLicenciaServidor.TabIndex = 121;
			this.txtCodigoEmpresa.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.txtCodigoEmpresa.Location = new global::System.Drawing.Point(292, 97);
			this.txtCodigoEmpresa.Margin = new global::System.Windows.Forms.Padding(2);
			this.txtCodigoEmpresa.Name = "txtCodigoEmpresa";
			this.txtCodigoEmpresa.ReadOnly = true;
			this.txtCodigoEmpresa.Size = new global::System.Drawing.Size(247, 22);
			this.txtCodigoEmpresa.TabIndex = 120;
			this.Label22.AutoSize = true;
			this.Label22.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label22.ForeColor = global::System.Drawing.Color.Black;
			this.Label22.Location = new global::System.Drawing.Point(152, 99);
			this.Label22.Name = "Label22";
			this.Label22.Size = new global::System.Drawing.Size(131, 17);
			this.Label22.TabIndex = 119;
			this.Label22.Text = "Codigo Software:";
			this.Label22.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label21.AutoSize = true;
			this.Label21.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label21.ForeColor = global::System.Drawing.Color.Black;
			this.Label21.Location = new global::System.Drawing.Point(169, 216);
			this.Label21.Name = "Label21";
			this.Label21.Size = new global::System.Drawing.Size(114, 17);
			this.Label21.TabIndex = 118;
			this.Label21.Text = "Codigo Unico :";
			this.Label21.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label20.ForeColor = global::System.Drawing.Color.Black;
			this.Label20.Location = new global::System.Drawing.Point(213, 177);
			this.Label20.Name = "Label20";
			this.Label20.Size = new global::System.Drawing.Size(68, 17);
			this.Label20.TabIndex = 117;
			this.Label20.Text = "Cliente :";
			this.Label20.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label19.ForeColor = global::System.Drawing.Color.Black;
			this.Label19.Location = new global::System.Drawing.Point(204, 138);
			this.Label19.Name = "Label19";
			this.Label19.Size = new global::System.Drawing.Size(79, 17);
			this.Label19.TabIndex = 116;
			this.Label19.Text = "Servidor :";
			this.Label19.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label18.AutoSize = true;
			this.Label18.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label18.ForeColor = global::System.Drawing.Color.Black;
			this.Label18.Location = new global::System.Drawing.Point(152, 55);
			this.Label18.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label18.Name = "Label18";
			this.Label18.Size = new global::System.Drawing.Size(464, 17);
			this.Label18.TabIndex = 2;
			this.Label18.Text = "Envia una foto de esta pantalla a tu Administrador del sistema!";
			this.Label17.AutoSize = true;
			this.Label17.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 7.875f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label17.ForeColor = global::System.Drawing.Color.Black;
			this.Label17.Location = new global::System.Drawing.Point(271, 22);
			this.Label17.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label17.Name = "Label17";
			this.Label17.Size = new global::System.Drawing.Size(248, 17);
			this.Label17.TabIndex = 1;
			this.Label17.Text = "El Modulo se configuro con exito!";
			this.Panel2.Controls.Add(this.Button2);
			this.Panel2.Dock = global::System.Windows.Forms.DockStyle.Bottom;
			this.Panel2.Location = new global::System.Drawing.Point(0, 369);
			this.Panel2.Margin = new global::System.Windows.Forms.Padding(2);
			this.Panel2.Name = "Panel2";
			this.Panel2.Size = new global::System.Drawing.Size(770, 38);
			this.Panel2.TabIndex = 0;
			this.Button2.BackColor = global::System.Drawing.Color.Green;
			this.Button2.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.Button2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.125f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button2.ForeColor = global::System.Drawing.Color.White;
			this.Button2.Location = new global::System.Drawing.Point(477, 0);
			this.Button2.Margin = new global::System.Windows.Forms.Padding(2);
			this.Button2.Name = "Button2";
			this.Button2.Size = new global::System.Drawing.Size(293, 38);
			this.Button2.TabIndex = 0;
			this.Button2.Text = "Continuar";
			this.Button2.UseVisualStyleBackColor = false;
			this.CheckBox1.AutoSize = true;
			this.CheckBox1.Location = new global::System.Drawing.Point(9, 234);
			this.CheckBox1.Margin = new global::System.Windows.Forms.Padding(2);
			this.CheckBox1.Name = "CheckBox1";
			this.CheckBox1.Size = new global::System.Drawing.Size(83, 21);
			this.CheckBox1.TabIndex = 141;
			this.CheckBox1.Text = "Servidor";
			this.CheckBox1.UseVisualStyleBackColor = true;
			this.CheckBox2.AutoSize = true;
			this.CheckBox2.Location = new global::System.Drawing.Point(95, 234);
			this.CheckBox2.Margin = new global::System.Windows.Forms.Padding(2);
			this.CheckBox2.Name = "CheckBox2";
			this.CheckBox2.Size = new global::System.Drawing.Size(84, 21);
			this.CheckBox2.TabIndex = 142;
			this.CheckBox2.Text = "Estación";
			this.CheckBox2.UseVisualStyleBackColor = true;
			this.GroupBoxEstacion.Controls.Add(this.PictureBox2);
			this.GroupBoxEstacion.Controls.Add(this.PictureBox3);
			this.GroupBoxEstacion.Controls.Add(this.Button3);
			this.GroupBoxEstacion.Controls.Add(this.Label23);
			this.GroupBoxEstacion.Controls.Add(this.cboBaseDatos);
			this.GroupBoxEstacion.Location = new global::System.Drawing.Point(8, 263);
			this.GroupBoxEstacion.Margin = new global::System.Windows.Forms.Padding(2);
			this.GroupBoxEstacion.Name = "GroupBoxEstacion";
			this.GroupBoxEstacion.Padding = new global::System.Windows.Forms.Padding(2);
			this.GroupBoxEstacion.Size = new global::System.Drawing.Size(384, 119);
			this.GroupBoxEstacion.TabIndex = 143;
			this.GroupBoxEstacion.TabStop = false;
			this.GroupBoxEstacion.Text = "Base de datos Modulo Estación";
			this.PictureBox2.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox2.Image");
			this.PictureBox2.Location = new global::System.Drawing.Point(301, 52);
			this.PictureBox2.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(67, 54);
			this.PictureBox2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox2.TabIndex = 139;
			this.PictureBox2.TabStop = false;
			this.PictureBox2.Visible = false;
			this.PictureBox3.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("PictureBox3.Image");
			this.PictureBox3.Location = new global::System.Drawing.Point(301, 52);
			this.PictureBox3.Margin = new global::System.Windows.Forms.Padding(2);
			this.PictureBox3.Name = "PictureBox3";
			this.PictureBox3.Size = new global::System.Drawing.Size(67, 54);
			this.PictureBox3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.PictureBox3.TabIndex = 138;
			this.PictureBox3.TabStop = false;
			this.PictureBox3.Visible = false;
			this.Button3.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.Button3.BackColor = global::System.Drawing.SystemColors.GradientActiveCaption;
			this.Button3.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.Button3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Button3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Button3.Location = new global::System.Drawing.Point(82, 76);
			this.Button3.Name = "Button3";
			this.Button3.Size = new global::System.Drawing.Size(213, 30);
			this.Button3.TabIndex = 113;
			this.Button3.TabStop = false;
			this.Button3.Text = "Probar Conexión";
			this.Button3.UseVisualStyleBackColor = false;
			this.Label23.AutoSize = true;
			this.Label23.Location = new global::System.Drawing.Point(4, 23);
			this.Label23.Margin = new global::System.Windows.Forms.Padding(2, 0, 2, 0);
			this.Label23.Name = "Label23";
			this.Label23.Size = new global::System.Drawing.Size(221, 17);
			this.Label23.TabIndex = 24;
			this.Label23.Text = "Elige la base de datos del Modulo";
			this.cboBaseDatos.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.cboBaseDatos.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cboBaseDatos.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.cboBaseDatos.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cboBaseDatos.FormattingEnabled = true;
			this.cboBaseDatos.Location = new global::System.Drawing.Point(6, 46);
			this.cboBaseDatos.Margin = new global::System.Windows.Forms.Padding(4);
			this.cboBaseDatos.Name = "cboBaseDatos";
			this.cboBaseDatos.Size = new global::System.Drawing.Size(291, 26);
			this.cboBaseDatos.TabIndex = 23;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.AutoSize = true;
			this.BackColor = global::System.Drawing.SystemColors.InactiveCaption;
			base.ClientSize = new global::System.Drawing.Size(772, 441);
			base.Controls.Add(this.PanelDatosLicencia);
			base.Controls.Add(this.GroupBoxEstacion);
			base.Controls.Add(this.CheckBox2);
			base.Controls.Add(this.CheckBox1);
			base.Controls.Add(this.lblid_licenciajc);
			base.Controls.Add(this.lblrfc);
			base.Controls.Add(this.lblbombresr);
			base.Controls.Add(this.lblfechaRegistro);
			base.Controls.Add(this.lblcodigoEmpresa);
			base.Controls.Add(this.GroupBox_Adicionales);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.GroupBox_ConexionSQL);
			base.Controls.Add(this.GroupBoxBase_Modulo);
			base.Controls.Add(this.btnGuardarConexion);
			base.Controls.Add(this.Label8);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Margin = new global::System.Windows.Forms.Padding(4);
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "frmServConfig";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Servidores";
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.GroupBoxBase_Modulo.ResumeLayout(false);
			this.GroupBoxBase_Modulo.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxModOK).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxModCancelar).EndInit();
			this.GroupBox_ConexionSQL.ResumeLayout(false);
			this.GroupBox_ConexionSQL.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxError).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBoxCorrecto).EndInit();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.GroupBox_Adicionales.ResumeLayout(false);
			this.GroupBox_Adicionales.PerformLayout();
			this.PanelDatosLicencia.ResumeLayout(false);
			this.PanelDatosLicencia.PerformLayout();
			this.Panel2.ResumeLayout(false);
			this.GroupBoxEstacion.ResumeLayout(false);
			this.GroupBoxEstacion.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox3).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04000701 RID: 1793
		private global::System.ComponentModel.IContainer components;
	}
}
